/**
 * Report filters.
 *
 * The generated client in `features/api/` is regenerated by Orval and carries a
 * "do not edit manually" header, so the wider filter surface the API now accepts
 * lives here instead. Orval's URL builders serialise any key/value pair they are
 * handed, so passing these through works without touching generated code.
 */
export interface ReportFilters {
    /** Inclusive, YYYY-MM-DD. */
    start_date?: string;
    /** Inclusive of the whole day, YYYY-MM-DD. */
    end_date?: string;
    /** Omit for the whole organization. A manager is always pinned to their own. */
    station_id?: string;
    customer_id?: string;
}

/** Echoed back by every report so the UI can label what it is showing. */
export interface ReportMeta {
    start_date: string;
    end_date: string;
    station_id: string | null;
    customer_id: string | null;
}

export interface DebtAgingRow {
    customer_id: string;
    customer_name: string;
    total_debt: number;
    credit_limit: number;
    buckets: {
        '0-30': number;
        '31-60': number;
        '61-90': number;
        '90+': number;
    };
}

export interface DebtAgingReport {
    data: DebtAgingRow[];
    meta: ReportMeta & { as_of: string; total_outstanding: number };
}

export interface ProfitAndLossReport {
    data: {
        sales: number;
        costs: number;
        taxes: number;
        net_profit: number;
        shift_count: number;
        lifting_count: number;
    };
    meta: ReportMeta;
}

export interface TaxSummaryReport {
    data: {
        tax_collected: number;
        tax_paid: number;
        net_tax: number;
    };
    meta: ReportMeta;
}

export interface VarianceTrendPoint {
    date: string;
    total_variance: number;
    total_stock_variance: number;
    shift_count: number;
}

export interface VarianceTrendReport {
    data: VarianceTrendPoint[];
    meta: { start_date: string; end_date: string; station_id: string | null };
}

export interface StatementLine {
    id: string;
    date: string;
    shift_number: string | null;
    station_name: string | null;
    vehicle_reg: string | null;
    amount: number;
}

export interface StatementInvoice {
    id: string;
    invoice_number: string;
    date: string;
    total_amount: number;
}

export interface CustomerStatement {
    data: {
        customer: {
            id: string;
            name: string;
            email: string;
            phone: string | null;
            tax_pin: string | null;
            credit_limit: number;
            current_balance: number;
        };
        opening_balance: number;
        period_charges: number;
        closing_balance: number;
        lines: StatementLine[];
        invoices: StatementInvoice[];
    };
    meta: ReportMeta & { line_count: number };
}

/** A named period the user can pick, resolved to concrete dates on selection. */
export type PeriodPresetId =
    | 'this_month'
    | 'last_month'
    | 'last_7'
    | 'last_30'
    | 'last_90'
    | 'this_year'
    | 'custom';
