/**
 * Generated by orval v8.0.3 🍺
 * Do not edit manually.
 * Petrol Integrity System API Documentation
 * OpenAPI spec version: 0.0.1
 */
import {
  useMutation,
  useQuery
} from '@tanstack/react-query';
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  MutationFunction,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult
} from '@tanstack/react-query';

import type {
  AuthenticationExceptionResponse,
  AuthorizationExceptionResponse,
  ModelNotFoundExceptionResponse,
  StationsDestroy200,
  StationsIndex200,
  StationsShow200,
  StationsStore200,
  StationsUpdate200,
  StoreStationRequest,
  UpdateStationRequest,
  ValidationExceptionResponse
} from '.././model';

import { customInstance } from '../../../lib/axios';


type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];



/**
 * @summary List all stations for the organization
 */
export type stationsIndexResponse200 = {
  data: StationsIndex200
  status: 200
}

export type stationsIndexResponse401 = {
  data: AuthenticationExceptionResponse
  status: 401
}

export type stationsIndexResponse403 = {
  data: AuthorizationExceptionResponse
  status: 403
}
    
export type stationsIndexResponseSuccess = (stationsIndexResponse200) & {
  headers: Headers;
};
export type stationsIndexResponseError = (stationsIndexResponse401 | stationsIndexResponse403) & {
  headers: Headers;
};

export type stationsIndexResponse = (stationsIndexResponseSuccess | stationsIndexResponseError)

export const getStationsIndexUrl = () => {


  

  return `/v1/stations`
}

export const stationsIndex = async ( options?: RequestInit): Promise<stationsIndexResponse> => {
  
  return customInstance<stationsIndexResponse>(getStationsIndexUrl(),
  {      
    ...options,
    method: 'GET'
    
    
  }
);}





export const getStationsIndexQueryKey = () => {
    return [
    `/v1/stations`
    ] as const;
    }

    
export const getStationsIndexQueryOptions = <TData = Awaited<ReturnType<typeof stationsIndex>>, TError = AuthenticationExceptionResponse | AuthorizationExceptionResponse>( options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof stationsIndex>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getStationsIndexQueryKey();

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof stationsIndex>>> = ({ signal }) => stationsIndex({ signal, ...requestOptions });

      

      

   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof stationsIndex>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type StationsIndexQueryResult = NonNullable<Awaited<ReturnType<typeof stationsIndex>>>
export type StationsIndexQueryError = AuthenticationExceptionResponse | AuthorizationExceptionResponse


export function useStationsIndex<TData = Awaited<ReturnType<typeof stationsIndex>>, TError = AuthenticationExceptionResponse | AuthorizationExceptionResponse>(
  options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof stationsIndex>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof stationsIndex>>,
          TError,
          Awaited<ReturnType<typeof stationsIndex>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useStationsIndex<TData = Awaited<ReturnType<typeof stationsIndex>>, TError = AuthenticationExceptionResponse | AuthorizationExceptionResponse>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof stationsIndex>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof stationsIndex>>,
          TError,
          Awaited<ReturnType<typeof stationsIndex>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useStationsIndex<TData = Awaited<ReturnType<typeof stationsIndex>>, TError = AuthenticationExceptionResponse | AuthorizationExceptionResponse>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof stationsIndex>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary List all stations for the organization
 */

export function useStationsIndex<TData = Awaited<ReturnType<typeof stationsIndex>>, TError = AuthenticationExceptionResponse | AuthorizationExceptionResponse>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof stationsIndex>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getStationsIndexQueryOptions(options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}




/**
 * @summary Create a new station
 */
export type stationsStoreResponse200 = {
  data: StationsStore200
  status: 200
}

export type stationsStoreResponse401 = {
  data: AuthenticationExceptionResponse
  status: 401
}

export type stationsStoreResponse403 = {
  data: AuthorizationExceptionResponse
  status: 403
}

export type stationsStoreResponse422 = {
  data: ValidationExceptionResponse
  status: 422
}
    
export type stationsStoreResponseSuccess = (stationsStoreResponse200) & {
  headers: Headers;
};
export type stationsStoreResponseError = (stationsStoreResponse401 | stationsStoreResponse403 | stationsStoreResponse422) & {
  headers: Headers;
};

export type stationsStoreResponse = (stationsStoreResponseSuccess | stationsStoreResponseError)

export const getStationsStoreUrl = () => {


  

  return `/v1/stations`
}

export const stationsStore = async (storeStationRequest: StoreStationRequest, options?: RequestInit): Promise<stationsStoreResponse> => {
  
  return customInstance<stationsStoreResponse>(getStationsStoreUrl(),
  {      
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(
      storeStationRequest,)
  }
);}




export const getStationsStoreMutationOptions = <TError = AuthenticationExceptionResponse | AuthorizationExceptionResponse | ValidationExceptionResponse,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof stationsStore>>, TError,{data: StoreStationRequest}, TContext>, request?: SecondParameter<typeof customInstance>}
): UseMutationOptions<Awaited<ReturnType<typeof stationsStore>>, TError,{data: StoreStationRequest}, TContext> => {

const mutationKey = ['stationsStore'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof stationsStore>>, {data: StoreStationRequest}> = (props) => {
          const {data} = props ?? {};

          return  stationsStore(data,requestOptions)
        }



        


  return  { mutationFn, ...mutationOptions }}

    export type StationsStoreMutationResult = NonNullable<Awaited<ReturnType<typeof stationsStore>>>
    export type StationsStoreMutationBody = StoreStationRequest
    export type StationsStoreMutationError = AuthenticationExceptionResponse | AuthorizationExceptionResponse | ValidationExceptionResponse

    /**
 * @summary Create a new station
 */
export const useStationsStore = <TError = AuthenticationExceptionResponse | AuthorizationExceptionResponse | ValidationExceptionResponse,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof stationsStore>>, TError,{data: StoreStationRequest}, TContext>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof stationsStore>>,
        TError,
        {data: StoreStationRequest},
        TContext
      > => {
      return useMutation(getStationsStoreMutationOptions(options), queryClient);
    }
    /**
 * @summary Show a specific station
 */
export type stationsShowResponse200 = {
  data: StationsShow200
  status: 200
}

export type stationsShowResponse401 = {
  data: AuthenticationExceptionResponse
  status: 401
}

export type stationsShowResponse403 = {
  data: AuthorizationExceptionResponse
  status: 403
}

export type stationsShowResponse404 = {
  data: ModelNotFoundExceptionResponse
  status: 404
}
    
export type stationsShowResponseSuccess = (stationsShowResponse200) & {
  headers: Headers;
};
export type stationsShowResponseError = (stationsShowResponse401 | stationsShowResponse403 | stationsShowResponse404) & {
  headers: Headers;
};

export type stationsShowResponse = (stationsShowResponseSuccess | stationsShowResponseError)

export const getStationsShowUrl = (station: string,) => {


  

  return `/v1/stations/${station}`
}

export const stationsShow = async (station: string, options?: RequestInit): Promise<stationsShowResponse> => {
  
  return customInstance<stationsShowResponse>(getStationsShowUrl(station),
  {      
    ...options,
    method: 'GET'
    
    
  }
);}





export const getStationsShowQueryKey = (station: string,) => {
    return [
    `/v1/stations/${station}`
    ] as const;
    }

    
export const getStationsShowQueryOptions = <TData = Awaited<ReturnType<typeof stationsShow>>, TError = AuthenticationExceptionResponse | AuthorizationExceptionResponse | ModelNotFoundExceptionResponse>(station: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof stationsShow>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getStationsShowQueryKey(station);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof stationsShow>>> = ({ signal }) => stationsShow(station, { signal, ...requestOptions });

      

      

   return  { queryKey, queryFn, enabled: !!(station), ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof stationsShow>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type StationsShowQueryResult = NonNullable<Awaited<ReturnType<typeof stationsShow>>>
export type StationsShowQueryError = AuthenticationExceptionResponse | AuthorizationExceptionResponse | ModelNotFoundExceptionResponse


export function useStationsShow<TData = Awaited<ReturnType<typeof stationsShow>>, TError = AuthenticationExceptionResponse | AuthorizationExceptionResponse | ModelNotFoundExceptionResponse>(
 station: string, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof stationsShow>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof stationsShow>>,
          TError,
          Awaited<ReturnType<typeof stationsShow>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useStationsShow<TData = Awaited<ReturnType<typeof stationsShow>>, TError = AuthenticationExceptionResponse | AuthorizationExceptionResponse | ModelNotFoundExceptionResponse>(
 station: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof stationsShow>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof stationsShow>>,
          TError,
          Awaited<ReturnType<typeof stationsShow>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useStationsShow<TData = Awaited<ReturnType<typeof stationsShow>>, TError = AuthenticationExceptionResponse | AuthorizationExceptionResponse | ModelNotFoundExceptionResponse>(
 station: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof stationsShow>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Show a specific station
 */

export function useStationsShow<TData = Awaited<ReturnType<typeof stationsShow>>, TError = AuthenticationExceptionResponse | AuthorizationExceptionResponse | ModelNotFoundExceptionResponse>(
 station: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof stationsShow>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getStationsShowQueryOptions(station,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}




/**
 * @summary Update station details
 */
export type stationsUpdateResponse200 = {
  data: StationsUpdate200
  status: 200
}

export type stationsUpdateResponse401 = {
  data: AuthenticationExceptionResponse
  status: 401
}

export type stationsUpdateResponse403 = {
  data: AuthorizationExceptionResponse
  status: 403
}

export type stationsUpdateResponse404 = {
  data: ModelNotFoundExceptionResponse
  status: 404
}

export type stationsUpdateResponse422 = {
  data: ValidationExceptionResponse
  status: 422
}
    
export type stationsUpdateResponseSuccess = (stationsUpdateResponse200) & {
  headers: Headers;
};
export type stationsUpdateResponseError = (stationsUpdateResponse401 | stationsUpdateResponse403 | stationsUpdateResponse404 | stationsUpdateResponse422) & {
  headers: Headers;
};

export type stationsUpdateResponse = (stationsUpdateResponseSuccess | stationsUpdateResponseError)

export const getStationsUpdateUrl = (station: string,) => {


  

  return `/v1/stations/${station}`
}

export const stationsUpdate = async (station: string,
    updateStationRequest: UpdateStationRequest, options?: RequestInit): Promise<stationsUpdateResponse> => {
  
  return customInstance<stationsUpdateResponse>(getStationsUpdateUrl(station),
  {      
    ...options,
    method: 'PUT',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(
      updateStationRequest,)
  }
);}




export const getStationsUpdateMutationOptions = <TError = AuthenticationExceptionResponse | AuthorizationExceptionResponse | ModelNotFoundExceptionResponse | ValidationExceptionResponse,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof stationsUpdate>>, TError,{station: string;data: UpdateStationRequest}, TContext>, request?: SecondParameter<typeof customInstance>}
): UseMutationOptions<Awaited<ReturnType<typeof stationsUpdate>>, TError,{station: string;data: UpdateStationRequest}, TContext> => {

const mutationKey = ['stationsUpdate'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof stationsUpdate>>, {station: string;data: UpdateStationRequest}> = (props) => {
          const {station,data} = props ?? {};

          return  stationsUpdate(station,data,requestOptions)
        }



        


  return  { mutationFn, ...mutationOptions }}

    export type StationsUpdateMutationResult = NonNullable<Awaited<ReturnType<typeof stationsUpdate>>>
    export type StationsUpdateMutationBody = UpdateStationRequest
    export type StationsUpdateMutationError = AuthenticationExceptionResponse | AuthorizationExceptionResponse | ModelNotFoundExceptionResponse | ValidationExceptionResponse

    /**
 * @summary Update station details
 */
export const useStationsUpdate = <TError = AuthenticationExceptionResponse | AuthorizationExceptionResponse | ModelNotFoundExceptionResponse | ValidationExceptionResponse,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof stationsUpdate>>, TError,{station: string;data: UpdateStationRequest}, TContext>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof stationsUpdate>>,
        TError,
        {station: string;data: UpdateStationRequest},
        TContext
      > => {
      return useMutation(getStationsUpdateMutationOptions(options), queryClient);
    }
    /**
 * @summary Delete a station
 */
export type stationsDestroyResponse200 = {
  data: StationsDestroy200
  status: 200
}

export type stationsDestroyResponse401 = {
  data: AuthenticationExceptionResponse
  status: 401
}

export type stationsDestroyResponse403 = {
  data: AuthorizationExceptionResponse
  status: 403
}

export type stationsDestroyResponse404 = {
  data: ModelNotFoundExceptionResponse
  status: 404
}
    
export type stationsDestroyResponseSuccess = (stationsDestroyResponse200) & {
  headers: Headers;
};
export type stationsDestroyResponseError = (stationsDestroyResponse401 | stationsDestroyResponse403 | stationsDestroyResponse404) & {
  headers: Headers;
};

export type stationsDestroyResponse = (stationsDestroyResponseSuccess | stationsDestroyResponseError)

export const getStationsDestroyUrl = (station: string,) => {


  

  return `/v1/stations/${station}`
}

export const stationsDestroy = async (station: string, options?: RequestInit): Promise<stationsDestroyResponse> => {
  
  return customInstance<stationsDestroyResponse>(getStationsDestroyUrl(station),
  {      
    ...options,
    method: 'DELETE'
    
    
  }
);}




export const getStationsDestroyMutationOptions = <TError = AuthenticationExceptionResponse | AuthorizationExceptionResponse | ModelNotFoundExceptionResponse,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof stationsDestroy>>, TError,{station: string}, TContext>, request?: SecondParameter<typeof customInstance>}
): UseMutationOptions<Awaited<ReturnType<typeof stationsDestroy>>, TError,{station: string}, TContext> => {

const mutationKey = ['stationsDestroy'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof stationsDestroy>>, {station: string}> = (props) => {
          const {station} = props ?? {};

          return  stationsDestroy(station,requestOptions)
        }



        


  return  { mutationFn, ...mutationOptions }}

    export type StationsDestroyMutationResult = NonNullable<Awaited<ReturnType<typeof stationsDestroy>>>
    
    export type StationsDestroyMutationError = AuthenticationExceptionResponse | AuthorizationExceptionResponse | ModelNotFoundExceptionResponse

    /**
 * @summary Delete a station
 */
export const useStationsDestroy = <TError = AuthenticationExceptionResponse | AuthorizationExceptionResponse | ModelNotFoundExceptionResponse,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof stationsDestroy>>, TError,{station: string}, TContext>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof stationsDestroy>>,
        TError,
        {station: string},
        TContext
      > => {
      return useMutation(getStationsDestroyMutationOptions(options), queryClient);
    }
    