<?php

/*
|--------------------------------------------------------------------------
| Administrator Agreement
|--------------------------------------------------------------------------
|
| The terms an administrator must accept before they can use the system.
|
| Held as structured data rather than markdown so the mobile application can
| render it natively — no markdown dependency, and the headings stay legible
| on a phone. The version is what makes acceptance durable: bump it when the
| terms change substantively and every administrator is asked again, while
| the previous acceptances remain on record against the version they agreed
| to. Never edit the text of a published version in place; add a new one.
|
*/

return [

    // Enforcement can only be switched off in the test environment — see
    // EnsureAgreementAccepted. The suite's existing tests act as
    // administrators of a running system, who would long since have accepted;
    // the agreement's own tests turn it back on to exercise the gate.
    'enforce' => env('AGREEMENT_ENFORCE', true),

    'version' => '1.0',

    'effective_date' => '16 September 2026',

    // Only these roles are asked. A manager never sees it, and the platform
    // owner is not bound by terms they are the one offering.
    'required_roles' => ['admin'],

    'title' => 'Administrator Agreement and Terms of Use',

    'intro' => 'This Agreement governs your use of the Petrol Integrity System as an Administrator. Read it in full. You are being asked to accept it because an Administrator can create accounts, configure equipment, alter prices and tax rates, approve corrections to locked records, and see every figure the System produces. Those powers carry obligations, and this Agreement sets them out. If you do not accept, you will not be able to proceed.',

    'sections' => [

        [
            'heading' => '1. Definitions',
            'body' => [
                '"System" means the Petrol Integrity System, comprising the mobile application, the web administration panel, the application programming interface, the hosted backend services, and all associated storage and databases.',
                '"Provider" means the party that developed, licenses, hosts or maintains the System on the Customer\'s behalf, together with its personnel, contractors and suppliers.',
                '"Customer" means the organisation on whose behalf you act, being the fuel retail business whose stations, staff, stock and trading records are recorded in the System.',
                '"Administrator" means you, the individual accepting this Agreement, holding an account with the administrator role.',
                '"Records" means all data entered into, generated by, or stored in the System, including shifts, meter readings, dip readings, payments, credit sales, deliveries, evidence photographs, reports and audit entries.',
                '"Evidence" means photographs of pump meters and any associated metadata, including location and time, captured through the System.',
                '"Personal Data" has the meaning given in the Data Protection Act, 2019 (Kenya).',
            ],
        ],

        [
            'heading' => '2. Acceptance and Authority',
            'body' => [
                'By selecting "I Agree" you confirm that you have read, understood and accept this Agreement in its entirety, and that you do so both personally and on behalf of the Customer.',
                'You confirm that you are duly authorised by the Customer to accept these terms, to administer the System on the Customer\'s behalf, and to bind the Customer to the obligations in this Agreement. If you are not so authorised, you must select "I Do Not Agree" and stop.',
                'You confirm that you are at least eighteen years of age and legally capable of entering into a binding agreement.',
                'Your acceptance is recorded with your account identity, the date and time, the version of this Agreement, and the network address and device from which you accepted. That record is retained as evidence of acceptance and may be produced in any dispute.',
                'Acceptance is required once per Administrator for each version of this Agreement. If the terms are materially revised, you will be asked to accept the revised version before continuing to use the System.',
            ],
        ],

        [
            'heading' => '3. Nature and Purpose of the System',
            'body' => [
                'The System is a record-keeping and reconciliation tool. It records what its users enter, performs arithmetic on those entries, and reports the results. It does not measure fuel, weigh cash, observe staff, or independently verify anything.',
                'THE SYSTEM IS NOT AN ACCOUNTING SYSTEM, A TAX RETURN, A STATUTORY RECORD, AN AUDIT, OR ANY FORM OF PROFESSIONAL ADVICE. Its outputs are management information only.',
                'Figures produced by the System — including expected cash, cash variance, stock variance, value added tax collected and paid, profit, loss and margin — are derived entirely from data entered by users and from configuration set by Administrators. They are only as accurate as those inputs.',
                'In particular, the profit and loss figure compares sales in a period against the cost of all fuel purchased in that period, not the cost of the fuel actually sold. It is therefore distorted by the timing of deliveries and must not be relied upon as a measure of profitability for any single period. You acknowledge that this has been disclosed to you.',
                'The Customer remains solely responsible for its own books of account, its statutory and tax filings, its regulatory compliance, and any professional advice it requires. Nothing produced by the System discharges any of those obligations.',
            ],
        ],

        [
            'heading' => '4. Integrity Controls Are Controls, Not Guarantees',
            'body' => [
                'The System includes features intended to make certain errors and manipulations harder or more visible. These include requiring each shift to open on the meter reading the previous shift closed with; attaching a photograph to a meter reading; rejecting a photograph already used on another shift; refusing to close a shift whose photograph could not be stored; preventing deletion of a closed shift; and recording an audit trail of changes.',
                'THESE ARE DETERRENTS AND DETECTION AIDS. THEY ARE NOT A GUARANTEE AGAINST THEFT, FRAUD, COLLUSION, NEGLIGENCE OR ERROR. A determined person with physical access to equipment, cash or the tank can defeat them.',
                'The System cannot detect a discrepancy that its inputs do not reveal. Where a tank has no calibration chart, no stock variance is reported at all; where a meter reading is entered incorrectly and consistently, the resulting figures will be consistently wrong.',
                'You accept that supervision, segregation of duties, physical security and independent verification remain the Customer\'s responsibility, and that the System supplements but does not replace them.',
            ],
        ],

        [
            'heading' => '5. Administrator Obligations',
            'body' => [
                'You must configure the System accurately. This includes, without limitation: the selling price and value added tax rate of each product; the capacity and calibration chart of each tank; the digit count and current reading of each pump nozzle; and the station to which each member of staff is assigned.',
                'You acknowledge specifically that the value added tax rate must be entered as the percentage it is expressed as, and that an incorrect rate will understate or overstate tax on every transaction recorded while it is in force.',
                'You acknowledge specifically that a pump nozzle\'s recorded meter reading is the figure from which litres sold is calculated, and that an inaccurate figure will produce inaccurate sales, cash and tax figures for the shift concerned.',
                'You must enter a tank calibration chart taken from that tank\'s calibration certificate and not from estimation. You accept that stock variance is meaningless or absent without it.',
                'You must create a separate account for each individual who uses the System, must not share accounts, and must not permit any person to use another person\'s account. Shift ownership, accountability and the audit trail all depend on this.',
                'You must promptly disable or delete the account of any person who ceases to be authorised.',
                'You must review the Records the System produces, investigate variances, and not treat the absence of a reported variance as assurance that none exists.',
            ],
        ],

        [
            'heading' => '6. Security of Credentials and Devices',
            'body' => [
                'You are responsible for maintaining the confidentiality of your password and of any credential issued to you, and for all activity occurring under your account.',
                'You must not disclose your password to any person, including the Provider. The Provider will never ask for it.',
                'You must notify the Provider and the Customer immediately upon becoming aware of any unauthorised access to, or use of, any account.',
                'You are responsible for the security of the devices from which you access the System, including keeping them locked, patched and free of malicious software. The System cannot protect Records reached from a compromised device.',
                'You acknowledge that the System does not presently offer multi-factor authentication, and that password strength and confidentiality are therefore the principal protection on every account.',
            ],
        ],

        [
            'heading' => '7. Permitted Use and Prohibited Conduct',
            'body' => [
                'You are granted a limited, non-exclusive, non-transferable, revocable right to access and use the System for the Customer\'s internal business purposes only, for the duration of your authorisation.',
                'You must not: use the System for any unlawful purpose; enter data you know or suspect to be false; alter, conceal or destroy any Record in order to misrepresent trading activity; attempt to circumvent any integrity control, authorisation check or audit mechanism; access data belonging to any organisation other than the Customer; attempt to gain access to any account, system or network without authorisation; probe, scan or test the vulnerability of the System; interfere with or disrupt the System\'s operation; copy, modify, decompile, reverse engineer or create derivative works from the System; remove or obscure any proprietary notice; resell, sublicense, rent or otherwise make the System available to any third party; or use the System to develop a competing product.',
                'Any attempt to falsify Records, defeat an integrity control, or misrepresent trading activity is a material breach of this Agreement and may constitute a criminal offence, including offences under the Computer Misuse and Cybercrimes Act, 2018 (Kenya).',
            ],
        ],

        [
            'heading' => '8. Data Protection and Staff Privacy',
            'body' => [
                'The System records Personal Data, including the names, contact details and working activity of the Customer\'s staff, and may record the location and time at which an individual captured Evidence.',
                'As between the parties, the Customer is the data controller in respect of that Personal Data and the Provider acts as a data processor on the Customer\'s instructions.',
                'The Customer, acting through you, is responsible for establishing and documenting a lawful basis for processing that Personal Data; for informing staff of what is recorded about them, why, and for how long; for honouring data subject rights; and for complying in all respects with the Data Protection Act, 2019 and any regulations made under it.',
                'You confirm that staff whose Personal Data is entered into the System have been informed that their work activity, meter readings, photographs and the location and time of capture are recorded, and that records are retained for business, audit and evidential purposes.',
                'You must not enter Personal Data into the System beyond what is necessary for its purpose, and must not enter any special category of Personal Data.',
                'Evidence photographs may incidentally capture individuals. You are responsible for ensuring that capture and retention is lawful and proportionate in the Customer\'s operating context.',
                'You must not download, copy, transmit or retain Records outside the System except as necessary for the Customer\'s legitimate business purposes and in compliance with applicable law.',
            ],
        ],

        [
            'heading' => '9. Hosting, Third Parties and Availability',
            'body' => [
                'The System is hosted on third-party infrastructure and depends on third-party services for computing, database storage, object storage, application distribution and network connectivity. The Provider does not control those services.',
                'THE SYSTEM IS PROVIDED WITHOUT ANY GUARANTEE OF AVAILABILITY, UPTIME, THROUGHPUT OR RESPONSE TIME. No service level is offered or implied.',
                'Access may be interrupted, suspended or terminated without notice by reason of maintenance, defect, third-party failure, network failure, suspension for non-payment, or any circumstance beyond the Provider\'s reasonable control.',
                'You acknowledge that the System requires network connectivity to function and that it cannot record or reconcile anything while a device is offline.',
                'You acknowledge that continued availability depends on the Customer maintaining any subscription, credit or payment arrangement required by the hosting providers, and that failure to do so will cause the System to stop serving, including loss of access to the administration panel and to the Records until the arrangement is restored.',
            ],
        ],

        [
            'heading' => '10. Backups and Data Loss',
            'body' => [
                'The System takes an automated daily snapshot of its database to third-party object storage. That snapshot is a copy of the data as it stood when the snapshot was taken.',
                'BACKUP IS NOT CONTINUOUS. There is no point-in-time recovery. In the event of loss, data entered since the most recent snapshot may be unrecoverable.',
                'The Provider gives no warranty that any backup will be complete, uncorrupted, or capable of successful restoration.',
                'The Customer is responsible for satisfying itself as to the adequacy of backup arrangements for its own purposes, for verifying periodically that restoration is possible, and for retaining such independent records — including paper records — as it considers prudent.',
                'You acknowledge that a closed shift cannot be deleted through the System and that certain figures are fixed at the moment a shift is closed, so that a configuration error discovered afterwards cannot be corrected retrospectively except through the correction workflow.',
            ],
        ],

        [
            'heading' => '11. No Warranty',
            'body' => [
                'THE SYSTEM IS PROVIDED "AS IS" AND "AS AVAILABLE", WITH ALL FAULTS AND WITHOUT WARRANTY OF ANY KIND.',
                'TO THE MAXIMUM EXTENT PERMITTED BY LAW, THE PROVIDER DISCLAIMS ALL WARRANTIES, CONDITIONS, REPRESENTATIONS AND TERMS, WHETHER EXPRESS, IMPLIED, STATUTORY OR OTHERWISE, INCLUDING ANY IMPLIED WARRANTY OF MERCHANTABILITY, SATISFACTORY QUALITY, FITNESS FOR A PARTICULAR PURPOSE, ACCURACY, OR NON-INFRINGEMENT.',
                'THE PROVIDER DOES NOT WARRANT THAT THE SYSTEM WILL BE UNINTERRUPTED, TIMELY, SECURE, ERROR-FREE OR FREE OF HARMFUL COMPONENTS; THAT ANY DEFECT WILL BE CORRECTED; THAT ANY FIGURE, CALCULATION OR REPORT WILL BE ACCURATE OR COMPLETE; OR THAT THE SYSTEM WILL DETECT, PREVENT OR REVEAL ANY THEFT, FRAUD, LOSS, LEAK, SHORTAGE OR ERROR.',
                'No advice or information, whether oral or written, obtained from the Provider creates any warranty not expressly stated in this Agreement.',
            ],
        ],

        [
            'heading' => '12. Limitation of Liability',
            'body' => [
                'TO THE MAXIMUM EXTENT PERMITTED BY LAW, THE PROVIDER SHALL NOT BE LIABLE FOR ANY INDIRECT, INCIDENTAL, SPECIAL, CONSEQUENTIAL, EXEMPLARY OR PUNITIVE LOSS OR DAMAGE, NOR FOR ANY LOSS OF PROFIT, REVENUE, BUSINESS, GOODWILL, ANTICIPATED SAVINGS, OPPORTUNITY, REPUTATION, DATA OR RECORDS, HOWSOEVER ARISING AND WHETHER IN CONTRACT, TORT (INCLUDING NEGLIGENCE), BREACH OF STATUTORY DUTY, MISREPRESENTATION, RESTITUTION OR OTHERWISE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH LOSS.',
                'WITHOUT LIMITING THE GENERALITY OF THE FOREGOING, THE PROVIDER SHALL NOT BE LIABLE FOR: ANY FUEL, CASH, STOCK OR INVENTORY LOSS, SHORTAGE OR SHRINKAGE; ANY THEFT OR FRAUD BY ANY PERSON, WHETHER AN EMPLOYEE OF THE CUSTOMER OR OTHERWISE; ANY TAX, PENALTY, INTEREST, ASSESSMENT OR FINE; ANY REGULATORY SANCTION OR LOSS OF LICENCE; ANY DECISION TAKEN OR NOT TAKEN IN RELIANCE ON ANY FIGURE PRODUCED BY THE SYSTEM; ANY LOSS ARISING FROM INACCURATE, INCOMPLETE OR UNTIMELY DATA ENTRY OR CONFIGURATION; ANY LOSS ARISING FROM UNAVAILABILITY, SUSPENSION OR TERMINATION OF ANY THIRD-PARTY SERVICE; ANY LOSS ARISING FROM THE CUSTOMER\'S FAILURE TO MAINTAIN A REQUIRED SUBSCRIPTION OR PAYMENT ARRANGEMENT; ANY LOSS OR CORRUPTION OF DATA OR EVIDENCE; OR ANY EMPLOYMENT, DISCIPLINARY OR DEFAMATION CLAIM ARISING FROM THE USE OF RECORDS.',
                'THE PROVIDER\'S TOTAL AGGREGATE LIABILITY ARISING OUT OF OR IN CONNECTION WITH THIS AGREEMENT AND THE SYSTEM, WHETHER IN CONTRACT, TORT OR OTHERWISE, SHALL NOT EXCEED THE TOTAL AMOUNT ACTUALLY PAID BY THE CUSTOMER TO THE PROVIDER FOR THE SYSTEM IN THE SIX MONTHS IMMEDIATELY PRECEDING THE EVENT GIVING RISE TO THE CLAIM, OR KENYA SHILLINGS TEN THOUSAND (KES 10,000), WHICHEVER IS THE LESSER.',
                'Nothing in this Agreement excludes or limits liability for death or personal injury caused by negligence, for fraud or fraudulent misrepresentation, or for any liability that cannot lawfully be excluded or limited.',
                'You acknowledge that the allocation of risk in this clause is a fundamental basis on which the System is made available, that it is reasonable given the nature and price of the System, and that the System would not be made available on any other basis.',
            ],
        ],

        [
            'heading' => '13. Indemnity',
            'body' => [
                'You and the Customer jointly and severally agree to indemnify, defend and hold harmless the Provider and its personnel, contractors and suppliers against all claims, demands, proceedings, liabilities, losses, damages, fines, penalties, costs and expenses (including reasonable legal fees) arising out of or in connection with: any breach of this Agreement by you or the Customer; any inaccurate, incomplete or unlawful data entered into the System; any use of the System by any person using your account; any claim by any employee, contractor, customer, supplier or regulator of the Customer relating to the Records or to their use; any breach of the Data Protection Act, 2019 or of any other law in connection with Personal Data in the System; and any decision taken by the Customer in reliance on any output of the System.',
            ],
        ],

        [
            'heading' => '14. Intellectual Property',
            'body' => [
                'All intellectual property rights in and to the System, including its software, source code, design, structure, interfaces, documentation, names and marks, are and remain the exclusive property of the Provider or its licensors.',
                'Nothing in this Agreement transfers any such right to you or to the Customer. You are granted only the limited right of access set out in clause 7.',
                'The Records themselves, being the Customer\'s trading data, remain the property of the Customer. The Provider may process them only as necessary to provide, maintain, secure and support the System, and may use aggregated and anonymised data that does not identify the Customer or any individual for the purpose of improving the System.',
            ],
        ],

        [
            'heading' => '15. Confidentiality',
            'body' => [
                'You must treat as confidential all non-public information about the System and about the Provider to which you gain access, and all Records to which your role gives you access, and must not disclose them except as necessary for the Customer\'s legitimate business purposes or as required by law.',
                'This obligation survives the termination of your authorisation and of this Agreement.',
            ],
        ],

        [
            'heading' => '16. Suspension and Termination',
            'body' => [
                'The Provider or the Customer may suspend or terminate your access at any time, with or without notice, including where this Agreement is breached, where your authorisation ends, where your conduct threatens the integrity or security of the System, or where any required payment is not made.',
                'The Provider may suspend or terminate the System or any organisation\'s access to it where fees or hosting charges are unpaid.',
                'On termination, your right to access the System ceases immediately. Records remain the Customer\'s property and, subject to payment of any sums outstanding and to the Provider\'s ability to do so, will be made available for export for a reasonable period. The Provider is not obliged to retain Records indefinitely following termination.',
                'Clauses relating to definitions, nature of the System, no warranty, limitation of liability, indemnity, intellectual property, confidentiality, governing law and dispute resolution survive termination.',
            ],
        ],

        [
            'heading' => '17. Changes to the System and to this Agreement',
            'body' => [
                'The Provider may modify, add to, or discontinue any part or feature of the System at any time, including any calculation, report or integrity control, without liability.',
                'This Agreement may be revised. Where a revision is material, you will be presented with the revised version and asked to accept it before continuing to use the System. Continued use after acceptance constitutes agreement to the revised terms.',
                'Acceptances of earlier versions remain on record against the version accepted.',
            ],
        ],

        [
            'heading' => '18. Force Majeure',
            'body' => [
                'The Provider is not liable for any failure or delay in performance caused by any circumstance beyond its reasonable control, including act of God, flood, fire, earthquake, epidemic, war, civil unrest, terrorism, industrial action, governmental or regulatory action, failure of power, telecommunications or internet service, failure or suspension of any third-party hosting or storage provider, or cyber attack.',
            ],
        ],

        [
            'heading' => '19. Governing Law and Dispute Resolution',
            'body' => [
                'This Agreement is governed by and construed in accordance with the laws of the Republic of Kenya.',
                'The parties shall first attempt to resolve any dispute by good faith negotiation. Failing resolution within thirty (30) days, the dispute shall be referred to mediation by a single mediator agreed between the parties or, absent agreement, appointed by the Chartered Institute of Arbitrators (Kenya Branch).',
                'Failing resolution by mediation, the dispute shall be referred to and finally resolved by arbitration by a single arbitrator appointed in the same manner, seated in Nairobi and conducted in English, under the Arbitration Act, 1995.',
                'Nothing in this clause prevents either party from seeking urgent injunctive or interim relief from the courts of Kenya, to whose non-exclusive jurisdiction the parties submit.',
            ],
        ],

        [
            'heading' => '20. General',
            'body' => [
                'Entire agreement: this Agreement constitutes the entire agreement between the parties as to the subject matter and supersedes all prior discussions, representations and understandings, save that nothing limits liability for fraud.',
                'Severability: if any provision is held invalid or unenforceable, it shall be modified to the minimum extent necessary or severed, and the remainder shall continue in full force.',
                'No waiver: failure or delay in enforcing any provision is not a waiver of it.',
                'Assignment: you may not assign or transfer any right under this Agreement. The Provider may assign this Agreement in connection with a transfer of its business or assets.',
                'No partnership: nothing creates any partnership, joint venture, agency or employment relationship between the parties.',
                'Notices: notices may be given to you at the email address on your account and are deemed received on the day of sending.',
                'Language: this Agreement is made in English, which governs its interpretation.',
                'Electronic acceptance: you agree that your electronic acceptance has the same legal effect as a handwritten signature, in accordance with the Kenya Information and Communications Act and the Business Laws (Amendment) Act, 2020.',
            ],
        ],

        [
            'heading' => '21. Acknowledgement',
            'body' => [
                'By selecting "I Agree" you acknowledge that: you have read and understood this Agreement in full; you have had the opportunity to take independent legal advice; you accept it personally and on behalf of the Customer with authority to do so; you understand that the System is a record-keeping aid whose outputs depend entirely on the data entered into it; you understand that its integrity features are controls and not guarantees; you understand that the Provider\'s liability is limited as set out in clause 12; and you understand that your acceptance is recorded with your identity, the time, and the device and network address used.',
                'If you do not accept any part of this Agreement, select "I Do Not Agree". You will be signed out and will not be able to use the System.',
            ],
        ],

    ],

];
