/**
 * Generated by orval v8.0.3 🍺
 * Do not edit manually.
 * Petrol Integrity System API Documentation
 * OpenAPI spec version: 0.0.1
 */
import {
  useMutation,
  useQuery
} from '@tanstack/react-query';
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  MutationFunction,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult
} from '@tanstack/react-query';

import type {
  AuthenticationExceptionResponse,
  AuthorizationExceptionResponse,
  ModelNotFoundExceptionResponse,
  NozzlesDestroy200,
  NozzlesIndex200,
  NozzlesShow200,
  NozzlesStore200,
  NozzlesUpdate200,
  StoreNozzleRequest,
  UpdateNozzleRequest,
  ValidationExceptionResponse
} from '.././model';

import { customInstance } from '../../../lib/axios';


type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];



/**
 * @summary List Nozzles
Filterable by Station ID (for Manager/Admin views)
 */
export type nozzlesIndexResponse200 = {
  data: NozzlesIndex200
  status: 200
}

export type nozzlesIndexResponse401 = {
  data: AuthenticationExceptionResponse
  status: 401
}

export type nozzlesIndexResponse403 = {
  data: AuthorizationExceptionResponse
  status: 403
}
    
export type nozzlesIndexResponseSuccess = (nozzlesIndexResponse200) & {
  headers: Headers;
};
export type nozzlesIndexResponseError = (nozzlesIndexResponse401 | nozzlesIndexResponse403) & {
  headers: Headers;
};

export type nozzlesIndexResponse = (nozzlesIndexResponseSuccess | nozzlesIndexResponseError)

export const getNozzlesIndexUrl = () => {


  

  return `/v1/nozzles`
}

export const nozzlesIndex = async ( options?: RequestInit): Promise<nozzlesIndexResponse> => {
  
  return customInstance<nozzlesIndexResponse>(getNozzlesIndexUrl(),
  {      
    ...options,
    method: 'GET'
    
    
  }
);}





export const getNozzlesIndexQueryKey = () => {
    return [
    `/v1/nozzles`
    ] as const;
    }

    
export const getNozzlesIndexQueryOptions = <TData = Awaited<ReturnType<typeof nozzlesIndex>>, TError = AuthenticationExceptionResponse | AuthorizationExceptionResponse>( options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof nozzlesIndex>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getNozzlesIndexQueryKey();

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof nozzlesIndex>>> = ({ signal }) => nozzlesIndex({ signal, ...requestOptions });

      

      

   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof nozzlesIndex>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type NozzlesIndexQueryResult = NonNullable<Awaited<ReturnType<typeof nozzlesIndex>>>
export type NozzlesIndexQueryError = AuthenticationExceptionResponse | AuthorizationExceptionResponse


export function useNozzlesIndex<TData = Awaited<ReturnType<typeof nozzlesIndex>>, TError = AuthenticationExceptionResponse | AuthorizationExceptionResponse>(
  options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof nozzlesIndex>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof nozzlesIndex>>,
          TError,
          Awaited<ReturnType<typeof nozzlesIndex>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useNozzlesIndex<TData = Awaited<ReturnType<typeof nozzlesIndex>>, TError = AuthenticationExceptionResponse | AuthorizationExceptionResponse>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof nozzlesIndex>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof nozzlesIndex>>,
          TError,
          Awaited<ReturnType<typeof nozzlesIndex>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useNozzlesIndex<TData = Awaited<ReturnType<typeof nozzlesIndex>>, TError = AuthenticationExceptionResponse | AuthorizationExceptionResponse>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof nozzlesIndex>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary List Nozzles
Filterable by Station ID (for Manager/Admin views)
 */

export function useNozzlesIndex<TData = Awaited<ReturnType<typeof nozzlesIndex>>, TError = AuthenticationExceptionResponse | AuthorizationExceptionResponse>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof nozzlesIndex>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getNozzlesIndexQueryOptions(options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}




/**
 * @summary Create a new Nozzle
 */
export type nozzlesStoreResponse200 = {
  data: NozzlesStore200
  status: 200
}

export type nozzlesStoreResponse401 = {
  data: AuthenticationExceptionResponse
  status: 401
}

export type nozzlesStoreResponse403 = {
  data: AuthorizationExceptionResponse
  status: 403
}

export type nozzlesStoreResponse422 = {
  data: ValidationExceptionResponse
  status: 422
}
    
export type nozzlesStoreResponseSuccess = (nozzlesStoreResponse200) & {
  headers: Headers;
};
export type nozzlesStoreResponseError = (nozzlesStoreResponse401 | nozzlesStoreResponse403 | nozzlesStoreResponse422) & {
  headers: Headers;
};

export type nozzlesStoreResponse = (nozzlesStoreResponseSuccess | nozzlesStoreResponseError)

export const getNozzlesStoreUrl = () => {


  

  return `/v1/nozzles`
}

export const nozzlesStore = async (storeNozzleRequest: StoreNozzleRequest, options?: RequestInit): Promise<nozzlesStoreResponse> => {
  
  return customInstance<nozzlesStoreResponse>(getNozzlesStoreUrl(),
  {      
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(
      storeNozzleRequest,)
  }
);}




export const getNozzlesStoreMutationOptions = <TError = AuthenticationExceptionResponse | AuthorizationExceptionResponse | ValidationExceptionResponse,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof nozzlesStore>>, TError,{data: StoreNozzleRequest}, TContext>, request?: SecondParameter<typeof customInstance>}
): UseMutationOptions<Awaited<ReturnType<typeof nozzlesStore>>, TError,{data: StoreNozzleRequest}, TContext> => {

const mutationKey = ['nozzlesStore'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof nozzlesStore>>, {data: StoreNozzleRequest}> = (props) => {
          const {data} = props ?? {};

          return  nozzlesStore(data,requestOptions)
        }



        


  return  { mutationFn, ...mutationOptions }}

    export type NozzlesStoreMutationResult = NonNullable<Awaited<ReturnType<typeof nozzlesStore>>>
    export type NozzlesStoreMutationBody = StoreNozzleRequest
    export type NozzlesStoreMutationError = AuthenticationExceptionResponse | AuthorizationExceptionResponse | ValidationExceptionResponse

    /**
 * @summary Create a new Nozzle
 */
export const useNozzlesStore = <TError = AuthenticationExceptionResponse | AuthorizationExceptionResponse | ValidationExceptionResponse,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof nozzlesStore>>, TError,{data: StoreNozzleRequest}, TContext>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof nozzlesStore>>,
        TError,
        {data: StoreNozzleRequest},
        TContext
      > => {
      return useMutation(getNozzlesStoreMutationOptions(options), queryClient);
    }
    /**
 * @summary Show a specific Nozzle
 */
export type nozzlesShowResponse200 = {
  data: NozzlesShow200
  status: 200
}

export type nozzlesShowResponse401 = {
  data: AuthenticationExceptionResponse
  status: 401
}

export type nozzlesShowResponse403 = {
  data: AuthorizationExceptionResponse
  status: 403
}

export type nozzlesShowResponse404 = {
  data: ModelNotFoundExceptionResponse
  status: 404
}
    
export type nozzlesShowResponseSuccess = (nozzlesShowResponse200) & {
  headers: Headers;
};
export type nozzlesShowResponseError = (nozzlesShowResponse401 | nozzlesShowResponse403 | nozzlesShowResponse404) & {
  headers: Headers;
};

export type nozzlesShowResponse = (nozzlesShowResponseSuccess | nozzlesShowResponseError)

export const getNozzlesShowUrl = (nozzle: string,) => {


  

  return `/v1/nozzles/${nozzle}`
}

export const nozzlesShow = async (nozzle: string, options?: RequestInit): Promise<nozzlesShowResponse> => {
  
  return customInstance<nozzlesShowResponse>(getNozzlesShowUrl(nozzle),
  {      
    ...options,
    method: 'GET'
    
    
  }
);}





export const getNozzlesShowQueryKey = (nozzle: string,) => {
    return [
    `/v1/nozzles/${nozzle}`
    ] as const;
    }

    
export const getNozzlesShowQueryOptions = <TData = Awaited<ReturnType<typeof nozzlesShow>>, TError = AuthenticationExceptionResponse | AuthorizationExceptionResponse | ModelNotFoundExceptionResponse>(nozzle: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof nozzlesShow>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getNozzlesShowQueryKey(nozzle);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof nozzlesShow>>> = ({ signal }) => nozzlesShow(nozzle, { signal, ...requestOptions });

      

      

   return  { queryKey, queryFn, enabled: !!(nozzle), ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof nozzlesShow>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type NozzlesShowQueryResult = NonNullable<Awaited<ReturnType<typeof nozzlesShow>>>
export type NozzlesShowQueryError = AuthenticationExceptionResponse | AuthorizationExceptionResponse | ModelNotFoundExceptionResponse


export function useNozzlesShow<TData = Awaited<ReturnType<typeof nozzlesShow>>, TError = AuthenticationExceptionResponse | AuthorizationExceptionResponse | ModelNotFoundExceptionResponse>(
 nozzle: string, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof nozzlesShow>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof nozzlesShow>>,
          TError,
          Awaited<ReturnType<typeof nozzlesShow>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useNozzlesShow<TData = Awaited<ReturnType<typeof nozzlesShow>>, TError = AuthenticationExceptionResponse | AuthorizationExceptionResponse | ModelNotFoundExceptionResponse>(
 nozzle: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof nozzlesShow>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof nozzlesShow>>,
          TError,
          Awaited<ReturnType<typeof nozzlesShow>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useNozzlesShow<TData = Awaited<ReturnType<typeof nozzlesShow>>, TError = AuthenticationExceptionResponse | AuthorizationExceptionResponse | ModelNotFoundExceptionResponse>(
 nozzle: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof nozzlesShow>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Show a specific Nozzle
 */

export function useNozzlesShow<TData = Awaited<ReturnType<typeof nozzlesShow>>, TError = AuthenticationExceptionResponse | AuthorizationExceptionResponse | ModelNotFoundExceptionResponse>(
 nozzle: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof nozzlesShow>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getNozzlesShowQueryOptions(nozzle,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}




/**
 * @summary Update Nozzle details
 */
export type nozzlesUpdateResponse200 = {
  data: NozzlesUpdate200
  status: 200
}

export type nozzlesUpdateResponse401 = {
  data: AuthenticationExceptionResponse
  status: 401
}

export type nozzlesUpdateResponse403 = {
  data: AuthorizationExceptionResponse
  status: 403
}

export type nozzlesUpdateResponse404 = {
  data: ModelNotFoundExceptionResponse
  status: 404
}

export type nozzlesUpdateResponse422 = {
  data: ValidationExceptionResponse
  status: 422
}
    
export type nozzlesUpdateResponseSuccess = (nozzlesUpdateResponse200) & {
  headers: Headers;
};
export type nozzlesUpdateResponseError = (nozzlesUpdateResponse401 | nozzlesUpdateResponse403 | nozzlesUpdateResponse404 | nozzlesUpdateResponse422) & {
  headers: Headers;
};

export type nozzlesUpdateResponse = (nozzlesUpdateResponseSuccess | nozzlesUpdateResponseError)

export const getNozzlesUpdateUrl = (nozzle: string,) => {


  

  return `/v1/nozzles/${nozzle}`
}

export const nozzlesUpdate = async (nozzle: string,
    updateNozzleRequest: UpdateNozzleRequest, options?: RequestInit): Promise<nozzlesUpdateResponse> => {
  
  return customInstance<nozzlesUpdateResponse>(getNozzlesUpdateUrl(nozzle),
  {      
    ...options,
    method: 'PUT',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(
      updateNozzleRequest,)
  }
);}




export const getNozzlesUpdateMutationOptions = <TError = AuthenticationExceptionResponse | AuthorizationExceptionResponse | ModelNotFoundExceptionResponse | ValidationExceptionResponse,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof nozzlesUpdate>>, TError,{nozzle: string;data: UpdateNozzleRequest}, TContext>, request?: SecondParameter<typeof customInstance>}
): UseMutationOptions<Awaited<ReturnType<typeof nozzlesUpdate>>, TError,{nozzle: string;data: UpdateNozzleRequest}, TContext> => {

const mutationKey = ['nozzlesUpdate'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof nozzlesUpdate>>, {nozzle: string;data: UpdateNozzleRequest}> = (props) => {
          const {nozzle,data} = props ?? {};

          return  nozzlesUpdate(nozzle,data,requestOptions)
        }



        


  return  { mutationFn, ...mutationOptions }}

    export type NozzlesUpdateMutationResult = NonNullable<Awaited<ReturnType<typeof nozzlesUpdate>>>
    export type NozzlesUpdateMutationBody = UpdateNozzleRequest
    export type NozzlesUpdateMutationError = AuthenticationExceptionResponse | AuthorizationExceptionResponse | ModelNotFoundExceptionResponse | ValidationExceptionResponse

    /**
 * @summary Update Nozzle details
 */
export const useNozzlesUpdate = <TError = AuthenticationExceptionResponse | AuthorizationExceptionResponse | ModelNotFoundExceptionResponse | ValidationExceptionResponse,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof nozzlesUpdate>>, TError,{nozzle: string;data: UpdateNozzleRequest}, TContext>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof nozzlesUpdate>>,
        TError,
        {nozzle: string;data: UpdateNozzleRequest},
        TContext
      > => {
      return useMutation(getNozzlesUpdateMutationOptions(options), queryClient);
    }
    /**
 * @summary Delete a Nozzle
 */
export type nozzlesDestroyResponse200 = {
  data: NozzlesDestroy200
  status: 200
}

export type nozzlesDestroyResponse401 = {
  data: AuthenticationExceptionResponse
  status: 401
}

export type nozzlesDestroyResponse403 = {
  data: AuthorizationExceptionResponse
  status: 403
}

export type nozzlesDestroyResponse404 = {
  data: ModelNotFoundExceptionResponse
  status: 404
}
    
export type nozzlesDestroyResponseSuccess = (nozzlesDestroyResponse200) & {
  headers: Headers;
};
export type nozzlesDestroyResponseError = (nozzlesDestroyResponse401 | nozzlesDestroyResponse403 | nozzlesDestroyResponse404) & {
  headers: Headers;
};

export type nozzlesDestroyResponse = (nozzlesDestroyResponseSuccess | nozzlesDestroyResponseError)

export const getNozzlesDestroyUrl = (nozzle: string,) => {


  

  return `/v1/nozzles/${nozzle}`
}

export const nozzlesDestroy = async (nozzle: string, options?: RequestInit): Promise<nozzlesDestroyResponse> => {
  
  return customInstance<nozzlesDestroyResponse>(getNozzlesDestroyUrl(nozzle),
  {      
    ...options,
    method: 'DELETE'
    
    
  }
);}




export const getNozzlesDestroyMutationOptions = <TError = AuthenticationExceptionResponse | AuthorizationExceptionResponse | ModelNotFoundExceptionResponse,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof nozzlesDestroy>>, TError,{nozzle: string}, TContext>, request?: SecondParameter<typeof customInstance>}
): UseMutationOptions<Awaited<ReturnType<typeof nozzlesDestroy>>, TError,{nozzle: string}, TContext> => {

const mutationKey = ['nozzlesDestroy'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof nozzlesDestroy>>, {nozzle: string}> = (props) => {
          const {nozzle} = props ?? {};

          return  nozzlesDestroy(nozzle,requestOptions)
        }



        


  return  { mutationFn, ...mutationOptions }}

    export type NozzlesDestroyMutationResult = NonNullable<Awaited<ReturnType<typeof nozzlesDestroy>>>
    
    export type NozzlesDestroyMutationError = AuthenticationExceptionResponse | AuthorizationExceptionResponse | ModelNotFoundExceptionResponse

    /**
 * @summary Delete a Nozzle
 */
export const useNozzlesDestroy = <TError = AuthenticationExceptionResponse | AuthorizationExceptionResponse | ModelNotFoundExceptionResponse,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof nozzlesDestroy>>, TError,{nozzle: string}, TContext>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof nozzlesDestroy>>,
        TError,
        {nozzle: string},
        TContext
      > => {
      return useMutation(getNozzlesDestroyMutationOptions(options), queryClient);
    }
    