/**
 * Generated by orval v8.0.3 🍺
 * Do not edit manually.
 * Petrol Integrity System API Documentation
 * OpenAPI spec version: 0.0.1
 */
import {
  useMutation,
  useQuery
} from '@tanstack/react-query';
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  MutationFunction,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult
} from '@tanstack/react-query';

import type {
  AuthenticationExceptionResponse,
  GetV1User200,
  PostLogin200,
  PostLogin401,
  PostLoginBody,
  ValidationExceptionResponse
} from '.././model';

import { customInstance } from '../../../lib/axios';


type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];



export type postLoginResponse200 = {
  data: PostLogin200
  status: 200
}

export type postLoginResponse401 = {
  data: PostLogin401
  status: 401
}

export type postLoginResponse422 = {
  data: ValidationExceptionResponse
  status: 422
}
    
export type postLoginResponseSuccess = (postLoginResponse200) & {
  headers: Headers;
};
export type postLoginResponseError = (postLoginResponse401 | postLoginResponse422) & {
  headers: Headers;
};

export type postLoginResponse = (postLoginResponseSuccess | postLoginResponseError)

export const getPostLoginUrl = () => {


  

  return `/login`
}

export const postLogin = async (postLoginBody: PostLoginBody, options?: RequestInit): Promise<postLoginResponse> => {
  
  return customInstance<postLoginResponse>(getPostLoginUrl(),
  {      
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(
      postLoginBody,)
  }
);}




export const getPostLoginMutationOptions = <TError = PostLogin401 | ValidationExceptionResponse,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postLogin>>, TError,{data: PostLoginBody}, TContext>, request?: SecondParameter<typeof customInstance>}
): UseMutationOptions<Awaited<ReturnType<typeof postLogin>>, TError,{data: PostLoginBody}, TContext> => {

const mutationKey = ['postLogin'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof postLogin>>, {data: PostLoginBody}> = (props) => {
          const {data} = props ?? {};

          return  postLogin(data,requestOptions)
        }



        


  return  { mutationFn, ...mutationOptions }}

    export type PostLoginMutationResult = NonNullable<Awaited<ReturnType<typeof postLogin>>>
    export type PostLoginMutationBody = PostLoginBody
    export type PostLoginMutationError = PostLogin401 | ValidationExceptionResponse

    export const usePostLogin = <TError = PostLogin401 | ValidationExceptionResponse,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postLogin>>, TError,{data: PostLoginBody}, TContext>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof postLogin>>,
        TError,
        {data: PostLoginBody},
        TContext
      > => {
      return useMutation(getPostLoginMutationOptions(options), queryClient);
    }
    export type getV1UserResponse200 = {
  data: GetV1User200
  status: 200
}

export type getV1UserResponse401 = {
  data: AuthenticationExceptionResponse
  status: 401
}
    
export type getV1UserResponseSuccess = (getV1UserResponse200) & {
  headers: Headers;
};
export type getV1UserResponseError = (getV1UserResponse401) & {
  headers: Headers;
};

export type getV1UserResponse = (getV1UserResponseSuccess | getV1UserResponseError)

export const getGetV1UserUrl = () => {


  

  return `/v1/user`
}

export const getV1User = async ( options?: RequestInit): Promise<getV1UserResponse> => {
  
  return customInstance<getV1UserResponse>(getGetV1UserUrl(),
  {      
    ...options,
    method: 'GET'
    
    
  }
);}





export const getGetV1UserQueryKey = () => {
    return [
    `/v1/user`
    ] as const;
    }

    
export const getGetV1UserQueryOptions = <TData = Awaited<ReturnType<typeof getV1User>>, TError = AuthenticationExceptionResponse>( options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getV1User>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetV1UserQueryKey();

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof getV1User>>> = ({ signal }) => getV1User({ signal, ...requestOptions });

      

      

   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getV1User>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetV1UserQueryResult = NonNullable<Awaited<ReturnType<typeof getV1User>>>
export type GetV1UserQueryError = AuthenticationExceptionResponse


export function useGetV1User<TData = Awaited<ReturnType<typeof getV1User>>, TError = AuthenticationExceptionResponse>(
  options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getV1User>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getV1User>>,
          TError,
          Awaited<ReturnType<typeof getV1User>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetV1User<TData = Awaited<ReturnType<typeof getV1User>>, TError = AuthenticationExceptionResponse>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getV1User>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getV1User>>,
          TError,
          Awaited<ReturnType<typeof getV1User>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetV1User<TData = Awaited<ReturnType<typeof getV1User>>, TError = AuthenticationExceptionResponse>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getV1User>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }

export function useGetV1User<TData = Awaited<ReturnType<typeof getV1User>>, TError = AuthenticationExceptionResponse>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getV1User>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetV1UserQueryOptions(options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}




