/**
 * Generated by orval v8.0.3 🍺
 * Do not edit manually.
 * Petrol Integrity System API Documentation
 * OpenAPI spec version: 0.0.1
 */
import {
  useMutation,
  useQuery
} from '@tanstack/react-query';
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  MutationFunction,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult
} from '@tanstack/react-query';

import type {
  AuthenticationExceptionResponse,
  AuthorizationExceptionResponse,
  ModelNotFoundExceptionResponse,
  UsersIndex200,
  UsersShow200,
  UsersStore200,
  ValidationExceptionResponse
} from '.././model';

import { customInstance } from '../../../lib/axios';


type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];



export type usersIndexResponse200 = {
  data: UsersIndex200
  status: 200
}

export type usersIndexResponse401 = {
  data: AuthenticationExceptionResponse
  status: 401
}

export type usersIndexResponse403 = {
  data: AuthorizationExceptionResponse
  status: 403
}
    
export type usersIndexResponseSuccess = (usersIndexResponse200) & {
  headers: Headers;
};
export type usersIndexResponseError = (usersIndexResponse401 | usersIndexResponse403) & {
  headers: Headers;
};

export type usersIndexResponse = (usersIndexResponseSuccess | usersIndexResponseError)

export const getUsersIndexUrl = () => {


  

  return `/v1/users`
}

export const usersIndex = async ( options?: RequestInit): Promise<usersIndexResponse> => {
  
  return customInstance<usersIndexResponse>(getUsersIndexUrl(),
  {      
    ...options,
    method: 'GET'
    
    
  }
);}





export const getUsersIndexQueryKey = () => {
    return [
    `/v1/users`
    ] as const;
    }

    
export const getUsersIndexQueryOptions = <TData = Awaited<ReturnType<typeof usersIndex>>, TError = AuthenticationExceptionResponse | AuthorizationExceptionResponse>( options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof usersIndex>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getUsersIndexQueryKey();

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof usersIndex>>> = ({ signal }) => usersIndex({ signal, ...requestOptions });

      

      

   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof usersIndex>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type UsersIndexQueryResult = NonNullable<Awaited<ReturnType<typeof usersIndex>>>
export type UsersIndexQueryError = AuthenticationExceptionResponse | AuthorizationExceptionResponse


export function useUsersIndex<TData = Awaited<ReturnType<typeof usersIndex>>, TError = AuthenticationExceptionResponse | AuthorizationExceptionResponse>(
  options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof usersIndex>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof usersIndex>>,
          TError,
          Awaited<ReturnType<typeof usersIndex>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useUsersIndex<TData = Awaited<ReturnType<typeof usersIndex>>, TError = AuthenticationExceptionResponse | AuthorizationExceptionResponse>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof usersIndex>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof usersIndex>>,
          TError,
          Awaited<ReturnType<typeof usersIndex>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useUsersIndex<TData = Awaited<ReturnType<typeof usersIndex>>, TError = AuthenticationExceptionResponse | AuthorizationExceptionResponse>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof usersIndex>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }

export function useUsersIndex<TData = Awaited<ReturnType<typeof usersIndex>>, TError = AuthenticationExceptionResponse | AuthorizationExceptionResponse>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof usersIndex>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getUsersIndexQueryOptions(options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}




export type usersStoreResponse200 = {
  data: UsersStore200
  status: 200
}

export type usersStoreResponse401 = {
  data: AuthenticationExceptionResponse
  status: 401
}

export type usersStoreResponse403 = {
  data: AuthorizationExceptionResponse
  status: 403
}

export type usersStoreResponse422 = {
  data: ValidationExceptionResponse
  status: 422
}
    
export type usersStoreResponseSuccess = (usersStoreResponse200) & {
  headers: Headers;
};
export type usersStoreResponseError = (usersStoreResponse401 | usersStoreResponse403 | usersStoreResponse422) & {
  headers: Headers;
};

export type usersStoreResponse = (usersStoreResponseSuccess | usersStoreResponseError)

export const getUsersStoreUrl = () => {


  

  return `/v1/users`
}

export const usersStore = async ( options?: RequestInit): Promise<usersStoreResponse> => {
  
  return customInstance<usersStoreResponse>(getUsersStoreUrl(),
  {      
    ...options,
    method: 'POST'
    
    
  }
);}




export const getUsersStoreMutationOptions = <TError = AuthenticationExceptionResponse | AuthorizationExceptionResponse | ValidationExceptionResponse,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof usersStore>>, TError,void, TContext>, request?: SecondParameter<typeof customInstance>}
): UseMutationOptions<Awaited<ReturnType<typeof usersStore>>, TError,void, TContext> => {

const mutationKey = ['usersStore'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof usersStore>>, void> = () => {
          

          return  usersStore(requestOptions)
        }



        


  return  { mutationFn, ...mutationOptions }}

    export type UsersStoreMutationResult = NonNullable<Awaited<ReturnType<typeof usersStore>>>
    
    export type UsersStoreMutationError = AuthenticationExceptionResponse | AuthorizationExceptionResponse | ValidationExceptionResponse

    export const useUsersStore = <TError = AuthenticationExceptionResponse | AuthorizationExceptionResponse | ValidationExceptionResponse,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof usersStore>>, TError,void, TContext>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof usersStore>>,
        TError,
        void,
        TContext
      > => {
      return useMutation(getUsersStoreMutationOptions(options), queryClient);
    }
    export type usersShowResponse200 = {
  data: UsersShow200
  status: 200
}

export type usersShowResponse401 = {
  data: AuthenticationExceptionResponse
  status: 401
}

export type usersShowResponse403 = {
  data: AuthorizationExceptionResponse
  status: 403
}

export type usersShowResponse404 = {
  data: ModelNotFoundExceptionResponse
  status: 404
}
    
export type usersShowResponseSuccess = (usersShowResponse200) & {
  headers: Headers;
};
export type usersShowResponseError = (usersShowResponse401 | usersShowResponse403 | usersShowResponse404) & {
  headers: Headers;
};

export type usersShowResponse = (usersShowResponseSuccess | usersShowResponseError)

export const getUsersShowUrl = (user: string,) => {


  

  return `/v1/users/${user}`
}

export const usersShow = async (user: string, options?: RequestInit): Promise<usersShowResponse> => {
  
  return customInstance<usersShowResponse>(getUsersShowUrl(user),
  {      
    ...options,
    method: 'GET'
    
    
  }
);}





export const getUsersShowQueryKey = (user: string,) => {
    return [
    `/v1/users/${user}`
    ] as const;
    }

    
export const getUsersShowQueryOptions = <TData = Awaited<ReturnType<typeof usersShow>>, TError = AuthenticationExceptionResponse | AuthorizationExceptionResponse | ModelNotFoundExceptionResponse>(user: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof usersShow>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getUsersShowQueryKey(user);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof usersShow>>> = ({ signal }) => usersShow(user, { signal, ...requestOptions });

      

      

   return  { queryKey, queryFn, enabled: !!(user), ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof usersShow>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type UsersShowQueryResult = NonNullable<Awaited<ReturnType<typeof usersShow>>>
export type UsersShowQueryError = AuthenticationExceptionResponse | AuthorizationExceptionResponse | ModelNotFoundExceptionResponse


export function useUsersShow<TData = Awaited<ReturnType<typeof usersShow>>, TError = AuthenticationExceptionResponse | AuthorizationExceptionResponse | ModelNotFoundExceptionResponse>(
 user: string, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof usersShow>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof usersShow>>,
          TError,
          Awaited<ReturnType<typeof usersShow>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useUsersShow<TData = Awaited<ReturnType<typeof usersShow>>, TError = AuthenticationExceptionResponse | AuthorizationExceptionResponse | ModelNotFoundExceptionResponse>(
 user: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof usersShow>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof usersShow>>,
          TError,
          Awaited<ReturnType<typeof usersShow>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useUsersShow<TData = Awaited<ReturnType<typeof usersShow>>, TError = AuthenticationExceptionResponse | AuthorizationExceptionResponse | ModelNotFoundExceptionResponse>(
 user: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof usersShow>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }

export function useUsersShow<TData = Awaited<ReturnType<typeof usersShow>>, TError = AuthenticationExceptionResponse | AuthorizationExceptionResponse | ModelNotFoundExceptionResponse>(
 user: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof usersShow>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getUsersShowQueryOptions(user,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}




