/**
 * Generated by orval v8.0.3 🍺
 * Do not edit manually.
 * Petrol Integrity System API Documentation
 * OpenAPI spec version: 0.0.1
 */
import type { ClosingNozzleResource } from './closingNozzleResource';
import type { ClosingTankResource } from './closingTankResource';

export interface ClosingShiftResource {
  shift_id: string;
  status: string;
  station_name: string | 'Station';
  nozzles: ClosingNozzleResource[];
  tanks: ClosingTankResource[];
}
