/**
 * Generated by orval v8.0.3 🍺
 * Do not edit manually.
 * Petrol Integrity System API Documentation
 * OpenAPI spec version: 0.0.1
 */

export interface ClosingNozzleResource {
  nozzle_id: string;
  pump_name: string;
  product_name: string | 'Fuel';
  opening_reading: number;
  digits: string;
}
