/**
 * Generated by orval v8.0.3 🍺
 * Do not edit manually.
 * Petrol Integrity System API Documentation
 * OpenAPI spec version: 0.0.1
 */
import type { CreditSaleResource } from './creditSaleResource';
import type { CreditSalesIndex200Links } from './creditSalesIndex200Links';
import type { CreditSalesIndex200Meta } from './creditSalesIndex200Meta';

export type CreditSalesIndex200 = {
  data: CreditSaleResource[];
  links: CreditSalesIndex200Links;
  meta: CreditSalesIndex200Meta;
};
