/**
 * Generated by orval v8.0.3 🍺
 * Do not edit manually.
 * Petrol Integrity System API Documentation
 * OpenAPI spec version: 0.0.1
 */

export interface CreditSaleResource {
  id: string;
  amount: number;
  /** @nullable */
  vehicle_reg: string | null;
  /** @nullable */
  notes: string | null;
  organization_id: string;
  shift_id: string;
  customer_id: string;
  /** @nullable */
  customer_name: string | null;
  created_at: string;
}
