/**
 * Generated by orval v8.0.3 🍺
 * Do not edit manually.
 * Petrol Integrity System API Documentation
 * OpenAPI spec version: 0.0.1
 */

export type EditRequestsStore403Message = typeof EditRequestsStore403Message[keyof typeof EditRequestsStore403Message];


export const EditRequestsStore403Message = {
  Unauthorized: 'Unauthorized',
} as const;
