/**
 * Generated by orval v8.0.3 🍺
 * Do not edit manually.
 * Petrol Integrity System API Documentation
 * OpenAPI spec version: 0.0.1
 */

export type LiftingsDestroy200Message = typeof LiftingsDestroy200Message[keyof typeof LiftingsDestroy200Message];


export const LiftingsDestroy200Message = {
  Lifting_deleted_and_inventory_reversed_successfully: 'Lifting deleted and inventory reversed successfully.',
} as const;
