/**
 * Generated by orval v8.0.3 🍺
 * Do not edit manually.
 * Petrol Integrity System API Documentation
 * OpenAPI spec version: 0.0.1
 */

export interface Payment {
  id: string;
  organization_id: string;
  shift_id: string;
  method: string;
  amount: string;
  /** @nullable */
  reference_code: string | null;
  /** @nullable */
  created_at: string | null;
  /** @nullable */
  updated_at: string | null;
}
