/**
 * Generated by orval v8.0.3 🍺
 * Do not edit manually.
 * Petrol Integrity System API Documentation
 * OpenAPI spec version: 0.0.1
 */

export type ProductsDestroy200Message = typeof ProductsDestroy200Message[keyof typeof ProductsDestroy200Message];


export const ProductsDestroy200Message = {
  Product_deleted_successfully: 'Product deleted successfully.',
} as const;
