/**
 * Generated by orval v8.0.3 🍺
 * Do not edit manually.
 * Petrol Integrity System API Documentation
 * OpenAPI spec version: 0.0.1
 */
import type { ReportDebtAging200DataItemBuckets030 } from './reportDebtAging200DataItemBuckets030';
import type { ReportDebtAging200DataItemBuckets3160 } from './reportDebtAging200DataItemBuckets3160';
import type { ReportDebtAging200DataItemBuckets6190 } from './reportDebtAging200DataItemBuckets6190';
import type { ReportDebtAging200DataItemBuckets90 } from './reportDebtAging200DataItemBuckets90';

export type ReportDebtAging200DataItemBuckets = {
  '0-30': ReportDebtAging200DataItemBuckets030;
  '31-60': ReportDebtAging200DataItemBuckets3160;
  '61-90': ReportDebtAging200DataItemBuckets6190;
  '90+': ReportDebtAging200DataItemBuckets90;
};
