/**
 * Generated by orval v8.0.3 🍺
 * Do not edit manually.
 * Petrol Integrity System API Documentation
 * OpenAPI spec version: 0.0.1
 */

export type ReportTaxSummary200Data = {
  tax_collected: number;
  tax_paid: number;
  net_tax: number;
};
