/**
 * Generated by orval v8.0.3 🍺
 * Do not edit manually.
 * Petrol Integrity System API Documentation
 * OpenAPI spec version: 0.0.1
 */
import type { ReportTaxSummary200Data } from './reportTaxSummary200Data';

export type ReportTaxSummary200 = {
  data: ReportTaxSummary200Data;
};
