/**
 * Generated by orval v8.0.3 🍺
 * Do not edit manually.
 * Petrol Integrity System API Documentation
 * OpenAPI spec version: 0.0.1
 */
import type { ReportPl200Data } from './reportPl200Data';

export type ReportPl200 = {
  data: ReportPl200Data;
};
