/**
 * Generated by orval v8.0.3 🍺
 * Do not edit manually.
 * Petrol Integrity System API Documentation
 * OpenAPI spec version: 0.0.1
 */
import type { ShiftIndex404Message } from './shiftIndex404Message';

export type ShiftIndex404 = {
  message: ShiftIndex404Message;
};
