/**
 * Generated by orval v8.0.3 🍺
 * Do not edit manually.
 * Petrol Integrity System API Documentation
 * OpenAPI spec version: 0.0.1
 */

export type ShiftIndex404Message = typeof ShiftIndex404Message[keyof typeof ShiftIndex404Message];


export const ShiftIndex404Message = {
  No_active_shift_found: 'No active shift found.',
} as const;
