/**
 * Generated by orval v8.0.3 🍺
 * Do not edit manually.
 * Petrol Integrity System API Documentation
 * OpenAPI spec version: 0.0.1
 */

export type ShiftGenerateInvoices422Message = typeof ShiftGenerateInvoices422Message[keyof typeof ShiftGenerateInvoices422Message];


export const ShiftGenerateInvoices422Message = {
  Shift_must_be_locked_to_generate_invoices: 'Shift must be locked to generate invoices.',
} as const;
