/**
 * Generated by orval v8.0.3 🍺
 * Do not edit manually.
 * Petrol Integrity System API Documentation
 * OpenAPI spec version: 0.0.1
 */

export type ShiftInvoiceData422Message = typeof ShiftInvoiceData422Message[keyof typeof ShiftInvoiceData422Message];


export const ShiftInvoiceData422Message = {
  Shift_must_be_locked_to_fetch_invoice_data: 'Shift must be locked to fetch invoice data.',
} as const;
