/**
 * Generated by orval v8.0.3 🍺
 * Do not edit manually.
 * Petrol Integrity System API Documentation
 * OpenAPI spec version: 0.0.1
 */
import type { Invoice } from './invoice';

export type ShiftGenerateInvoices200 = {
  message: string;
  /**
   * @minItems 2
   * @maxItems 2
   */
  invoices: [Invoice | null, Invoice];
};
