/**
 * Generated by orval v8.0.3 🍺
 * Do not edit manually.
 * Petrol Integrity System API Documentation
 * OpenAPI spec version: 0.0.1
 */

export type StationsIndex200MetaLinksItem = {
  /** @nullable */
  url: string | null;
  label: string;
  active: boolean;
};
