/**
 * Generated by orval v8.0.3 🍺
 * Do not edit manually.
 * Petrol Integrity System API Documentation
 * OpenAPI spec version: 0.0.1
 */

export interface StoreCreditSaleRequest {
  shift_id: string;
  customer_id: string;
  /** @minimum 0.01 */
  amount: number;
  /**
   * @maxLength 255
   * @nullable
   */
  vehicle_reg?: string | null;
  /** @nullable */
  notes?: string | null;
}
