/**
 * Generated by orval v8.0.3 🍺
 * Do not edit manually.
 * Petrol Integrity System API Documentation
 * OpenAPI spec version: 0.0.1
 */
import type { TankResource } from './tankResource';

export type TanksUpdate200 = {
  data: TankResource;
};
