/**
 * Generated by orval v8.0.3 🍺
 * Do not edit manually.
 * Petrol Integrity System API Documentation
 * OpenAPI spec version: 0.0.1
 */

export type TanksDestroy200Message = typeof TanksDestroy200Message[keyof typeof TanksDestroy200Message];


export const TanksDestroy200Message = {
  Tank_deleted_successfully: 'Tank deleted successfully.',
} as const;
