/**
 * Generated by orval v8.0.3 🍺
 * Do not edit manually.
 * Petrol Integrity System API Documentation
 * OpenAPI spec version: 0.0.1
 */

export interface UserResource {
  id: string;
  name: string;
  email: string;
  /** Return the roles as an array (e.g., ["manager", "super-admin"]) */
  roles: unknown[];
  /** @nullable */
  organization_id: string | null;
  /** @nullable */
  station_id: string | null;
  /** @nullable */
  organization_name: string | null;
  /** @nullable */
  station_name: string | null;
  created_at: string;
}
