/**
 * Generated by orval v8.2.0 🍺
 * Do not edit manually.
 * Petrol Integrity System API Documentation
 * OpenAPI spec version: 0.0.1
 */

export interface User {
  id: string;
  name: string;
  email: string;
  /** @nullable */
  organization_id: string | null;
  /** @nullable */
  station_id: string | null;
  /** @nullable */
  email_verified_at: string | null;
  /** @nullable */
  created_at: string | null;
  /** @nullable */
  updated_at: string | null;
}
