/**
 * Generated by orval v8.2.0 🍺
 * Do not edit manually.
 * Petrol Integrity System API Documentation
 * OpenAPI spec version: 0.0.1
 */

export interface ClosingTankResource {
  tank_id: string;
  tank_name: string;
  product_name: string | 'Unknown';
  opening_volume: number;
  capacity: number;
}
