/**
 * Generated by orval v8.0.3 🍺
 * Do not edit manually.
 * Petrol Integrity System API Documentation
 * OpenAPI spec version: 0.0.1
 */
import type { CreditSaleResource } from './creditSaleResource';

export type CreditSalesStore201 = {
  data: CreditSaleResource;
};
