/**
 * Generated by orval v8.2.0 🍺
 * Do not edit manually.
 * Petrol Integrity System API Documentation
 * OpenAPI spec version: 0.0.1
 */
import type { CustomersDestroy200Message } from './customersDestroy200Message';

export type CustomersDestroy200 = {
  message: CustomersDestroy200Message;
};
