/**
 * Generated by orval v8.2.0 🍺
 * Do not edit manually.
 * Petrol Integrity System API Documentation
 * OpenAPI spec version: 0.0.1
 */

export type CustomersDestroy200Message = typeof CustomersDestroy200Message[keyof typeof CustomersDestroy200Message];


export const CustomersDestroy200Message = {
  Customer_deleted_successfully: 'Customer deleted successfully',
} as const;
