/**
 * Generated by orval v8.0.3 🍺
 * Do not edit manually.
 * Petrol Integrity System API Documentation
 * OpenAPI spec version: 0.0.1
 */

export interface DipReading {
  id: string;
  organization_id: string;
  shift_id: string;
  tank_id: string;
  dip_mm: string;
  volume_liters: string;
  /** @nullable */
  created_at: string | null;
  /** @nullable */
  updated_at: string | null;
}
