/**
 * Generated by orval v8.0.3 🍺
 * Do not edit manually.
 * Petrol Integrity System API Documentation
 * OpenAPI spec version: 0.0.1
 */
import type { UserResource } from './userResource';

export interface EditRequestResource {
  id: string;
  status: string;
  model_type: string;
  model_id: string;
  original_data: string;
  requested_data: string;
  reason: string;
  comments: string;
  user?: UserResource;
  approver?: UserResource;
  approved_at: string;
  rejected_at: string;
  created_at: string;
  updated_at: string;
}
