/**
 * Generated by orval v8.0.3 🍺
 * Do not edit manually.
 * Petrol Integrity System API Documentation
 * OpenAPI spec version: 0.0.1
 */
import type { UserResource } from './userResource';

export interface EditRequestResource {
  id: string;
  status: string;
  model_type: string;
  model_id: string;
  /** @nullable */
  original_data: unknown[] | null;
  requested_data: unknown[];
  /** @nullable */
  reason: string | null;
  /** @nullable */
  comments: string | null;
  user?: UserResource;
  approver?: UserResource;
  /** @nullable */
  approved_at: string | null;
  /** @nullable */
  rejected_at: string | null;
  created_at: string;
  updated_at: string;
}
