/**
 * Generated by orval v8.0.3 🍺
 * Do not edit manually.
 * Petrol Integrity System API Documentation
 * OpenAPI spec version: 0.0.1
 */

export interface Invoice {
  id: string;
  organization_id: string;
  shift_id: string;
  customer_id: string;
  invoice_number: string;
  total_amount: string;
  /** @nullable */
  pdf_path: string | null;
  /** @nullable */
  deleted_at: string | null;
  /** @nullable */
  created_at: string | null;
  /** @nullable */
  updated_at: string | null;
}
