/**
 * Generated by orval v8.0.3 🍺
 * Do not edit manually.
 * Petrol Integrity System API Documentation
 * OpenAPI spec version: 0.0.1
 */

export interface InvoiceResource {
  id: string;
  invoice_number: string;
  total_amount: number;
  customer_name: string | 'N/A';
  customer_id: string;
  shift_id: string;
  download_url: string;
  created_at: string;
}
