/**
 * Generated by orval v8.0.3 🍺
 * Do not edit manually.
 * Petrol Integrity System API Documentation
 * OpenAPI spec version: 0.0.1
 */

export type LiftingResourceSupplier = {
  id: string;
  name: string;
  current_balance: number;
};
