/**
 * Generated by orval v8.0.3 🍺
 * Do not edit manually.
 * Petrol Integrity System API Documentation
 * OpenAPI spec version: 0.0.1
 */

export type LockShiftRequestPaymentsCreditItem = {
  customer_id: string;
  /** @minimum 0 */
  amount: number;
  /** @nullable */
  vehicle_reg?: string | null;
};
