/**
 * Generated by orval v8.2.0 🍺
 * Do not edit manually.
 * Petrol Integrity System API Documentation
 * OpenAPI spec version: 0.0.1
 */

export type LockShiftRequestDipsItem = {
  tank_id: string;
  dip_mm: number;
};
