/**
 * Generated by orval v8.2.0 🍺
 * Do not edit manually.
 * Petrol Integrity System API Documentation
 * OpenAPI spec version: 0.0.1
 */
import type { LockShiftRequestPaymentsCreditItem } from './lockShiftRequestPaymentsCreditItem';

export type LockShiftRequestPayments = {
  /**
   * @minimum 0
   * @nullable
   */
  cash?: number | null;
  /**
   * @minimum 0
   * @nullable
   */
  mpesa?: number | null;
  /** @nullable */
  credit?: LockShiftRequestPaymentsCreditItem[] | null;
};
