/**
 * Generated by orval v8.0.3 🍺
 * Do not edit manually.
 * Petrol Integrity System API Documentation
 * OpenAPI spec version: 0.0.1
 */

export type LockShiftRequestMetersItem = {
  nozzle_id: string;
  opening_reading: number;
  closing_reading: number;
  /**
   * @maxLength 8192
   * @nullable
   */
  evidence?: Blob | null;
  /** @nullable */
  gps_coordinates?: string | null;
};
