/**
 * Generated by orval v8.0.3 🍺
 * Do not edit manually.
 * Petrol Integrity System API Documentation
 * OpenAPI spec version: 0.0.1
 */
import type { LockShiftRequestDipsItem } from './lockShiftRequestDipsItem';
import type { LockShiftRequestMetersItem } from './lockShiftRequestMetersItem';
import type { LockShiftRequestPayments } from './lockShiftRequestPayments';

export interface LockShiftRequest {
  payments: LockShiftRequestPayments;
  meters: LockShiftRequestMetersItem[];
  dips: LockShiftRequestDipsItem[];
}
