/**
 * Generated by orval v8.2.0 🍺
 * Do not edit manually.
 * Petrol Integrity System API Documentation
 * OpenAPI spec version: 0.0.1
 */
import type { NozzlesDestroy200Message } from './nozzlesDestroy200Message';

export type NozzlesDestroy200 = {
  message: NozzlesDestroy200Message;
};
