/**
 * Generated by orval v8.2.0 🍺
 * Do not edit manually.
 * Petrol Integrity System API Documentation
 * OpenAPI spec version: 0.0.1
 */

export type NozzlesIndex200Links = {
  /** @nullable */
  first: string | null;
  /** @nullable */
  last: string | null;
  /** @nullable */
  prev: string | null;
  /** @nullable */
  next: string | null;
};
