/**
 * Generated by orval v8.0.3 🍺
 * Do not edit manually.
 * Petrol Integrity System API Documentation
 * OpenAPI spec version: 0.0.1
 */

export type PostLogin401Message = typeof PostLogin401Message[keyof typeof PostLogin401Message];


export const PostLogin401Message = {
  Invalid_credentials: 'Invalid credentials.',
} as const;
