/**
 * Generated by orval v8.2.0 🍺
 * Do not edit manually.
 * Petrol Integrity System API Documentation
 * OpenAPI spec version: 0.0.1
 */

export type ProductsDestroy422Message = typeof ProductsDestroy422Message[keyof typeof ProductsDestroy422Message];


export const ProductsDestroy422Message = {
  Cannot_delete_product_associated_with_active_tanks: 'Cannot delete product associated with active tanks.',
} as const;
