/**
 * Generated by orval v8.2.0 🍺
 * Do not edit manually.
 * Petrol Integrity System API Documentation
 * OpenAPI spec version: 0.0.1
 */
import type { ProductsDestroy422Errors } from './productsDestroy422Errors';
import type { ProductsDestroy422Message } from './productsDestroy422Message';

export type ProductsDestroy422 = {
  message: ProductsDestroy422Message;
  errors: ProductsDestroy422Errors;
};
