/**
 * Generated by orval v8.2.0 🍺
 * Do not edit manually.
 * Petrol Integrity System API Documentation
 * OpenAPI spec version: 0.0.1
 */
import type { ProductsDestroy422ErrorsIdItem0 } from './productsDestroy422ErrorsIdItem0';

export type ProductsDestroy422Errors = {
  /**
   * @minItems 1
   * @maxItems 1
   */
  id: [ProductsDestroy422ErrorsIdItem0];
};
