/**
 * Generated by orval v8.0.3 🍺
 * Do not edit manually.
 * Petrol Integrity System API Documentation
 * OpenAPI spec version: 0.0.1
 */
import type { ReportDebtAging200DataItem } from './reportDebtAging200DataItem';

export type ReportDebtAging200 = {
  data: ReportDebtAging200DataItem[];
};
