/**
 * Generated by orval v8.0.3 🍺
 * Do not edit manually.
 * Petrol Integrity System API Documentation
 * OpenAPI spec version: 0.0.1
 */

export type ReportDebtAging200DataItemBuckets3160 = typeof ReportDebtAging200DataItemBuckets3160[keyof typeof ReportDebtAging200DataItemBuckets3160];


export const ReportDebtAging200DataItemBuckets3160 = {
  NUMBER_0: 0,
} as const;
