/**
 * Generated by orval v8.0.3 🍺
 * Do not edit manually.
 * Petrol Integrity System API Documentation
 * OpenAPI spec version: 0.0.1
 */

export type ReportPl200Data = {
  sales: number;
  costs: number;
  taxes: number;
  net_profit: number;
};
