/**
 * Generated by orval v8.0.3 🍺
 * Do not edit manually.
 * Petrol Integrity System API Documentation
 * OpenAPI spec version: 0.0.1
 */

export type ReportDebtAging200DataItemBuckets90 = typeof ReportDebtAging200DataItemBuckets90[keyof typeof ReportDebtAging200DataItemBuckets90];


export const ReportDebtAging200DataItemBuckets90 = {
  NUMBER_0: 0,
} as const;
