/**
 * Generated by orval v8.0.3 🍺
 * Do not edit manually.
 * Petrol Integrity System API Documentation
 * OpenAPI spec version: 0.0.1
 */

export interface Shift {
  id: string;
  organization_id: string;
  station_id: string;
  started_by_user_id: string;
  /** @nullable */
  locked_by_user_id: string | null;
  started_at: string;
  /** @nullable */
  locked_at: string | null;
  status: string;
  total_collected_cash: number;
  total_expected_cash: number;
  cash_variance: number;
  total_stock_sold_liters: number;
  stock_variance_liters: number;
  /** @nullable */
  created_at: string | null;
  /** @nullable */
  updated_at: string | null;
  total_tax_collected: number;
  /** @nullable */
  deleted_at: string | null;
}
