/**
 * Generated by orval v8.0.3 🍺
 * Do not edit manually.
 * Petrol Integrity System API Documentation
 * OpenAPI spec version: 0.0.1
 */

export type ShiftStore400Message = typeof ShiftStore400Message[keyof typeof ShiftStore400Message];


export const ShiftStore400Message = {
  User_is_not_assigned_to_a_station: 'User is not assigned to a station.',
} as const;
