/**
 * Generated by orval v8.0.3 🍺
 * Do not edit manually.
 * Petrol Integrity System API Documentation
 * OpenAPI spec version: 0.0.1
 */
import type { ShiftCurrent404Message } from './shiftCurrent404Message';

export type ShiftCurrent404 = {
  message: ShiftCurrent404Message;
};
