/**
 * Generated by orval v8.0.3 🍺
 * Do not edit manually.
 * Petrol Integrity System API Documentation
 * OpenAPI spec version: 0.0.1
 */
import type { ShiftGenerateInvoices422Message } from './shiftGenerateInvoices422Message';

export type ShiftGenerateInvoices422 = {
  message: ShiftGenerateInvoices422Message;
};
