/**
 * Generated by orval v8.2.0 🍺
 * Do not edit manually.
 * Petrol Integrity System API Documentation
 * OpenAPI spec version: 0.0.1
 */
import type { MeterReading } from './meterReading';
import type { ShiftResourceFinancials } from './shiftResourceFinancials';

export interface ShiftResource {
  id: string;
  station_name: string;
  started_at: string;
  status: string;
  variance_alert: boolean;
  financials: ShiftResourceFinancials;
  readings?: MeterReading[];
}
