/**
 * Generated by orval v8.2.0 🍺
 * Do not edit manually.
 * Petrol Integrity System API Documentation
 * OpenAPI spec version: 0.0.1
 */

export type ShiftClosingData200Data = {
  shift_id: string;
  status: string;
  station_name: string | 'Station';
  nozzles: string;
  tanks: string;
};
