/**
 * Generated by orval v8.2.0 🍺
 * Do not edit manually.
 * Petrol Integrity System API Documentation
 * OpenAPI spec version: 0.0.1
 */
import type { ShiftStore400Message } from './shiftStore400Message';

export type ShiftStore400 = {
  message: ShiftStore400Message;
};
