/**
 * Generated by orval v8.2.0 🍺
 * Do not edit manually.
 * Petrol Integrity System API Documentation
 * OpenAPI spec version: 0.0.1
 */

export type StationsDestroy200Message = typeof StationsDestroy200Message[keyof typeof StationsDestroy200Message];


export const StationsDestroy200Message = {
  Station_deleted_successfully: 'Station deleted successfully.',
} as const;
