/**
 * Generated by orval v8.2.0 🍺
 * Do not edit manually.
 * Petrol Integrity System API Documentation
 * OpenAPI spec version: 0.0.1
 */

export type StoreTankRequestCalibrationChartItem = {
  /** @minimum 0 */
  mm?: number;
  /** @minimum 0 */
  liters?: number;
};
