/**
 * Generated by orval v8.0.3 🍺
 * Do not edit manually.
 * Petrol Integrity System API Documentation
 * OpenAPI spec version: 0.0.1
 */

export interface StoreLiftingRequest {
  station_id: string;
  tank_id: string;
  lifting_date: string;
  /**
   * @maxLength 255
   * @nullable
   */
  invoice_number?: string | null;
  /** @minimum 1 */
  volume_liters: number;
  /** @minimum 0 */
  buying_price_per_liter: number;
  /**
   * Total cost is usually calculated, but if provided manually, validate it
   * @minimum 0
   */
  total_cost: number;
  /**
   * @minimum 0
   * @nullable
   */
  tax_paid?: number | null;
  /**
   * @maxLength 255
   * @nullable
   */
  supplier_name?: string | null;
  supplier_id?: string;
  is_credit?: boolean;
}
