/**
 * Generated by orval v8.0.3 🍺
 * Do not edit manually.
 * Petrol Integrity System API Documentation
 * OpenAPI spec version: 0.0.1
 */

export type UpdateEditRequestRequestStatus = typeof UpdateEditRequestRequestStatus[keyof typeof UpdateEditRequestRequestStatus];


export const UpdateEditRequestRequestStatus = {
  approved: 'approved',
  rejected: 'rejected',
} as const;
