/**
 * Generated by orval v8.0.3 🍺
 * Do not edit manually.
 * Petrol Integrity System API Documentation
 * OpenAPI spec version: 0.0.1
 */

export interface UpdateLiftingRequest {
  /**
   * Minimal update scope: only supplier_name is updatable via API for now
   * @maxLength 255
   * @nullable
   */
  supplier_name?: string | null;
}
