/**
 * Generated by orval v8.2.0 🍺
 * Do not edit manually.
 * Petrol Integrity System API Documentation
 * OpenAPI spec version: 0.0.1
 */

/**
 * A detailed description of each field that failed validation.
 */
export type ValidationExceptionResponseErrors = {[key: string]: string[]};
