/**
 * Generated by orval v8.0.3 🍺
 * Do not edit manually.
 * Petrol Integrity System API Documentation
 * OpenAPI spec version: 0.0.1
 */
import {
  useMutation,
  useQuery
} from '@tanstack/react-query';
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  MutationFunction,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult
} from '@tanstack/react-query';

import type {
  AuthenticationExceptionResponse,
  AuthorizationExceptionResponse,
  EditRequestsIndex200,
  EditRequestsShow200,
  EditRequestsStore200,
  EditRequestsStore403,
  EditRequestsUpdate200,
  ModelNotFoundExceptionResponse,
  StoreEditRequestRequest,
  UpdateEditRequestRequest,
  ValidationExceptionResponse
} from '.././model';

import { customInstance } from '../../../lib/axios';


type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];



/**
 * @summary List Edit Requests
 */
export type editRequestsIndexResponse200 = {
  data: EditRequestsIndex200
  status: 200
}

export type editRequestsIndexResponse401 = {
  data: AuthenticationExceptionResponse
  status: 401
}
    
export type editRequestsIndexResponseSuccess = (editRequestsIndexResponse200) & {
  headers: Headers;
};
export type editRequestsIndexResponseError = (editRequestsIndexResponse401) & {
  headers: Headers;
};

export type editRequestsIndexResponse = (editRequestsIndexResponseSuccess | editRequestsIndexResponseError)

export const getEditRequestsIndexUrl = () => {


  

  return `/v1/edit-requests`
}

export const editRequestsIndex = async ( options?: RequestInit): Promise<editRequestsIndexResponse> => {
  
  return customInstance<editRequestsIndexResponse>(getEditRequestsIndexUrl(),
  {      
    ...options,
    method: 'GET'
    
    
  }
);}





export const getEditRequestsIndexQueryKey = () => {
    return [
    `/v1/edit-requests`
    ] as const;
    }

    
export const getEditRequestsIndexQueryOptions = <TData = Awaited<ReturnType<typeof editRequestsIndex>>, TError = AuthenticationExceptionResponse>( options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof editRequestsIndex>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getEditRequestsIndexQueryKey();

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof editRequestsIndex>>> = ({ signal }) => editRequestsIndex({ signal, ...requestOptions });

      

      

   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof editRequestsIndex>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type EditRequestsIndexQueryResult = NonNullable<Awaited<ReturnType<typeof editRequestsIndex>>>
export type EditRequestsIndexQueryError = AuthenticationExceptionResponse


export function useEditRequestsIndex<TData = Awaited<ReturnType<typeof editRequestsIndex>>, TError = AuthenticationExceptionResponse>(
  options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof editRequestsIndex>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof editRequestsIndex>>,
          TError,
          Awaited<ReturnType<typeof editRequestsIndex>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useEditRequestsIndex<TData = Awaited<ReturnType<typeof editRequestsIndex>>, TError = AuthenticationExceptionResponse>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof editRequestsIndex>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof editRequestsIndex>>,
          TError,
          Awaited<ReturnType<typeof editRequestsIndex>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useEditRequestsIndex<TData = Awaited<ReturnType<typeof editRequestsIndex>>, TError = AuthenticationExceptionResponse>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof editRequestsIndex>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary List Edit Requests
 */

export function useEditRequestsIndex<TData = Awaited<ReturnType<typeof editRequestsIndex>>, TError = AuthenticationExceptionResponse>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof editRequestsIndex>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getEditRequestsIndexQueryOptions(options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}




/**
 * @summary Create an Edit Request
 */
export type editRequestsStoreResponse200 = {
  data: EditRequestsStore200
  status: 200
}

export type editRequestsStoreResponse401 = {
  data: AuthenticationExceptionResponse
  status: 401
}

export type editRequestsStoreResponse403 = {
  data: EditRequestsStore403
  status: 403
}

export type editRequestsStoreResponse422 = {
  data: ValidationExceptionResponse
  status: 422
}
    
export type editRequestsStoreResponseSuccess = (editRequestsStoreResponse200) & {
  headers: Headers;
};
export type editRequestsStoreResponseError = (editRequestsStoreResponse401 | editRequestsStoreResponse403 | editRequestsStoreResponse422) & {
  headers: Headers;
};

export type editRequestsStoreResponse = (editRequestsStoreResponseSuccess | editRequestsStoreResponseError)

export const getEditRequestsStoreUrl = () => {


  

  return `/v1/edit-requests`
}

export const editRequestsStore = async (storeEditRequestRequest: StoreEditRequestRequest, options?: RequestInit): Promise<editRequestsStoreResponse> => {
  
  return customInstance<editRequestsStoreResponse>(getEditRequestsStoreUrl(),
  {      
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(
      storeEditRequestRequest,)
  }
);}




export const getEditRequestsStoreMutationOptions = <TError = AuthenticationExceptionResponse | EditRequestsStore403 | ValidationExceptionResponse,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof editRequestsStore>>, TError,{data: StoreEditRequestRequest}, TContext>, request?: SecondParameter<typeof customInstance>}
): UseMutationOptions<Awaited<ReturnType<typeof editRequestsStore>>, TError,{data: StoreEditRequestRequest}, TContext> => {

const mutationKey = ['editRequestsStore'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof editRequestsStore>>, {data: StoreEditRequestRequest}> = (props) => {
          const {data} = props ?? {};

          return  editRequestsStore(data,requestOptions)
        }



        


  return  { mutationFn, ...mutationOptions }}

    export type EditRequestsStoreMutationResult = NonNullable<Awaited<ReturnType<typeof editRequestsStore>>>
    export type EditRequestsStoreMutationBody = StoreEditRequestRequest
    export type EditRequestsStoreMutationError = AuthenticationExceptionResponse | EditRequestsStore403 | ValidationExceptionResponse

    /**
 * @summary Create an Edit Request
 */
export const useEditRequestsStore = <TError = AuthenticationExceptionResponse | EditRequestsStore403 | ValidationExceptionResponse,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof editRequestsStore>>, TError,{data: StoreEditRequestRequest}, TContext>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof editRequestsStore>>,
        TError,
        {data: StoreEditRequestRequest},
        TContext
      > => {
      return useMutation(getEditRequestsStoreMutationOptions(options), queryClient);
    }
    /**
 * @summary Show Edit Request details
 */
export type editRequestsShowResponse200 = {
  data: EditRequestsShow200
  status: 200
}

export type editRequestsShowResponse401 = {
  data: AuthenticationExceptionResponse
  status: 401
}

export type editRequestsShowResponse403 = {
  data: AuthorizationExceptionResponse
  status: 403
}

export type editRequestsShowResponse404 = {
  data: ModelNotFoundExceptionResponse
  status: 404
}
    
export type editRequestsShowResponseSuccess = (editRequestsShowResponse200) & {
  headers: Headers;
};
export type editRequestsShowResponseError = (editRequestsShowResponse401 | editRequestsShowResponse403 | editRequestsShowResponse404) & {
  headers: Headers;
};

export type editRequestsShowResponse = (editRequestsShowResponseSuccess | editRequestsShowResponseError)

export const getEditRequestsShowUrl = (editRequest: string,) => {


  

  return `/v1/edit-requests/${editRequest}`
}

export const editRequestsShow = async (editRequest: string, options?: RequestInit): Promise<editRequestsShowResponse> => {
  
  return customInstance<editRequestsShowResponse>(getEditRequestsShowUrl(editRequest),
  {      
    ...options,
    method: 'GET'
    
    
  }
);}





export const getEditRequestsShowQueryKey = (editRequest: string,) => {
    return [
    `/v1/edit-requests/${editRequest}`
    ] as const;
    }

    
export const getEditRequestsShowQueryOptions = <TData = Awaited<ReturnType<typeof editRequestsShow>>, TError = AuthenticationExceptionResponse | AuthorizationExceptionResponse | ModelNotFoundExceptionResponse>(editRequest: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof editRequestsShow>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getEditRequestsShowQueryKey(editRequest);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof editRequestsShow>>> = ({ signal }) => editRequestsShow(editRequest, { signal, ...requestOptions });

      

      

   return  { queryKey, queryFn, enabled: !!(editRequest), ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof editRequestsShow>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type EditRequestsShowQueryResult = NonNullable<Awaited<ReturnType<typeof editRequestsShow>>>
export type EditRequestsShowQueryError = AuthenticationExceptionResponse | AuthorizationExceptionResponse | ModelNotFoundExceptionResponse


export function useEditRequestsShow<TData = Awaited<ReturnType<typeof editRequestsShow>>, TError = AuthenticationExceptionResponse | AuthorizationExceptionResponse | ModelNotFoundExceptionResponse>(
 editRequest: string, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof editRequestsShow>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof editRequestsShow>>,
          TError,
          Awaited<ReturnType<typeof editRequestsShow>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useEditRequestsShow<TData = Awaited<ReturnType<typeof editRequestsShow>>, TError = AuthenticationExceptionResponse | AuthorizationExceptionResponse | ModelNotFoundExceptionResponse>(
 editRequest: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof editRequestsShow>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof editRequestsShow>>,
          TError,
          Awaited<ReturnType<typeof editRequestsShow>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useEditRequestsShow<TData = Awaited<ReturnType<typeof editRequestsShow>>, TError = AuthenticationExceptionResponse | AuthorizationExceptionResponse | ModelNotFoundExceptionResponse>(
 editRequest: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof editRequestsShow>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Show Edit Request details
 */

export function useEditRequestsShow<TData = Awaited<ReturnType<typeof editRequestsShow>>, TError = AuthenticationExceptionResponse | AuthorizationExceptionResponse | ModelNotFoundExceptionResponse>(
 editRequest: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof editRequestsShow>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getEditRequestsShowQueryOptions(editRequest,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}




/**
 * @summary Approve or Reject an Edit Request
 */
export type editRequestsUpdateResponse200 = {
  data: EditRequestsUpdate200
  status: 200
}

export type editRequestsUpdateResponse401 = {
  data: AuthenticationExceptionResponse
  status: 401
}

export type editRequestsUpdateResponse403 = {
  data: AuthorizationExceptionResponse
  status: 403
}

export type editRequestsUpdateResponse404 = {
  data: ModelNotFoundExceptionResponse
  status: 404
}

export type editRequestsUpdateResponse422 = {
  data: ValidationExceptionResponse
  status: 422
}
    
export type editRequestsUpdateResponseSuccess = (editRequestsUpdateResponse200) & {
  headers: Headers;
};
export type editRequestsUpdateResponseError = (editRequestsUpdateResponse401 | editRequestsUpdateResponse403 | editRequestsUpdateResponse404 | editRequestsUpdateResponse422) & {
  headers: Headers;
};

export type editRequestsUpdateResponse = (editRequestsUpdateResponseSuccess | editRequestsUpdateResponseError)

export const getEditRequestsUpdateUrl = (editRequest: string,) => {


  

  return `/v1/edit-requests/${editRequest}`
}

export const editRequestsUpdate = async (editRequest: string,
    updateEditRequestRequest: UpdateEditRequestRequest, options?: RequestInit): Promise<editRequestsUpdateResponse> => {
  
  return customInstance<editRequestsUpdateResponse>(getEditRequestsUpdateUrl(editRequest),
  {      
    ...options,
    method: 'PUT',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(
      updateEditRequestRequest,)
  }
);}




export const getEditRequestsUpdateMutationOptions = <TError = AuthenticationExceptionResponse | AuthorizationExceptionResponse | ModelNotFoundExceptionResponse | ValidationExceptionResponse,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof editRequestsUpdate>>, TError,{editRequest: string;data: UpdateEditRequestRequest}, TContext>, request?: SecondParameter<typeof customInstance>}
): UseMutationOptions<Awaited<ReturnType<typeof editRequestsUpdate>>, TError,{editRequest: string;data: UpdateEditRequestRequest}, TContext> => {

const mutationKey = ['editRequestsUpdate'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof editRequestsUpdate>>, {editRequest: string;data: UpdateEditRequestRequest}> = (props) => {
          const {editRequest,data} = props ?? {};

          return  editRequestsUpdate(editRequest,data,requestOptions)
        }



        


  return  { mutationFn, ...mutationOptions }}

    export type EditRequestsUpdateMutationResult = NonNullable<Awaited<ReturnType<typeof editRequestsUpdate>>>
    export type EditRequestsUpdateMutationBody = UpdateEditRequestRequest
    export type EditRequestsUpdateMutationError = AuthenticationExceptionResponse | AuthorizationExceptionResponse | ModelNotFoundExceptionResponse | ValidationExceptionResponse

    /**
 * @summary Approve or Reject an Edit Request
 */
export const useEditRequestsUpdate = <TError = AuthenticationExceptionResponse | AuthorizationExceptionResponse | ModelNotFoundExceptionResponse | ValidationExceptionResponse,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof editRequestsUpdate>>, TError,{editRequest: string;data: UpdateEditRequestRequest}, TContext>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof editRequestsUpdate>>,
        TError,
        {editRequest: string;data: UpdateEditRequestRequest},
        TContext
      > => {
      return useMutation(getEditRequestsUpdateMutationOptions(options), queryClient);
    }
    