/**
 * Generated by orval v8.0.3 🍺
 * Do not edit manually.
 * Petrol Integrity System API Documentation
 * OpenAPI spec version: 0.0.1
 */
import {
  useMutation,
  useQuery
} from '@tanstack/react-query';
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  MutationFunction,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult
} from '@tanstack/react-query';

import type {
  AuthenticationExceptionResponse,
  AuthorizationExceptionResponse,
  LiftingsDestroy200,
  LiftingsIndex200,
  LiftingsShow200,
  LiftingsStore201,
  LiftingsUpdate200,
  ModelNotFoundExceptionResponse,
  StoreLiftingRequest,
  UpdateLiftingRequest,
  ValidationExceptionResponse
} from '.././model';

import { customInstance } from '../../../lib/axios';


type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];



/**
 * @summary List Liftings
Filterable by date range and station (for Admins)
 */
export type liftingsIndexResponse200 = {
  data: LiftingsIndex200
  status: 200
}

export type liftingsIndexResponse401 = {
  data: AuthenticationExceptionResponse
  status: 401
}
    
export type liftingsIndexResponseSuccess = (liftingsIndexResponse200) & {
  headers: Headers;
};
export type liftingsIndexResponseError = (liftingsIndexResponse401) & {
  headers: Headers;
};

export type liftingsIndexResponse = (liftingsIndexResponseSuccess | liftingsIndexResponseError)

export const getLiftingsIndexUrl = () => {


  

  return `/v1/liftings`
}

export const liftingsIndex = async ( options?: RequestInit): Promise<liftingsIndexResponse> => {
  
  return customInstance<liftingsIndexResponse>(getLiftingsIndexUrl(),
  {      
    ...options,
    method: 'GET'
    
    
  }
);}





export const getLiftingsIndexQueryKey = () => {
    return [
    `/v1/liftings`
    ] as const;
    }

    
export const getLiftingsIndexQueryOptions = <TData = Awaited<ReturnType<typeof liftingsIndex>>, TError = AuthenticationExceptionResponse>( options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof liftingsIndex>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getLiftingsIndexQueryKey();

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof liftingsIndex>>> = ({ signal }) => liftingsIndex({ signal, ...requestOptions });

      

      

   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof liftingsIndex>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type LiftingsIndexQueryResult = NonNullable<Awaited<ReturnType<typeof liftingsIndex>>>
export type LiftingsIndexQueryError = AuthenticationExceptionResponse


export function useLiftingsIndex<TData = Awaited<ReturnType<typeof liftingsIndex>>, TError = AuthenticationExceptionResponse>(
  options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof liftingsIndex>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof liftingsIndex>>,
          TError,
          Awaited<ReturnType<typeof liftingsIndex>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useLiftingsIndex<TData = Awaited<ReturnType<typeof liftingsIndex>>, TError = AuthenticationExceptionResponse>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof liftingsIndex>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof liftingsIndex>>,
          TError,
          Awaited<ReturnType<typeof liftingsIndex>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useLiftingsIndex<TData = Awaited<ReturnType<typeof liftingsIndex>>, TError = AuthenticationExceptionResponse>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof liftingsIndex>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary List Liftings
Filterable by date range and station (for Admins)
 */

export function useLiftingsIndex<TData = Awaited<ReturnType<typeof liftingsIndex>>, TError = AuthenticationExceptionResponse>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof liftingsIndex>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getLiftingsIndexQueryOptions(options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}




/**
 * @summary Store a new Lifting
 */
export type liftingsStoreResponse201 = {
  data: LiftingsStore201
  status: 201
}

export type liftingsStoreResponse401 = {
  data: AuthenticationExceptionResponse
  status: 401
}

export type liftingsStoreResponse403 = {
  data: AuthorizationExceptionResponse
  status: 403
}

export type liftingsStoreResponse422 = {
  data: ValidationExceptionResponse
  status: 422
}
    
export type liftingsStoreResponseSuccess = (liftingsStoreResponse201) & {
  headers: Headers;
};
export type liftingsStoreResponseError = (liftingsStoreResponse401 | liftingsStoreResponse403 | liftingsStoreResponse422) & {
  headers: Headers;
};

export type liftingsStoreResponse = (liftingsStoreResponseSuccess | liftingsStoreResponseError)

export const getLiftingsStoreUrl = () => {


  

  return `/v1/liftings`
}

export const liftingsStore = async (storeLiftingRequest: StoreLiftingRequest, options?: RequestInit): Promise<liftingsStoreResponse> => {
  
  return customInstance<liftingsStoreResponse>(getLiftingsStoreUrl(),
  {      
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(
      storeLiftingRequest,)
  }
);}




export const getLiftingsStoreMutationOptions = <TError = AuthenticationExceptionResponse | AuthorizationExceptionResponse | ValidationExceptionResponse,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof liftingsStore>>, TError,{data: StoreLiftingRequest}, TContext>, request?: SecondParameter<typeof customInstance>}
): UseMutationOptions<Awaited<ReturnType<typeof liftingsStore>>, TError,{data: StoreLiftingRequest}, TContext> => {

const mutationKey = ['liftingsStore'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof liftingsStore>>, {data: StoreLiftingRequest}> = (props) => {
          const {data} = props ?? {};

          return  liftingsStore(data,requestOptions)
        }



        


  return  { mutationFn, ...mutationOptions }}

    export type LiftingsStoreMutationResult = NonNullable<Awaited<ReturnType<typeof liftingsStore>>>
    export type LiftingsStoreMutationBody = StoreLiftingRequest
    export type LiftingsStoreMutationError = AuthenticationExceptionResponse | AuthorizationExceptionResponse | ValidationExceptionResponse

    /**
 * @summary Store a new Lifting
 */
export const useLiftingsStore = <TError = AuthenticationExceptionResponse | AuthorizationExceptionResponse | ValidationExceptionResponse,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof liftingsStore>>, TError,{data: StoreLiftingRequest}, TContext>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof liftingsStore>>,
        TError,
        {data: StoreLiftingRequest},
        TContext
      > => {
      return useMutation(getLiftingsStoreMutationOptions(options), queryClient);
    }
    /**
 * @summary Show a specific lifting
 */
export type liftingsShowResponse200 = {
  data: LiftingsShow200
  status: 200
}

export type liftingsShowResponse401 = {
  data: AuthenticationExceptionResponse
  status: 401
}

export type liftingsShowResponse403 = {
  data: AuthorizationExceptionResponse
  status: 403
}

export type liftingsShowResponse404 = {
  data: ModelNotFoundExceptionResponse
  status: 404
}
    
export type liftingsShowResponseSuccess = (liftingsShowResponse200) & {
  headers: Headers;
};
export type liftingsShowResponseError = (liftingsShowResponse401 | liftingsShowResponse403 | liftingsShowResponse404) & {
  headers: Headers;
};

export type liftingsShowResponse = (liftingsShowResponseSuccess | liftingsShowResponseError)

export const getLiftingsShowUrl = (lifting: string,) => {


  

  return `/v1/liftings/${lifting}`
}

export const liftingsShow = async (lifting: string, options?: RequestInit): Promise<liftingsShowResponse> => {
  
  return customInstance<liftingsShowResponse>(getLiftingsShowUrl(lifting),
  {      
    ...options,
    method: 'GET'
    
    
  }
);}





export const getLiftingsShowQueryKey = (lifting: string,) => {
    return [
    `/v1/liftings/${lifting}`
    ] as const;
    }

    
export const getLiftingsShowQueryOptions = <TData = Awaited<ReturnType<typeof liftingsShow>>, TError = AuthenticationExceptionResponse | AuthorizationExceptionResponse | ModelNotFoundExceptionResponse>(lifting: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof liftingsShow>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getLiftingsShowQueryKey(lifting);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof liftingsShow>>> = ({ signal }) => liftingsShow(lifting, { signal, ...requestOptions });

      

      

   return  { queryKey, queryFn, enabled: !!(lifting), ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof liftingsShow>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type LiftingsShowQueryResult = NonNullable<Awaited<ReturnType<typeof liftingsShow>>>
export type LiftingsShowQueryError = AuthenticationExceptionResponse | AuthorizationExceptionResponse | ModelNotFoundExceptionResponse


export function useLiftingsShow<TData = Awaited<ReturnType<typeof liftingsShow>>, TError = AuthenticationExceptionResponse | AuthorizationExceptionResponse | ModelNotFoundExceptionResponse>(
 lifting: string, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof liftingsShow>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof liftingsShow>>,
          TError,
          Awaited<ReturnType<typeof liftingsShow>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useLiftingsShow<TData = Awaited<ReturnType<typeof liftingsShow>>, TError = AuthenticationExceptionResponse | AuthorizationExceptionResponse | ModelNotFoundExceptionResponse>(
 lifting: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof liftingsShow>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof liftingsShow>>,
          TError,
          Awaited<ReturnType<typeof liftingsShow>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useLiftingsShow<TData = Awaited<ReturnType<typeof liftingsShow>>, TError = AuthenticationExceptionResponse | AuthorizationExceptionResponse | ModelNotFoundExceptionResponse>(
 lifting: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof liftingsShow>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Show a specific lifting
 */

export function useLiftingsShow<TData = Awaited<ReturnType<typeof liftingsShow>>, TError = AuthenticationExceptionResponse | AuthorizationExceptionResponse | ModelNotFoundExceptionResponse>(
 lifting: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof liftingsShow>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getLiftingsShowQueryOptions(lifting,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}




/**
 * @summary Update a lifting (currently only supports updating supplier_name)
 */
export type liftingsUpdateResponse200 = {
  data: LiftingsUpdate200
  status: 200
}

export type liftingsUpdateResponse401 = {
  data: AuthenticationExceptionResponse
  status: 401
}

export type liftingsUpdateResponse403 = {
  data: AuthorizationExceptionResponse
  status: 403
}

export type liftingsUpdateResponse404 = {
  data: ModelNotFoundExceptionResponse
  status: 404
}

export type liftingsUpdateResponse422 = {
  data: ValidationExceptionResponse
  status: 422
}
    
export type liftingsUpdateResponseSuccess = (liftingsUpdateResponse200) & {
  headers: Headers;
};
export type liftingsUpdateResponseError = (liftingsUpdateResponse401 | liftingsUpdateResponse403 | liftingsUpdateResponse404 | liftingsUpdateResponse422) & {
  headers: Headers;
};

export type liftingsUpdateResponse = (liftingsUpdateResponseSuccess | liftingsUpdateResponseError)

export const getLiftingsUpdateUrl = (lifting: string,) => {


  

  return `/v1/liftings/${lifting}`
}

export const liftingsUpdate = async (lifting: string,
    updateLiftingRequest: UpdateLiftingRequest, options?: RequestInit): Promise<liftingsUpdateResponse> => {
  
  return customInstance<liftingsUpdateResponse>(getLiftingsUpdateUrl(lifting),
  {      
    ...options,
    method: 'PUT',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(
      updateLiftingRequest,)
  }
);}




export const getLiftingsUpdateMutationOptions = <TError = AuthenticationExceptionResponse | AuthorizationExceptionResponse | ModelNotFoundExceptionResponse | ValidationExceptionResponse,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof liftingsUpdate>>, TError,{lifting: string;data: UpdateLiftingRequest}, TContext>, request?: SecondParameter<typeof customInstance>}
): UseMutationOptions<Awaited<ReturnType<typeof liftingsUpdate>>, TError,{lifting: string;data: UpdateLiftingRequest}, TContext> => {

const mutationKey = ['liftingsUpdate'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof liftingsUpdate>>, {lifting: string;data: UpdateLiftingRequest}> = (props) => {
          const {lifting,data} = props ?? {};

          return  liftingsUpdate(lifting,data,requestOptions)
        }



        


  return  { mutationFn, ...mutationOptions }}

    export type LiftingsUpdateMutationResult = NonNullable<Awaited<ReturnType<typeof liftingsUpdate>>>
    export type LiftingsUpdateMutationBody = UpdateLiftingRequest
    export type LiftingsUpdateMutationError = AuthenticationExceptionResponse | AuthorizationExceptionResponse | ModelNotFoundExceptionResponse | ValidationExceptionResponse

    /**
 * @summary Update a lifting (currently only supports updating supplier_name)
 */
export const useLiftingsUpdate = <TError = AuthenticationExceptionResponse | AuthorizationExceptionResponse | ModelNotFoundExceptionResponse | ValidationExceptionResponse,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof liftingsUpdate>>, TError,{lifting: string;data: UpdateLiftingRequest}, TContext>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof liftingsUpdate>>,
        TError,
        {lifting: string;data: UpdateLiftingRequest},
        TContext
      > => {
      return useMutation(getLiftingsUpdateMutationOptions(options), queryClient);
    }
    /**
 * @summary Delete a lifting
(Reverses the inventory effect automatically via model 'deleted' event)
 */
export type liftingsDestroyResponse200 = {
  data: LiftingsDestroy200
  status: 200
}

export type liftingsDestroyResponse401 = {
  data: AuthenticationExceptionResponse
  status: 401
}

export type liftingsDestroyResponse403 = {
  data: AuthorizationExceptionResponse
  status: 403
}

export type liftingsDestroyResponse404 = {
  data: ModelNotFoundExceptionResponse
  status: 404
}
    
export type liftingsDestroyResponseSuccess = (liftingsDestroyResponse200) & {
  headers: Headers;
};
export type liftingsDestroyResponseError = (liftingsDestroyResponse401 | liftingsDestroyResponse403 | liftingsDestroyResponse404) & {
  headers: Headers;
};

export type liftingsDestroyResponse = (liftingsDestroyResponseSuccess | liftingsDestroyResponseError)

export const getLiftingsDestroyUrl = (lifting: string,) => {


  

  return `/v1/liftings/${lifting}`
}

export const liftingsDestroy = async (lifting: string, options?: RequestInit): Promise<liftingsDestroyResponse> => {
  
  return customInstance<liftingsDestroyResponse>(getLiftingsDestroyUrl(lifting),
  {      
    ...options,
    method: 'DELETE'
    
    
  }
);}




export const getLiftingsDestroyMutationOptions = <TError = AuthenticationExceptionResponse | AuthorizationExceptionResponse | ModelNotFoundExceptionResponse,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof liftingsDestroy>>, TError,{lifting: string}, TContext>, request?: SecondParameter<typeof customInstance>}
): UseMutationOptions<Awaited<ReturnType<typeof liftingsDestroy>>, TError,{lifting: string}, TContext> => {

const mutationKey = ['liftingsDestroy'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof liftingsDestroy>>, {lifting: string}> = (props) => {
          const {lifting} = props ?? {};

          return  liftingsDestroy(lifting,requestOptions)
        }



        


  return  { mutationFn, ...mutationOptions }}

    export type LiftingsDestroyMutationResult = NonNullable<Awaited<ReturnType<typeof liftingsDestroy>>>
    
    export type LiftingsDestroyMutationError = AuthenticationExceptionResponse | AuthorizationExceptionResponse | ModelNotFoundExceptionResponse

    /**
 * @summary Delete a lifting
(Reverses the inventory effect automatically via model 'deleted' event)
 */
export const useLiftingsDestroy = <TError = AuthenticationExceptionResponse | AuthorizationExceptionResponse | ModelNotFoundExceptionResponse,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof liftingsDestroy>>, TError,{lifting: string}, TContext>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof liftingsDestroy>>,
        TError,
        {lifting: string},
        TContext
      > => {
      return useMutation(getLiftingsDestroyMutationOptions(options), queryClient);
    }
    