import axios, { AxiosRequestConfig } from 'axios';
import * as SecureStore from 'expo-secure-store';

export const BASE_URL = process.env.EXPO_PUBLIC_BASE_URL;

export const api = axios.create({
  baseURL: BASE_URL,
  headers: {
    'Content-Type': 'application/json',
    'Accept': 'application/json',
    'Except': ''
  },
});

// 1. Interceptor: Auto-attach Token
api.interceptors.request.use(async (config) => {
  const token = await SecureStore.getItemAsync('auth_token');
  if (token) {
    config.headers.Authorization = `Bearer ${token}`;
  }

  // 👇 ADD THIS BLOCK TO SEE THE URL
  console.log('------------------------------------------------');
  console.log('🚀 API Request:', config.method?.toUpperCase(), config.baseURL, config.url);
  console.log('------------------------------------------------');

  return config;
});

// 2. Custom Mutator for Orval (Required for the next step)
// This tells the generator how to actually execute the requests
export const customInstance = <T>(
  url: string,
  options?: AxiosRequestConfig,
): Promise<T> => {
  const source = axios.CancelToken.source();
  const data = options?.data ?? options?.body;

  /* 
   * FIX: Orval generates FormData with repeated keys (e.g. 'meters', 'meters') 
   * but the backend expects "exploded" keys (e.g. 'meters[0][nozzle_id]').
   * We intercept and fix this here by parsing the JSON values and recursively flattening them.
   */
  if (data instanceof FormData) {
    const newData = new FormData();

    const appendRecursive = (formData: FormData, data: any, rootKey: string) => {
      if (rootKey === 'evidence' && data instanceof Blob) {
        formData.append(rootKey, data);
        return;
      }
      if (data instanceof Date) {
        formData.append(rootKey, data.toISOString());
      } else if (data instanceof Blob || data instanceof File) {
        formData.append(rootKey, data);
      } else if (Array.isArray(data)) {
        data.forEach((value, index) => {
          appendRecursive(formData, value, `${rootKey}[${index}]`);
        });
      } else if (typeof data === 'object' && data !== null) {
        Object.keys(data).forEach((key) => {
          appendRecursive(formData, data[key], `${rootKey}[${key}]`);
        });
      } else {
        formData.append(rootKey, String(data));
      }
    };

    // converting to any because FormData iteration types can be tricky in some RN versions
    // We expect 'meters', 'dips', 'payments' to be passed as JSON strings if generated by Orval
    const keysToExplode = ['meters', 'dips', 'payments'];
    const tempStore: Record<string, any[]> = {}; // Store repeating keys to merge into array

    (data as any).forEach((value: any, key: string) => {
      if (keysToExplode.includes(key)) {
        // Try to parse JSON. If it's a string, it might be the JSON representation.
        try {
          if (typeof value === 'string') {
            const parsed = JSON.parse(value);
            // If it's meters/dips, Orval might be sending item by item (repeated key) or as a list wrapped in one string.
            // We accumulate them just in case.
            if (!tempStore[key]) tempStore[key] = [];
            tempStore[key].push(parsed);
          } else {
            // Already an object/array?
            if (!tempStore[key]) tempStore[key] = [];
            tempStore[key].push(value);
          }
        } catch (e) {
          // Fallback: treat as normal value
          newData.append(key, value);
        }
      } else {
        newData.append(key, value);
      }
    });

    // Now process the exploded keys
    Object.keys(tempStore).forEach((key) => {
      const values = tempStore[key];
      // If we have multiple values for the same key (e.g. repeated meters), we treat them as an array.
      // However, if the parsed value ITSELF is an array (e.g. payments might be sent as one big object?), we need to handle that.
      // Based on previous errors, 'meters' was sent as repeated items.

      // Flatten the accumulated list. If 'meters' was sent 3 times with 3 objects, values = [obj1, obj2, obj3].
      // If 'payments' was sent once with 1 object, values = [obj].

      // Special Handling: If the key expects an array (meters, dips) but we only collected single objects,
      // we essentially have the array we want in 'values'.
      // If 'payments' is a single object, 'values' is [paymentObj]. We likely want `payments[cash]`, not `payments[0][cash]`.

      if (key === 'payments' && values.length === 1 && !Array.isArray(values[0])) {
        // Single object case: payments: { cash: ... } -> payments[cash]
        appendRecursive(newData, values[0], key);
      } else {
        // Array case: meters: [obj1] -> meters[0][id]
        // Note: Orval generated code usually JSON.stringifies the *item* if it sends repeated keys.
        // But if it sent an array in one go, 'values' might be [[obj1, obj2]]. 
        // Let's flatten one level if needed? 
        // Actually, if tempStore[key] contains multiple items, it IS the array.
        // If tempStore[key] contains one item and that item IS an array, we use that array.

        let finalArray = values;
        if (values.length === 1 && Array.isArray(values[0])) {
          finalArray = values[0];
        }

        finalArray.forEach((item, index) => {
          appendRecursive(newData, item, `${key}[${index}]`);
        });
      }
    });

    const promise = api({
      url,
      ...options,
      data: newData,
      cancelToken: source.token,
    }).then(({ data }) => data);

    // @ts-ignore
    promise.cancel = () => {
      source.cancel('Query was cancelled');
    };

    return promise;
  }

  const promise = api({
    url,
    ...options,
    data,
    cancelToken: source.token,
  }).then(({ data }) => data);

  // @ts-ignore
  promise.cancel = () => {
    source.cancel('Query was cancelled');
  };

  return promise;
};