/**
 * Generated by orval v8.0.3 🍺
 * Do not edit manually.
 * Petrol Integrity System API Documentation
 * OpenAPI spec version: 0.0.1
 */
import {
  useQuery
} from '@tanstack/react-query';
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseQueryOptions,
  UseQueryResult
} from '@tanstack/react-query';

import type {
  AuditLogIndex200,
  AuditLogShow200,
  AuditLogShow403,
  AuthenticationExceptionResponse,
  ModelNotFoundExceptionResponse
} from '.././model';

import { customInstance } from '../../../lib/axios';


type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];



/**
 * @summary Display audit logs according to the user role
 */
export type auditLogIndexResponse200 = {
  data: AuditLogIndex200
  status: 200
}

export type auditLogIndexResponse401 = {
  data: AuthenticationExceptionResponse
  status: 401
}
    
export type auditLogIndexResponseSuccess = (auditLogIndexResponse200) & {
  headers: Headers;
};
export type auditLogIndexResponseError = (auditLogIndexResponse401) & {
  headers: Headers;
};

export type auditLogIndexResponse = (auditLogIndexResponseSuccess | auditLogIndexResponseError)

export const getAuditLogIndexUrl = () => {


  

  return `/v1/audit-logs`
}

export const auditLogIndex = async ( options?: RequestInit): Promise<auditLogIndexResponse> => {
  
  return customInstance<auditLogIndexResponse>(getAuditLogIndexUrl(),
  {      
    ...options,
    method: 'GET'
    
    
  }
);}





export const getAuditLogIndexQueryKey = () => {
    return [
    `/v1/audit-logs`
    ] as const;
    }

    
export const getAuditLogIndexQueryOptions = <TData = Awaited<ReturnType<typeof auditLogIndex>>, TError = AuthenticationExceptionResponse>( options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof auditLogIndex>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getAuditLogIndexQueryKey();

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof auditLogIndex>>> = ({ signal }) => auditLogIndex({ signal, ...requestOptions });

      

      

   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof auditLogIndex>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type AuditLogIndexQueryResult = NonNullable<Awaited<ReturnType<typeof auditLogIndex>>>
export type AuditLogIndexQueryError = AuthenticationExceptionResponse


export function useAuditLogIndex<TData = Awaited<ReturnType<typeof auditLogIndex>>, TError = AuthenticationExceptionResponse>(
  options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof auditLogIndex>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof auditLogIndex>>,
          TError,
          Awaited<ReturnType<typeof auditLogIndex>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useAuditLogIndex<TData = Awaited<ReturnType<typeof auditLogIndex>>, TError = AuthenticationExceptionResponse>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof auditLogIndex>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof auditLogIndex>>,
          TError,
          Awaited<ReturnType<typeof auditLogIndex>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useAuditLogIndex<TData = Awaited<ReturnType<typeof auditLogIndex>>, TError = AuthenticationExceptionResponse>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof auditLogIndex>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Display audit logs according to the user role
 */

export function useAuditLogIndex<TData = Awaited<ReturnType<typeof auditLogIndex>>, TError = AuthenticationExceptionResponse>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof auditLogIndex>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getAuditLogIndexQueryOptions(options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}




/**
 * @summary Display a specific audit log
 */
export type auditLogShowResponse200 = {
  data: AuditLogShow200
  status: 200
}

export type auditLogShowResponse401 = {
  data: AuthenticationExceptionResponse
  status: 401
}

export type auditLogShowResponse403 = {
  data: AuditLogShow403
  status: 403
}

export type auditLogShowResponse404 = {
  data: ModelNotFoundExceptionResponse
  status: 404
}
    
export type auditLogShowResponseSuccess = (auditLogShowResponse200) & {
  headers: Headers;
};
export type auditLogShowResponseError = (auditLogShowResponse401 | auditLogShowResponse403 | auditLogShowResponse404) & {
  headers: Headers;
};

export type auditLogShowResponse = (auditLogShowResponseSuccess | auditLogShowResponseError)

export const getAuditLogShowUrl = (activity: number,) => {


  

  return `/v1/audit-logs/${activity}`
}

export const auditLogShow = async (activity: number, options?: RequestInit): Promise<auditLogShowResponse> => {
  
  return customInstance<auditLogShowResponse>(getAuditLogShowUrl(activity),
  {      
    ...options,
    method: 'GET'
    
    
  }
);}





export const getAuditLogShowQueryKey = (activity: number,) => {
    return [
    `/v1/audit-logs/${activity}`
    ] as const;
    }

    
export const getAuditLogShowQueryOptions = <TData = Awaited<ReturnType<typeof auditLogShow>>, TError = AuthenticationExceptionResponse | AuditLogShow403 | ModelNotFoundExceptionResponse>(activity: number, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof auditLogShow>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getAuditLogShowQueryKey(activity);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof auditLogShow>>> = ({ signal }) => auditLogShow(activity, { signal, ...requestOptions });

      

      

   return  { queryKey, queryFn, enabled: !!(activity), ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof auditLogShow>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type AuditLogShowQueryResult = NonNullable<Awaited<ReturnType<typeof auditLogShow>>>
export type AuditLogShowQueryError = AuthenticationExceptionResponse | AuditLogShow403 | ModelNotFoundExceptionResponse


export function useAuditLogShow<TData = Awaited<ReturnType<typeof auditLogShow>>, TError = AuthenticationExceptionResponse | AuditLogShow403 | ModelNotFoundExceptionResponse>(
 activity: number, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof auditLogShow>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof auditLogShow>>,
          TError,
          Awaited<ReturnType<typeof auditLogShow>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useAuditLogShow<TData = Awaited<ReturnType<typeof auditLogShow>>, TError = AuthenticationExceptionResponse | AuditLogShow403 | ModelNotFoundExceptionResponse>(
 activity: number, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof auditLogShow>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof auditLogShow>>,
          TError,
          Awaited<ReturnType<typeof auditLogShow>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useAuditLogShow<TData = Awaited<ReturnType<typeof auditLogShow>>, TError = AuthenticationExceptionResponse | AuditLogShow403 | ModelNotFoundExceptionResponse>(
 activity: number, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof auditLogShow>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Display a specific audit log
 */

export function useAuditLogShow<TData = Awaited<ReturnType<typeof auditLogShow>>, TError = AuthenticationExceptionResponse | AuditLogShow403 | ModelNotFoundExceptionResponse>(
 activity: number, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof auditLogShow>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getAuditLogShowQueryOptions(activity,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}




