/**
 * Generated by orval v8.2.0 🍺
 * Do not edit manually.
 * Petrol Integrity System API Documentation
 * OpenAPI spec version: 0.0.1
 */
import {
  useMutation,
  useQuery
} from '@tanstack/react-query';
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  MutationFunction,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult
} from '@tanstack/react-query';

import type {
  AuthenticationExceptionResponse,
  AuthorizationExceptionResponse,
  ModelNotFoundExceptionResponse,
  StoreTankRequest,
  TanksDestroy200,
  TanksIndex200,
  TanksShow200,
  TanksStore200,
  TanksUpdate200,
  UpdateTankRequest,
  ValidationExceptionResponse
} from '.././model';

import { customInstance } from '../../../lib/axios';


type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];



/**
 * @summary List Tanks
Filterable by Station ID
 */
export type tanksIndexResponse200 = {
  data: TanksIndex200
  status: 200
}

export type tanksIndexResponse401 = {
  data: AuthenticationExceptionResponse
  status: 401
}

export type tanksIndexResponse403 = {
  data: AuthorizationExceptionResponse
  status: 403
}
    
export type tanksIndexResponseSuccess = (tanksIndexResponse200) & {
  headers: Headers;
};
export type tanksIndexResponseError = (tanksIndexResponse401 | tanksIndexResponse403) & {
  headers: Headers;
};

export type tanksIndexResponse = (tanksIndexResponseSuccess | tanksIndexResponseError)

export const getTanksIndexUrl = () => {


  

  return `/v1/tanks`
}

export const tanksIndex = async ( options?: RequestInit): Promise<tanksIndexResponse> => {
  
  return customInstance<tanksIndexResponse>(getTanksIndexUrl(),
  {      
    ...options,
    method: 'GET'
    
    
  }
);}





export const getTanksIndexQueryKey = () => {
    return [
    `/v1/tanks`
    ] as const;
    }

    
export const getTanksIndexQueryOptions = <TData = Awaited<ReturnType<typeof tanksIndex>>, TError = AuthenticationExceptionResponse | AuthorizationExceptionResponse>( options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof tanksIndex>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getTanksIndexQueryKey();

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof tanksIndex>>> = ({ signal }) => tanksIndex({ signal, ...requestOptions });

      

      

   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof tanksIndex>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type TanksIndexQueryResult = NonNullable<Awaited<ReturnType<typeof tanksIndex>>>
export type TanksIndexQueryError = AuthenticationExceptionResponse | AuthorizationExceptionResponse


export function useTanksIndex<TData = Awaited<ReturnType<typeof tanksIndex>>, TError = AuthenticationExceptionResponse | AuthorizationExceptionResponse>(
  options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof tanksIndex>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof tanksIndex>>,
          TError,
          Awaited<ReturnType<typeof tanksIndex>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useTanksIndex<TData = Awaited<ReturnType<typeof tanksIndex>>, TError = AuthenticationExceptionResponse | AuthorizationExceptionResponse>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof tanksIndex>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof tanksIndex>>,
          TError,
          Awaited<ReturnType<typeof tanksIndex>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useTanksIndex<TData = Awaited<ReturnType<typeof tanksIndex>>, TError = AuthenticationExceptionResponse | AuthorizationExceptionResponse>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof tanksIndex>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary List Tanks
Filterable by Station ID
 */

export function useTanksIndex<TData = Awaited<ReturnType<typeof tanksIndex>>, TError = AuthenticationExceptionResponse | AuthorizationExceptionResponse>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof tanksIndex>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getTanksIndexQueryOptions(options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}




/**
 * @summary Store a new Tank
 */
export type tanksStoreResponse200 = {
  data: TanksStore200
  status: 200
}

export type tanksStoreResponse401 = {
  data: AuthenticationExceptionResponse
  status: 401
}

export type tanksStoreResponse403 = {
  data: AuthorizationExceptionResponse
  status: 403
}

export type tanksStoreResponse422 = {
  data: ValidationExceptionResponse
  status: 422
}
    
export type tanksStoreResponseSuccess = (tanksStoreResponse200) & {
  headers: Headers;
};
export type tanksStoreResponseError = (tanksStoreResponse401 | tanksStoreResponse403 | tanksStoreResponse422) & {
  headers: Headers;
};

export type tanksStoreResponse = (tanksStoreResponseSuccess | tanksStoreResponseError)

export const getTanksStoreUrl = () => {


  

  return `/v1/tanks`
}

export const tanksStore = async (storeTankRequest: StoreTankRequest, options?: RequestInit): Promise<tanksStoreResponse> => {
  
  return customInstance<tanksStoreResponse>(getTanksStoreUrl(),
  {      
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(
      storeTankRequest,)
  }
);}




export const getTanksStoreMutationOptions = <TError = AuthenticationExceptionResponse | AuthorizationExceptionResponse | ValidationExceptionResponse,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof tanksStore>>, TError,{data: StoreTankRequest}, TContext>, request?: SecondParameter<typeof customInstance>}
): UseMutationOptions<Awaited<ReturnType<typeof tanksStore>>, TError,{data: StoreTankRequest}, TContext> => {

const mutationKey = ['tanksStore'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof tanksStore>>, {data: StoreTankRequest}> = (props) => {
          const {data} = props ?? {};

          return  tanksStore(data,requestOptions)
        }



        


  return  { mutationFn, ...mutationOptions }}

    export type TanksStoreMutationResult = NonNullable<Awaited<ReturnType<typeof tanksStore>>>
    export type TanksStoreMutationBody = StoreTankRequest
    export type TanksStoreMutationError = AuthenticationExceptionResponse | AuthorizationExceptionResponse | ValidationExceptionResponse

    /**
 * @summary Store a new Tank
 */
export const useTanksStore = <TError = AuthenticationExceptionResponse | AuthorizationExceptionResponse | ValidationExceptionResponse,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof tanksStore>>, TError,{data: StoreTankRequest}, TContext>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof tanksStore>>,
        TError,
        {data: StoreTankRequest},
        TContext
      > => {
      return useMutation(getTanksStoreMutationOptions(options), queryClient);
    }
    /**
 * @summary Show a specific Tank
 */
export type tanksShowResponse200 = {
  data: TanksShow200
  status: 200
}

export type tanksShowResponse401 = {
  data: AuthenticationExceptionResponse
  status: 401
}

export type tanksShowResponse403 = {
  data: AuthorizationExceptionResponse
  status: 403
}

export type tanksShowResponse404 = {
  data: ModelNotFoundExceptionResponse
  status: 404
}
    
export type tanksShowResponseSuccess = (tanksShowResponse200) & {
  headers: Headers;
};
export type tanksShowResponseError = (tanksShowResponse401 | tanksShowResponse403 | tanksShowResponse404) & {
  headers: Headers;
};

export type tanksShowResponse = (tanksShowResponseSuccess | tanksShowResponseError)

export const getTanksShowUrl = (tank: string,) => {


  

  return `/v1/tanks/${tank}`
}

export const tanksShow = async (tank: string, options?: RequestInit): Promise<tanksShowResponse> => {
  
  return customInstance<tanksShowResponse>(getTanksShowUrl(tank),
  {      
    ...options,
    method: 'GET'
    
    
  }
);}





export const getTanksShowQueryKey = (tank: string,) => {
    return [
    `/v1/tanks/${tank}`
    ] as const;
    }

    
export const getTanksShowQueryOptions = <TData = Awaited<ReturnType<typeof tanksShow>>, TError = AuthenticationExceptionResponse | AuthorizationExceptionResponse | ModelNotFoundExceptionResponse>(tank: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof tanksShow>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getTanksShowQueryKey(tank);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof tanksShow>>> = ({ signal }) => tanksShow(tank, { signal, ...requestOptions });

      

      

   return  { queryKey, queryFn, enabled: !!(tank), ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof tanksShow>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type TanksShowQueryResult = NonNullable<Awaited<ReturnType<typeof tanksShow>>>
export type TanksShowQueryError = AuthenticationExceptionResponse | AuthorizationExceptionResponse | ModelNotFoundExceptionResponse


export function useTanksShow<TData = Awaited<ReturnType<typeof tanksShow>>, TError = AuthenticationExceptionResponse | AuthorizationExceptionResponse | ModelNotFoundExceptionResponse>(
 tank: string, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof tanksShow>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof tanksShow>>,
          TError,
          Awaited<ReturnType<typeof tanksShow>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useTanksShow<TData = Awaited<ReturnType<typeof tanksShow>>, TError = AuthenticationExceptionResponse | AuthorizationExceptionResponse | ModelNotFoundExceptionResponse>(
 tank: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof tanksShow>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof tanksShow>>,
          TError,
          Awaited<ReturnType<typeof tanksShow>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useTanksShow<TData = Awaited<ReturnType<typeof tanksShow>>, TError = AuthenticationExceptionResponse | AuthorizationExceptionResponse | ModelNotFoundExceptionResponse>(
 tank: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof tanksShow>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Show a specific Tank
 */

export function useTanksShow<TData = Awaited<ReturnType<typeof tanksShow>>, TError = AuthenticationExceptionResponse | AuthorizationExceptionResponse | ModelNotFoundExceptionResponse>(
 tank: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof tanksShow>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getTanksShowQueryOptions(tank,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}




/**
 * @summary Update Tank details
 */
export type tanksUpdateResponse200 = {
  data: TanksUpdate200
  status: 200
}

export type tanksUpdateResponse401 = {
  data: AuthenticationExceptionResponse
  status: 401
}

export type tanksUpdateResponse403 = {
  data: AuthorizationExceptionResponse
  status: 403
}

export type tanksUpdateResponse404 = {
  data: ModelNotFoundExceptionResponse
  status: 404
}

export type tanksUpdateResponse422 = {
  data: ValidationExceptionResponse
  status: 422
}
    
export type tanksUpdateResponseSuccess = (tanksUpdateResponse200) & {
  headers: Headers;
};
export type tanksUpdateResponseError = (tanksUpdateResponse401 | tanksUpdateResponse403 | tanksUpdateResponse404 | tanksUpdateResponse422) & {
  headers: Headers;
};

export type tanksUpdateResponse = (tanksUpdateResponseSuccess | tanksUpdateResponseError)

export const getTanksUpdateUrl = (tank: string,) => {


  

  return `/v1/tanks/${tank}`
}

export const tanksUpdate = async (tank: string,
    updateTankRequest: UpdateTankRequest, options?: RequestInit): Promise<tanksUpdateResponse> => {
  
  return customInstance<tanksUpdateResponse>(getTanksUpdateUrl(tank),
  {      
    ...options,
    method: 'PUT',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(
      updateTankRequest,)
  }
);}




export const getTanksUpdateMutationOptions = <TError = AuthenticationExceptionResponse | AuthorizationExceptionResponse | ModelNotFoundExceptionResponse | ValidationExceptionResponse,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof tanksUpdate>>, TError,{tank: string;data: UpdateTankRequest}, TContext>, request?: SecondParameter<typeof customInstance>}
): UseMutationOptions<Awaited<ReturnType<typeof tanksUpdate>>, TError,{tank: string;data: UpdateTankRequest}, TContext> => {

const mutationKey = ['tanksUpdate'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof tanksUpdate>>, {tank: string;data: UpdateTankRequest}> = (props) => {
          const {tank,data} = props ?? {};

          return  tanksUpdate(tank,data,requestOptions)
        }



        


  return  { mutationFn, ...mutationOptions }}

    export type TanksUpdateMutationResult = NonNullable<Awaited<ReturnType<typeof tanksUpdate>>>
    export type TanksUpdateMutationBody = UpdateTankRequest
    export type TanksUpdateMutationError = AuthenticationExceptionResponse | AuthorizationExceptionResponse | ModelNotFoundExceptionResponse | ValidationExceptionResponse

    /**
 * @summary Update Tank details
 */
export const useTanksUpdate = <TError = AuthenticationExceptionResponse | AuthorizationExceptionResponse | ModelNotFoundExceptionResponse | ValidationExceptionResponse,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof tanksUpdate>>, TError,{tank: string;data: UpdateTankRequest}, TContext>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof tanksUpdate>>,
        TError,
        {tank: string;data: UpdateTankRequest},
        TContext
      > => {
      return useMutation(getTanksUpdateMutationOptions(options), queryClient);
    }
    /**
 * @summary Delete a Tank
 */
export type tanksDestroyResponse200 = {
  data: TanksDestroy200
  status: 200
}

export type tanksDestroyResponse401 = {
  data: AuthenticationExceptionResponse
  status: 401
}

export type tanksDestroyResponse403 = {
  data: AuthorizationExceptionResponse
  status: 403
}

export type tanksDestroyResponse404 = {
  data: ModelNotFoundExceptionResponse
  status: 404
}
    
export type tanksDestroyResponseSuccess = (tanksDestroyResponse200) & {
  headers: Headers;
};
export type tanksDestroyResponseError = (tanksDestroyResponse401 | tanksDestroyResponse403 | tanksDestroyResponse404) & {
  headers: Headers;
};

export type tanksDestroyResponse = (tanksDestroyResponseSuccess | tanksDestroyResponseError)

export const getTanksDestroyUrl = (tank: string,) => {


  

  return `/v1/tanks/${tank}`
}

export const tanksDestroy = async (tank: string, options?: RequestInit): Promise<tanksDestroyResponse> => {
  
  return customInstance<tanksDestroyResponse>(getTanksDestroyUrl(tank),
  {      
    ...options,
    method: 'DELETE'
    
    
  }
);}




export const getTanksDestroyMutationOptions = <TError = AuthenticationExceptionResponse | AuthorizationExceptionResponse | ModelNotFoundExceptionResponse,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof tanksDestroy>>, TError,{tank: string}, TContext>, request?: SecondParameter<typeof customInstance>}
): UseMutationOptions<Awaited<ReturnType<typeof tanksDestroy>>, TError,{tank: string}, TContext> => {

const mutationKey = ['tanksDestroy'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof tanksDestroy>>, {tank: string}> = (props) => {
          const {tank} = props ?? {};

          return  tanksDestroy(tank,requestOptions)
        }



        


  return  { mutationFn, ...mutationOptions }}

    export type TanksDestroyMutationResult = NonNullable<Awaited<ReturnType<typeof tanksDestroy>>>
    
    export type TanksDestroyMutationError = AuthenticationExceptionResponse | AuthorizationExceptionResponse | ModelNotFoundExceptionResponse

    /**
 * @summary Delete a Tank
 */
export const useTanksDestroy = <TError = AuthenticationExceptionResponse | AuthorizationExceptionResponse | ModelNotFoundExceptionResponse,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof tanksDestroy>>, TError,{tank: string}, TContext>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof tanksDestroy>>,
        TError,
        {tank: string},
        TContext
      > => {
      return useMutation(getTanksDestroyMutationOptions(options), queryClient);
    }
    