/**
 * Generated by orval v8.2.0 🍺
 * Do not edit manually.
 * Petrol Integrity System API Documentation
 * OpenAPI spec version: 0.0.1
 */
import {
  useMutation,
  useQuery
} from '@tanstack/react-query';
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  MutationFunction,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult
} from '@tanstack/react-query';

import type {
  AuthenticationExceptionResponse,
  LockShiftRequest,
  ModelNotFoundExceptionResponse,
  ShiftClosingData200,
  ShiftClosingData403,
  ShiftIndex200,
  ShiftIndex404,
  ShiftLock200,
  ShiftLock403,
  ShiftLock500,
  ShiftStore200,
  ShiftStore400,
  ValidationExceptionResponse
} from '.././model';

import { customInstance } from '../../../lib/axios';


type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];



/**
 * @summary Display a listing of the resource
 */
export type shiftIndexResponse200 = {
  data: ShiftIndex200
  status: 200
}

export type shiftIndexResponse401 = {
  data: AuthenticationExceptionResponse
  status: 401
}

export type shiftIndexResponse404 = {
  data: ShiftIndex404
  status: 404
}

export type shiftIndexResponseSuccess = (shiftIndexResponse200) & {
  headers: Headers;
};
export type shiftIndexResponseError = (shiftIndexResponse401 | shiftIndexResponse404) & {
  headers: Headers;
};

export type shiftIndexResponse = (shiftIndexResponseSuccess | shiftIndexResponseError)

export const getShiftIndexUrl = () => {




  return `/v1/shifts/current`
}

export const shiftIndex = async (options?: RequestInit): Promise<shiftIndexResponse> => {

  return customInstance<shiftIndexResponse>(getShiftIndexUrl(),
    {
      ...options,
      method: 'GET'


    }
  );
}





export const getShiftIndexQueryKey = () => {
  return [
    `/v1/shifts/current`
  ] as const;
}


export const getShiftIndexQueryOptions = <TData = Awaited<ReturnType<typeof shiftIndex>>, TError = AuthenticationExceptionResponse | ShiftIndex404>(options?: { query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof shiftIndex>>, TError, TData>>, request?: SecondParameter<typeof customInstance> }
) => {

  const { query: queryOptions, request: requestOptions } = options ?? {};

  const queryKey = queryOptions?.queryKey ?? getShiftIndexQueryKey();



  const queryFn: QueryFunction<Awaited<ReturnType<typeof shiftIndex>>> = ({ signal }) => shiftIndex({ signal, ...requestOptions });





  return { queryKey, queryFn, ...queryOptions } as UseQueryOptions<Awaited<ReturnType<typeof shiftIndex>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type ShiftIndexQueryResult = NonNullable<Awaited<ReturnType<typeof shiftIndex>>>
export type ShiftIndexQueryError = AuthenticationExceptionResponse | ShiftIndex404


export function useShiftIndex<TData = Awaited<ReturnType<typeof shiftIndex>>, TError = AuthenticationExceptionResponse | ShiftIndex404>(
  options: {
    query: Partial<UseQueryOptions<Awaited<ReturnType<typeof shiftIndex>>, TError, TData>> & Pick<
      DefinedInitialDataOptions<
        Awaited<ReturnType<typeof shiftIndex>>,
        TError,
        Awaited<ReturnType<typeof shiftIndex>>
      >, 'initialData'
    >, request?: SecondParameter<typeof customInstance>
  }
  , queryClient?: QueryClient
): DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useShiftIndex<TData = Awaited<ReturnType<typeof shiftIndex>>, TError = AuthenticationExceptionResponse | ShiftIndex404>(
  options?: {
    query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof shiftIndex>>, TError, TData>> & Pick<
      UndefinedInitialDataOptions<
        Awaited<ReturnType<typeof shiftIndex>>,
        TError,
        Awaited<ReturnType<typeof shiftIndex>>
      >, 'initialData'
    >, request?: SecondParameter<typeof customInstance>
  }
  , queryClient?: QueryClient
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useShiftIndex<TData = Awaited<ReturnType<typeof shiftIndex>>, TError = AuthenticationExceptionResponse | ShiftIndex404>(
  options?: { query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof shiftIndex>>, TError, TData>>, request?: SecondParameter<typeof customInstance> }
  , queryClient?: QueryClient
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Display a listing of the resource
 */

export function useShiftIndex<TData = Awaited<ReturnType<typeof shiftIndex>>, TError = AuthenticationExceptionResponse | ShiftIndex404>(
  options?: { query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof shiftIndex>>, TError, TData>>, request?: SecondParameter<typeof customInstance> }
  , queryClient?: QueryClient
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getShiftIndexQueryOptions(options)

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}




/**
 * @summary Store a newly created resource in storage
 */
export type shiftStoreResponse200 = {
  data: ShiftStore200
  status: 200
}

export type shiftStoreResponse400 = {
  data: ShiftStore400
  status: 400
}

export type shiftStoreResponse401 = {
  data: AuthenticationExceptionResponse
  status: 401
}

export type shiftStoreResponseSuccess = (shiftStoreResponse200) & {
  headers: Headers;
};
export type shiftStoreResponseError = (shiftStoreResponse400 | shiftStoreResponse401) & {
  headers: Headers;
};

export type shiftStoreResponse = (shiftStoreResponseSuccess | shiftStoreResponseError)

export const getShiftStoreUrl = () => {




  return `/v1/shifts/start`
}

export const shiftStore = async (options?: RequestInit): Promise<shiftStoreResponse> => {

  return customInstance<shiftStoreResponse>(getShiftStoreUrl(),
    {
      ...options,
      method: 'POST'


    }
  );
}




export const getShiftStoreMutationOptions = <TError = ShiftStore400 | AuthenticationExceptionResponse,
  TContext = unknown>(options?: { mutation?: UseMutationOptions<Awaited<ReturnType<typeof shiftStore>>, TError, void, TContext>, request?: SecondParameter<typeof customInstance> }
  ): UseMutationOptions<Awaited<ReturnType<typeof shiftStore>>, TError, void, TContext> => {

  const mutationKey = ['shiftStore'];
  const { mutation: mutationOptions, request: requestOptions } = options ?
    options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey, }, request: undefined };




  const mutationFn: MutationFunction<Awaited<ReturnType<typeof shiftStore>>, void> = () => {


    return shiftStore(requestOptions)
  }






  return { mutationFn, ...mutationOptions }
}

export type ShiftStoreMutationResult = NonNullable<Awaited<ReturnType<typeof shiftStore>>>

export type ShiftStoreMutationError = ShiftStore400 | AuthenticationExceptionResponse

/**
* @summary Store a newly created resource in storage
*/
export const useShiftStore = <TError = ShiftStore400 | AuthenticationExceptionResponse,
  TContext = unknown>(options?: { mutation?: UseMutationOptions<Awaited<ReturnType<typeof shiftStore>>, TError, void, TContext>, request?: SecondParameter<typeof customInstance> }
    , queryClient?: QueryClient): UseMutationResult<
      Awaited<ReturnType<typeof shiftStore>>,
      TError,
      void,
      TContext
    > => {
  return useMutation(getShiftStoreMutationOptions(options), queryClient);
}
/**
* @summary Lock a Shift
* Submits final readings, evidence, and payments to close a shift.
Calculates variance immediately
*/
export type shiftLockResponse200 = {
  data: ShiftLock200
  status: 200
}

export type shiftLockResponse401 = {
  data: AuthenticationExceptionResponse
  status: 401
}

export type shiftLockResponse403 = {
  data: ShiftLock403
  status: 403
}

export type shiftLockResponse404 = {
  data: ModelNotFoundExceptionResponse
  status: 404
}

export type shiftLockResponse422 = {
  data: ValidationExceptionResponse
  status: 422
}

export type shiftLockResponse500 = {
  data: ShiftLock500
  status: 500
}

export type shiftLockResponseSuccess = (shiftLockResponse200) & {
  headers: Headers;
};
export type shiftLockResponseError = (shiftLockResponse401 | shiftLockResponse403 | shiftLockResponse404 | shiftLockResponse422 | shiftLockResponse500) & {
  headers: Headers;
};

export type shiftLockResponse = (shiftLockResponseSuccess | shiftLockResponseError)

export const getShiftLockUrl = (shift: string,) => {




  return `/v1/shifts/${shift}/lock`
}

export const shiftLock = async (shift: string,
  lockShiftRequest: LockShiftRequest, options?: RequestInit): Promise<shiftLockResponse> => {
  const formData = new FormData();
  formData.append(`payments`, JSON.stringify(lockShiftRequest.payments));
  lockShiftRequest.meters.forEach(value => formData.append(`meters`, JSON.stringify(value)));
  lockShiftRequest.dips.forEach(value => formData.append(`dips`, JSON.stringify(value)));

  return customInstance<shiftLockResponse>(getShiftLockUrl(shift),
    {
      ...options,
      method: 'POST'
      ,
      body:
        formData,
    }
  );
}




export const getShiftLockMutationOptions = <TError = AuthenticationExceptionResponse | ShiftLock403 | ModelNotFoundExceptionResponse | ValidationExceptionResponse | ShiftLock500,
  TContext = unknown>(options?: { mutation?: UseMutationOptions<Awaited<ReturnType<typeof shiftLock>>, TError, { shift: string; data: LockShiftRequest }, TContext>, request?: SecondParameter<typeof customInstance> }
  ): UseMutationOptions<Awaited<ReturnType<typeof shiftLock>>, TError, { shift: string; data: LockShiftRequest }, TContext> => {

  const mutationKey = ['shiftLock'];
  const { mutation: mutationOptions, request: requestOptions } = options ?
    options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey, }, request: undefined };




  const mutationFn: MutationFunction<Awaited<ReturnType<typeof shiftLock>>, { shift: string; data: LockShiftRequest }> = (props) => {
    const { shift, data } = props ?? {};

    return shiftLock(shift, data, requestOptions)
  }






  return { mutationFn, ...mutationOptions }
}

export type ShiftLockMutationResult = NonNullable<Awaited<ReturnType<typeof shiftLock>>>
export type ShiftLockMutationBody = LockShiftRequest
export type ShiftLockMutationError = AuthenticationExceptionResponse | ShiftLock403 | ModelNotFoundExceptionResponse | ValidationExceptionResponse | ShiftLock500

/**
* @summary Lock a Shift
* Submits final readings, evidence, and payments to close a shift.
Calculates variance immediately
*/
export const useShiftLock = <TError = AuthenticationExceptionResponse | ShiftLock403 | ModelNotFoundExceptionResponse | ValidationExceptionResponse | ShiftLock500,
  TContext = unknown>(options?: { mutation?: UseMutationOptions<Awaited<ReturnType<typeof shiftLock>>, TError, { shift: string; data: LockShiftRequest }, TContext>, request?: SecondParameter<typeof customInstance> }
    , queryClient?: QueryClient): UseMutationResult<
      Awaited<ReturnType<typeof shiftLock>>,
      TError,
      { shift: string; data: LockShiftRequest },
      TContext
    > => {
  return useMutation(getShiftLockMutationOptions(options), queryClient);
}
/**
* @summary Get closing data for the purpose of closing a shift
*/
export type shiftClosingDataResponse200 = {
  data: ShiftClosingData200
  status: 200
}

export type shiftClosingDataResponse401 = {
  data: AuthenticationExceptionResponse
  status: 401
}

export type shiftClosingDataResponse403 = {
  data: ShiftClosingData403
  status: 403
}

export type shiftClosingDataResponse404 = {
  data: ModelNotFoundExceptionResponse
  status: 404
}

export type shiftClosingDataResponseSuccess = (shiftClosingDataResponse200) & {
  headers: Headers;
};
export type shiftClosingDataResponseError = (shiftClosingDataResponse401 | shiftClosingDataResponse403 | shiftClosingDataResponse404) & {
  headers: Headers;
};

export type shiftClosingDataResponse = (shiftClosingDataResponseSuccess | shiftClosingDataResponseError)

export const getShiftClosingDataUrl = (shift: string,) => {




  return `/v1/shifts/${shift}/closing-data`
}

export const shiftClosingData = async (shift: string, options?: RequestInit): Promise<shiftClosingDataResponse> => {

  return customInstance<shiftClosingDataResponse>(getShiftClosingDataUrl(shift),
    {
      ...options,
      method: 'GET'


    }
  );
}





export const getShiftClosingDataQueryKey = (shift: string,) => {
  return [
    `/v1/shifts/${shift}/closing-data`
  ] as const;
}


export const getShiftClosingDataQueryOptions = <TData = Awaited<ReturnType<typeof shiftClosingData>>, TError = AuthenticationExceptionResponse | ShiftClosingData403 | ModelNotFoundExceptionResponse>(shift: string, options?: { query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof shiftClosingData>>, TError, TData>>, request?: SecondParameter<typeof customInstance> }
) => {

  const { query: queryOptions, request: requestOptions } = options ?? {};

  const queryKey = queryOptions?.queryKey ?? getShiftClosingDataQueryKey(shift);



  const queryFn: QueryFunction<Awaited<ReturnType<typeof shiftClosingData>>> = ({ signal }) => shiftClosingData(shift, { signal, ...requestOptions });





  return { queryKey, queryFn, enabled: !!(shift), ...queryOptions } as UseQueryOptions<Awaited<ReturnType<typeof shiftClosingData>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type ShiftClosingDataQueryResult = NonNullable<Awaited<ReturnType<typeof shiftClosingData>>>
export type ShiftClosingDataQueryError = AuthenticationExceptionResponse | ShiftClosingData403 | ModelNotFoundExceptionResponse


export function useShiftClosingData<TData = Awaited<ReturnType<typeof shiftClosingData>>, TError = AuthenticationExceptionResponse | ShiftClosingData403 | ModelNotFoundExceptionResponse>(
  shift: string, options: {
    query: Partial<UseQueryOptions<Awaited<ReturnType<typeof shiftClosingData>>, TError, TData>> & Pick<
      DefinedInitialDataOptions<
        Awaited<ReturnType<typeof shiftClosingData>>,
        TError,
        Awaited<ReturnType<typeof shiftClosingData>>
      >, 'initialData'
    >, request?: SecondParameter<typeof customInstance>
  }
  , queryClient?: QueryClient
): DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useShiftClosingData<TData = Awaited<ReturnType<typeof shiftClosingData>>, TError = AuthenticationExceptionResponse | ShiftClosingData403 | ModelNotFoundExceptionResponse>(
  shift: string, options?: {
    query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof shiftClosingData>>, TError, TData>> & Pick<
      UndefinedInitialDataOptions<
        Awaited<ReturnType<typeof shiftClosingData>>,
        TError,
        Awaited<ReturnType<typeof shiftClosingData>>
      >, 'initialData'
    >, request?: SecondParameter<typeof customInstance>
  }
  , queryClient?: QueryClient
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useShiftClosingData<TData = Awaited<ReturnType<typeof shiftClosingData>>, TError = AuthenticationExceptionResponse | ShiftClosingData403 | ModelNotFoundExceptionResponse>(
  shift: string, options?: { query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof shiftClosingData>>, TError, TData>>, request?: SecondParameter<typeof customInstance> }
  , queryClient?: QueryClient
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Get closing data for the purpose of closing a shift
 */

export function useShiftClosingData<TData = Awaited<ReturnType<typeof shiftClosingData>>, TError = AuthenticationExceptionResponse | ShiftClosingData403 | ModelNotFoundExceptionResponse>(
  shift: string, options?: { query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof shiftClosingData>>, TError, TData>>, request?: SecondParameter<typeof customInstance> }
  , queryClient?: QueryClient
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getShiftClosingDataQueryOptions(shift, options)

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}




