/**
 * Generated by orval v8.0.3 🍺
 * Do not edit manually.
 * Petrol Integrity System API Documentation
 * OpenAPI spec version: 0.0.1
 */
import {
  useMutation,
  useQuery
} from '@tanstack/react-query';
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  MutationFunction,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult
} from '@tanstack/react-query';

import type {
  AuthenticationExceptionResponse,
  AuthorizationExceptionResponse,
  ModelNotFoundExceptionResponse,
  OrganizationsIndex200,
  OrganizationsShow200,
  OrganizationsStore200,
  StoreOrganizationRequest,
  ValidationExceptionResponse
} from '.././model';

import { customInstance } from '../../../lib/axios';


type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];



/**
 * @summary List all organizations
 */
export type organizationsIndexResponse200 = {
  data: OrganizationsIndex200
  status: 200
}

export type organizationsIndexResponse401 = {
  data: AuthenticationExceptionResponse
  status: 401
}

export type organizationsIndexResponse403 = {
  data: AuthorizationExceptionResponse
  status: 403
}
    
export type organizationsIndexResponseSuccess = (organizationsIndexResponse200) & {
  headers: Headers;
};
export type organizationsIndexResponseError = (organizationsIndexResponse401 | organizationsIndexResponse403) & {
  headers: Headers;
};

export type organizationsIndexResponse = (organizationsIndexResponseSuccess | organizationsIndexResponseError)

export const getOrganizationsIndexUrl = () => {


  

  return `/v1/organizations`
}

export const organizationsIndex = async ( options?: RequestInit): Promise<organizationsIndexResponse> => {
  
  return customInstance<organizationsIndexResponse>(getOrganizationsIndexUrl(),
  {      
    ...options,
    method: 'GET'
    
    
  }
);}





export const getOrganizationsIndexQueryKey = () => {
    return [
    `/v1/organizations`
    ] as const;
    }

    
export const getOrganizationsIndexQueryOptions = <TData = Awaited<ReturnType<typeof organizationsIndex>>, TError = AuthenticationExceptionResponse | AuthorizationExceptionResponse>( options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof organizationsIndex>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getOrganizationsIndexQueryKey();

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof organizationsIndex>>> = ({ signal }) => organizationsIndex({ signal, ...requestOptions });

      

      

   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof organizationsIndex>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type OrganizationsIndexQueryResult = NonNullable<Awaited<ReturnType<typeof organizationsIndex>>>
export type OrganizationsIndexQueryError = AuthenticationExceptionResponse | AuthorizationExceptionResponse


export function useOrganizationsIndex<TData = Awaited<ReturnType<typeof organizationsIndex>>, TError = AuthenticationExceptionResponse | AuthorizationExceptionResponse>(
  options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof organizationsIndex>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof organizationsIndex>>,
          TError,
          Awaited<ReturnType<typeof organizationsIndex>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useOrganizationsIndex<TData = Awaited<ReturnType<typeof organizationsIndex>>, TError = AuthenticationExceptionResponse | AuthorizationExceptionResponse>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof organizationsIndex>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof organizationsIndex>>,
          TError,
          Awaited<ReturnType<typeof organizationsIndex>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useOrganizationsIndex<TData = Awaited<ReturnType<typeof organizationsIndex>>, TError = AuthenticationExceptionResponse | AuthorizationExceptionResponse>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof organizationsIndex>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary List all organizations
 */

export function useOrganizationsIndex<TData = Awaited<ReturnType<typeof organizationsIndex>>, TError = AuthenticationExceptionResponse | AuthorizationExceptionResponse>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof organizationsIndex>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getOrganizationsIndexQueryOptions(options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}




/**
 * @summary Store a newly created organization in storage
 */
export type organizationsStoreResponse200 = {
  data: OrganizationsStore200
  status: 200
}

export type organizationsStoreResponse401 = {
  data: AuthenticationExceptionResponse
  status: 401
}

export type organizationsStoreResponse403 = {
  data: AuthorizationExceptionResponse
  status: 403
}

export type organizationsStoreResponse422 = {
  data: ValidationExceptionResponse
  status: 422
}
    
export type organizationsStoreResponseSuccess = (organizationsStoreResponse200) & {
  headers: Headers;
};
export type organizationsStoreResponseError = (organizationsStoreResponse401 | organizationsStoreResponse403 | organizationsStoreResponse422) & {
  headers: Headers;
};

export type organizationsStoreResponse = (organizationsStoreResponseSuccess | organizationsStoreResponseError)

export const getOrganizationsStoreUrl = () => {


  

  return `/v1/organizations`
}

export const organizationsStore = async (storeOrganizationRequest: StoreOrganizationRequest, options?: RequestInit): Promise<organizationsStoreResponse> => {
  
  return customInstance<organizationsStoreResponse>(getOrganizationsStoreUrl(),
  {      
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(
      storeOrganizationRequest,)
  }
);}




export const getOrganizationsStoreMutationOptions = <TError = AuthenticationExceptionResponse | AuthorizationExceptionResponse | ValidationExceptionResponse,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof organizationsStore>>, TError,{data: StoreOrganizationRequest}, TContext>, request?: SecondParameter<typeof customInstance>}
): UseMutationOptions<Awaited<ReturnType<typeof organizationsStore>>, TError,{data: StoreOrganizationRequest}, TContext> => {

const mutationKey = ['organizationsStore'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof organizationsStore>>, {data: StoreOrganizationRequest}> = (props) => {
          const {data} = props ?? {};

          return  organizationsStore(data,requestOptions)
        }



        


  return  { mutationFn, ...mutationOptions }}

    export type OrganizationsStoreMutationResult = NonNullable<Awaited<ReturnType<typeof organizationsStore>>>
    export type OrganizationsStoreMutationBody = StoreOrganizationRequest
    export type OrganizationsStoreMutationError = AuthenticationExceptionResponse | AuthorizationExceptionResponse | ValidationExceptionResponse

    /**
 * @summary Store a newly created organization in storage
 */
export const useOrganizationsStore = <TError = AuthenticationExceptionResponse | AuthorizationExceptionResponse | ValidationExceptionResponse,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof organizationsStore>>, TError,{data: StoreOrganizationRequest}, TContext>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof organizationsStore>>,
        TError,
        {data: StoreOrganizationRequest},
        TContext
      > => {
      return useMutation(getOrganizationsStoreMutationOptions(options), queryClient);
    }
    /**
 * @summary Display the specified organization
 */
export type organizationsShowResponse200 = {
  data: OrganizationsShow200
  status: 200
}

export type organizationsShowResponse401 = {
  data: AuthenticationExceptionResponse
  status: 401
}

export type organizationsShowResponse403 = {
  data: AuthorizationExceptionResponse
  status: 403
}

export type organizationsShowResponse404 = {
  data: ModelNotFoundExceptionResponse
  status: 404
}
    
export type organizationsShowResponseSuccess = (organizationsShowResponse200) & {
  headers: Headers;
};
export type organizationsShowResponseError = (organizationsShowResponse401 | organizationsShowResponse403 | organizationsShowResponse404) & {
  headers: Headers;
};

export type organizationsShowResponse = (organizationsShowResponseSuccess | organizationsShowResponseError)

export const getOrganizationsShowUrl = (organization: string,) => {


  

  return `/v1/organizations/${organization}`
}

export const organizationsShow = async (organization: string, options?: RequestInit): Promise<organizationsShowResponse> => {
  
  return customInstance<organizationsShowResponse>(getOrganizationsShowUrl(organization),
  {      
    ...options,
    method: 'GET'
    
    
  }
);}





export const getOrganizationsShowQueryKey = (organization: string,) => {
    return [
    `/v1/organizations/${organization}`
    ] as const;
    }

    
export const getOrganizationsShowQueryOptions = <TData = Awaited<ReturnType<typeof organizationsShow>>, TError = AuthenticationExceptionResponse | AuthorizationExceptionResponse | ModelNotFoundExceptionResponse>(organization: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof organizationsShow>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getOrganizationsShowQueryKey(organization);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof organizationsShow>>> = ({ signal }) => organizationsShow(organization, { signal, ...requestOptions });

      

      

   return  { queryKey, queryFn, enabled: !!(organization), ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof organizationsShow>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type OrganizationsShowQueryResult = NonNullable<Awaited<ReturnType<typeof organizationsShow>>>
export type OrganizationsShowQueryError = AuthenticationExceptionResponse | AuthorizationExceptionResponse | ModelNotFoundExceptionResponse


export function useOrganizationsShow<TData = Awaited<ReturnType<typeof organizationsShow>>, TError = AuthenticationExceptionResponse | AuthorizationExceptionResponse | ModelNotFoundExceptionResponse>(
 organization: string, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof organizationsShow>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof organizationsShow>>,
          TError,
          Awaited<ReturnType<typeof organizationsShow>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useOrganizationsShow<TData = Awaited<ReturnType<typeof organizationsShow>>, TError = AuthenticationExceptionResponse | AuthorizationExceptionResponse | ModelNotFoundExceptionResponse>(
 organization: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof organizationsShow>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof organizationsShow>>,
          TError,
          Awaited<ReturnType<typeof organizationsShow>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useOrganizationsShow<TData = Awaited<ReturnType<typeof organizationsShow>>, TError = AuthenticationExceptionResponse | AuthorizationExceptionResponse | ModelNotFoundExceptionResponse>(
 organization: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof organizationsShow>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Display the specified organization
 */

export function useOrganizationsShow<TData = Awaited<ReturnType<typeof organizationsShow>>, TError = AuthenticationExceptionResponse | AuthorizationExceptionResponse | ModelNotFoundExceptionResponse>(
 organization: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof organizationsShow>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getOrganizationsShowQueryOptions(organization,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}




