{{-- Shared shell for every report PDF. DomPDF supports a limited CSS subset:
     no flexbox, no grid, no custom fonts without registration — hence tables
     for layout and the built-in DejaVu Sans stack. --}}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <title>{{ $title }}</title>
    <style>
        @page { margin: 28px 32px 52px 32px; }

        body {
            font-family: DejaVu Sans, sans-serif;
            font-size: 9.5px;
            color: #12121a;
            margin: 0;
        }

        /* ── masthead ── */
        .masthead { border-bottom: 2px solid #040273; padding-bottom: 10px; margin-bottom: 14px; }
        .masthead td { vertical-align: top; }
        .org { font-size: 15px; font-weight: bold; color: #040273; }
        .doc-title { font-size: 12px; font-weight: bold; margin-top: 2px; }
        .meta { font-size: 8.5px; color: #5c5c6b; line-height: 1.5; }
        .meta strong { color: #12121a; }

        /* ── section ── */
        h2 {
            font-size: 9px;
            text-transform: uppercase;
            letter-spacing: 0.08em;
            color: #5c5c6b;
            margin: 16px 0 6px;
            padding-bottom: 3px;
            border-bottom: 1px solid #e6e6ee;
        }

        /* ── figure tiles ── */
        .tiles { width: 100%; border-collapse: separate; border-spacing: 5px 0; margin-bottom: 4px; }
        .tile { background: #f7f7fa; padding: 7px 9px; width: 25%; }
        .tile .label { font-size: 7.5px; text-transform: uppercase; letter-spacing: 0.06em; color: #5c5c6b; }
        .tile .value { font-size: 12px; font-weight: bold; margin-top: 2px; }

        /* ── data table ── */
        table.data { width: 100%; border-collapse: collapse; }
        table.data th {
            text-align: left;
            font-size: 7.5px;
            text-transform: uppercase;
            letter-spacing: 0.06em;
            color: #5c5c6b;
            border-bottom: 1.2px solid #c9c9d8;
            padding: 5px 6px;
        }
        table.data td { padding: 5px 6px; border-bottom: 1px solid #eeeef4; }
        table.data tr.total td {
            border-top: 1.2px solid #12121a;
            border-bottom: none;
            font-weight: bold;
            background: #f7f7fa;
        }
        .num { text-align: right; }
        .neg { color: #bf0a30; font-weight: bold; }
        .pos { color: #046c4e; }
        .muted { color: #5c5c6b; }
        .empty { padding: 14px; text-align: center; color: #5c5c6b; background: #f7f7fa; }

        .pill {
            display: inline-block;
            padding: 1px 5px;
            font-size: 7.5px;
            font-weight: bold;
            text-transform: uppercase;
        }
        .pill-ok { background: #e6f4ef; color: #046c4e; }
        .pill-warn { background: #fdf2dd; color: #8a5a00; }
        .pill-bad { background: #fceaee; color: #bf0a30; }

        /* ── footer on every page ── */
        .footer {
            position: fixed;
            bottom: -34px;
            left: 0;
            right: 0;
            font-size: 7.5px;
            color: #8b8b99;
            border-top: 1px solid #e6e6ee;
            padding-top: 5px;
        }
        .footer td { width: 50%; }
    </style>
</head>
<body>

<table class="masthead" width="100%">
    <tr>
        <td>
            <div class="org">{{ $organization }}</div>
            <div class="doc-title">{{ $title }}</div>
        </td>
        <td class="meta" align="right">
            <strong>{{ $subtitle }}</strong><br>
            Station: {{ $station }}<br>
            Generated {{ $generatedAt }}<br>
            By {{ $generatedBy }}
        </td>
    </tr>
</table>

@yield('content')

<table class="footer">
    <tr>
        <td>{{ $organization }} &mdash; {{ $title }}</td>
        <td align="right">Generated by Petrol Integrity System</td>
    </tr>
</table>

</body>
</html>
