/**
 * Generated by orval v8.0.3 🍺
 * Do not edit manually.
 * Petrol Integrity System API Documentation
 * OpenAPI spec version: 0.0.1
 */
import {
  useMutation,
  useQuery
} from '@tanstack/react-query';
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  MutationFunction,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult
} from '@tanstack/react-query';

import type {
  AuthenticationExceptionResponse,
  AuthorizationExceptionResponse,
  ModelNotFoundExceptionResponse,
  ProductsDestroy200,
  ProductsDestroy422,
  ProductsIndex200,
  ProductsShow200,
  ProductsStore200,
  ProductsUpdate200,
  StoreProductRequest,
  UpdateProductRequest,
  ValidationExceptionResponse
} from '.././model';

import { customInstance } from '../../../lib/axios';


type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];



/**
 * @summary List all products in the organization
 */
export type productsIndexResponse200 = {
  data: ProductsIndex200
  status: 200
}

export type productsIndexResponse401 = {
  data: AuthenticationExceptionResponse
  status: 401
}

export type productsIndexResponse403 = {
  data: AuthorizationExceptionResponse
  status: 403
}
    
export type productsIndexResponseSuccess = (productsIndexResponse200) & {
  headers: Headers;
};
export type productsIndexResponseError = (productsIndexResponse401 | productsIndexResponse403) & {
  headers: Headers;
};

export type productsIndexResponse = (productsIndexResponseSuccess | productsIndexResponseError)

export const getProductsIndexUrl = () => {


  

  return `/v1/products`
}

export const productsIndex = async ( options?: RequestInit): Promise<productsIndexResponse> => {
  
  return customInstance<productsIndexResponse>(getProductsIndexUrl(),
  {      
    ...options,
    method: 'GET'
    
    
  }
);}





export const getProductsIndexQueryKey = () => {
    return [
    `/v1/products`
    ] as const;
    }

    
export const getProductsIndexQueryOptions = <TData = Awaited<ReturnType<typeof productsIndex>>, TError = AuthenticationExceptionResponse | AuthorizationExceptionResponse>( options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof productsIndex>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getProductsIndexQueryKey();

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof productsIndex>>> = ({ signal }) => productsIndex({ signal, ...requestOptions });

      

      

   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof productsIndex>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type ProductsIndexQueryResult = NonNullable<Awaited<ReturnType<typeof productsIndex>>>
export type ProductsIndexQueryError = AuthenticationExceptionResponse | AuthorizationExceptionResponse


export function useProductsIndex<TData = Awaited<ReturnType<typeof productsIndex>>, TError = AuthenticationExceptionResponse | AuthorizationExceptionResponse>(
  options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof productsIndex>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof productsIndex>>,
          TError,
          Awaited<ReturnType<typeof productsIndex>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useProductsIndex<TData = Awaited<ReturnType<typeof productsIndex>>, TError = AuthenticationExceptionResponse | AuthorizationExceptionResponse>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof productsIndex>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof productsIndex>>,
          TError,
          Awaited<ReturnType<typeof productsIndex>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useProductsIndex<TData = Awaited<ReturnType<typeof productsIndex>>, TError = AuthenticationExceptionResponse | AuthorizationExceptionResponse>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof productsIndex>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary List all products in the organization
 */

export function useProductsIndex<TData = Awaited<ReturnType<typeof productsIndex>>, TError = AuthenticationExceptionResponse | AuthorizationExceptionResponse>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof productsIndex>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getProductsIndexQueryOptions(options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}




/**
 * @summary Create a new product
 */
export type productsStoreResponse200 = {
  data: ProductsStore200
  status: 200
}

export type productsStoreResponse401 = {
  data: AuthenticationExceptionResponse
  status: 401
}

export type productsStoreResponse403 = {
  data: AuthorizationExceptionResponse
  status: 403
}

export type productsStoreResponse422 = {
  data: ValidationExceptionResponse
  status: 422
}
    
export type productsStoreResponseSuccess = (productsStoreResponse200) & {
  headers: Headers;
};
export type productsStoreResponseError = (productsStoreResponse401 | productsStoreResponse403 | productsStoreResponse422) & {
  headers: Headers;
};

export type productsStoreResponse = (productsStoreResponseSuccess | productsStoreResponseError)

export const getProductsStoreUrl = () => {


  

  return `/v1/products`
}

export const productsStore = async (storeProductRequest: StoreProductRequest, options?: RequestInit): Promise<productsStoreResponse> => {
  
  return customInstance<productsStoreResponse>(getProductsStoreUrl(),
  {      
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(
      storeProductRequest,)
  }
);}




export const getProductsStoreMutationOptions = <TError = AuthenticationExceptionResponse | AuthorizationExceptionResponse | ValidationExceptionResponse,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof productsStore>>, TError,{data: StoreProductRequest}, TContext>, request?: SecondParameter<typeof customInstance>}
): UseMutationOptions<Awaited<ReturnType<typeof productsStore>>, TError,{data: StoreProductRequest}, TContext> => {

const mutationKey = ['productsStore'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof productsStore>>, {data: StoreProductRequest}> = (props) => {
          const {data} = props ?? {};

          return  productsStore(data,requestOptions)
        }



        


  return  { mutationFn, ...mutationOptions }}

    export type ProductsStoreMutationResult = NonNullable<Awaited<ReturnType<typeof productsStore>>>
    export type ProductsStoreMutationBody = StoreProductRequest
    export type ProductsStoreMutationError = AuthenticationExceptionResponse | AuthorizationExceptionResponse | ValidationExceptionResponse

    /**
 * @summary Create a new product
 */
export const useProductsStore = <TError = AuthenticationExceptionResponse | AuthorizationExceptionResponse | ValidationExceptionResponse,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof productsStore>>, TError,{data: StoreProductRequest}, TContext>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof productsStore>>,
        TError,
        {data: StoreProductRequest},
        TContext
      > => {
      return useMutation(getProductsStoreMutationOptions(options), queryClient);
    }
    /**
 * @summary Show a specific product
 */
export type productsShowResponse200 = {
  data: ProductsShow200
  status: 200
}

export type productsShowResponse401 = {
  data: AuthenticationExceptionResponse
  status: 401
}

export type productsShowResponse403 = {
  data: AuthorizationExceptionResponse
  status: 403
}

export type productsShowResponse404 = {
  data: ModelNotFoundExceptionResponse
  status: 404
}
    
export type productsShowResponseSuccess = (productsShowResponse200) & {
  headers: Headers;
};
export type productsShowResponseError = (productsShowResponse401 | productsShowResponse403 | productsShowResponse404) & {
  headers: Headers;
};

export type productsShowResponse = (productsShowResponseSuccess | productsShowResponseError)

export const getProductsShowUrl = (product: string,) => {


  

  return `/v1/products/${product}`
}

export const productsShow = async (product: string, options?: RequestInit): Promise<productsShowResponse> => {
  
  return customInstance<productsShowResponse>(getProductsShowUrl(product),
  {      
    ...options,
    method: 'GET'
    
    
  }
);}





export const getProductsShowQueryKey = (product: string,) => {
    return [
    `/v1/products/${product}`
    ] as const;
    }

    
export const getProductsShowQueryOptions = <TData = Awaited<ReturnType<typeof productsShow>>, TError = AuthenticationExceptionResponse | AuthorizationExceptionResponse | ModelNotFoundExceptionResponse>(product: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof productsShow>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getProductsShowQueryKey(product);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof productsShow>>> = ({ signal }) => productsShow(product, { signal, ...requestOptions });

      

      

   return  { queryKey, queryFn, enabled: !!(product), ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof productsShow>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type ProductsShowQueryResult = NonNullable<Awaited<ReturnType<typeof productsShow>>>
export type ProductsShowQueryError = AuthenticationExceptionResponse | AuthorizationExceptionResponse | ModelNotFoundExceptionResponse


export function useProductsShow<TData = Awaited<ReturnType<typeof productsShow>>, TError = AuthenticationExceptionResponse | AuthorizationExceptionResponse | ModelNotFoundExceptionResponse>(
 product: string, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof productsShow>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof productsShow>>,
          TError,
          Awaited<ReturnType<typeof productsShow>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useProductsShow<TData = Awaited<ReturnType<typeof productsShow>>, TError = AuthenticationExceptionResponse | AuthorizationExceptionResponse | ModelNotFoundExceptionResponse>(
 product: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof productsShow>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof productsShow>>,
          TError,
          Awaited<ReturnType<typeof productsShow>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useProductsShow<TData = Awaited<ReturnType<typeof productsShow>>, TError = AuthenticationExceptionResponse | AuthorizationExceptionResponse | ModelNotFoundExceptionResponse>(
 product: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof productsShow>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Show a specific product
 */

export function useProductsShow<TData = Awaited<ReturnType<typeof productsShow>>, TError = AuthenticationExceptionResponse | AuthorizationExceptionResponse | ModelNotFoundExceptionResponse>(
 product: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof productsShow>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getProductsShowQueryOptions(product,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}




/**
 * @summary Update a product (Price changes are logged by ActivityLog)
 */
export type productsUpdateResponse200 = {
  data: ProductsUpdate200
  status: 200
}

export type productsUpdateResponse401 = {
  data: AuthenticationExceptionResponse
  status: 401
}

export type productsUpdateResponse403 = {
  data: AuthorizationExceptionResponse
  status: 403
}

export type productsUpdateResponse404 = {
  data: ModelNotFoundExceptionResponse
  status: 404
}

export type productsUpdateResponse422 = {
  data: ValidationExceptionResponse
  status: 422
}
    
export type productsUpdateResponseSuccess = (productsUpdateResponse200) & {
  headers: Headers;
};
export type productsUpdateResponseError = (productsUpdateResponse401 | productsUpdateResponse403 | productsUpdateResponse404 | productsUpdateResponse422) & {
  headers: Headers;
};

export type productsUpdateResponse = (productsUpdateResponseSuccess | productsUpdateResponseError)

export const getProductsUpdateUrl = (product: string,) => {


  

  return `/v1/products/${product}`
}

export const productsUpdate = async (product: string,
    updateProductRequest: UpdateProductRequest, options?: RequestInit): Promise<productsUpdateResponse> => {
  
  return customInstance<productsUpdateResponse>(getProductsUpdateUrl(product),
  {      
    ...options,
    method: 'PUT',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(
      updateProductRequest,)
  }
);}




export const getProductsUpdateMutationOptions = <TError = AuthenticationExceptionResponse | AuthorizationExceptionResponse | ModelNotFoundExceptionResponse | ValidationExceptionResponse,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof productsUpdate>>, TError,{product: string;data: UpdateProductRequest}, TContext>, request?: SecondParameter<typeof customInstance>}
): UseMutationOptions<Awaited<ReturnType<typeof productsUpdate>>, TError,{product: string;data: UpdateProductRequest}, TContext> => {

const mutationKey = ['productsUpdate'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof productsUpdate>>, {product: string;data: UpdateProductRequest}> = (props) => {
          const {product,data} = props ?? {};

          return  productsUpdate(product,data,requestOptions)
        }



        


  return  { mutationFn, ...mutationOptions }}

    export type ProductsUpdateMutationResult = NonNullable<Awaited<ReturnType<typeof productsUpdate>>>
    export type ProductsUpdateMutationBody = UpdateProductRequest
    export type ProductsUpdateMutationError = AuthenticationExceptionResponse | AuthorizationExceptionResponse | ModelNotFoundExceptionResponse | ValidationExceptionResponse

    /**
 * @summary Update a product (Price changes are logged by ActivityLog)
 */
export const useProductsUpdate = <TError = AuthenticationExceptionResponse | AuthorizationExceptionResponse | ModelNotFoundExceptionResponse | ValidationExceptionResponse,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof productsUpdate>>, TError,{product: string;data: UpdateProductRequest}, TContext>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof productsUpdate>>,
        TError,
        {product: string;data: UpdateProductRequest},
        TContext
      > => {
      return useMutation(getProductsUpdateMutationOptions(options), queryClient);
    }
    /**
 * @summary Delete a product
 */
export type productsDestroyResponse200 = {
  data: ProductsDestroy200
  status: 200
}

export type productsDestroyResponse401 = {
  data: AuthenticationExceptionResponse
  status: 401
}

export type productsDestroyResponse403 = {
  data: AuthorizationExceptionResponse
  status: 403
}

export type productsDestroyResponse404 = {
  data: ModelNotFoundExceptionResponse
  status: 404
}

export type productsDestroyResponse422 = {
  data: ProductsDestroy422
  status: 422
}
    
export type productsDestroyResponseSuccess = (productsDestroyResponse200) & {
  headers: Headers;
};
export type productsDestroyResponseError = (productsDestroyResponse401 | productsDestroyResponse403 | productsDestroyResponse404 | productsDestroyResponse422) & {
  headers: Headers;
};

export type productsDestroyResponse = (productsDestroyResponseSuccess | productsDestroyResponseError)

export const getProductsDestroyUrl = (product: string,) => {


  

  return `/v1/products/${product}`
}

export const productsDestroy = async (product: string, options?: RequestInit): Promise<productsDestroyResponse> => {
  
  return customInstance<productsDestroyResponse>(getProductsDestroyUrl(product),
  {      
    ...options,
    method: 'DELETE'
    
    
  }
);}




export const getProductsDestroyMutationOptions = <TError = AuthenticationExceptionResponse | AuthorizationExceptionResponse | ModelNotFoundExceptionResponse | ProductsDestroy422,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof productsDestroy>>, TError,{product: string}, TContext>, request?: SecondParameter<typeof customInstance>}
): UseMutationOptions<Awaited<ReturnType<typeof productsDestroy>>, TError,{product: string}, TContext> => {

const mutationKey = ['productsDestroy'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof productsDestroy>>, {product: string}> = (props) => {
          const {product} = props ?? {};

          return  productsDestroy(product,requestOptions)
        }



        


  return  { mutationFn, ...mutationOptions }}

    export type ProductsDestroyMutationResult = NonNullable<Awaited<ReturnType<typeof productsDestroy>>>
    
    export type ProductsDestroyMutationError = AuthenticationExceptionResponse | AuthorizationExceptionResponse | ModelNotFoundExceptionResponse | ProductsDestroy422

    /**
 * @summary Delete a product
 */
export const useProductsDestroy = <TError = AuthenticationExceptionResponse | AuthorizationExceptionResponse | ModelNotFoundExceptionResponse | ProductsDestroy422,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof productsDestroy>>, TError,{product: string}, TContext>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof productsDestroy>>,
        TError,
        {product: string},
        TContext
      > => {
      return useMutation(getProductsDestroyMutationOptions(options), queryClient);
    }
    