/**
 * Generated by orval v8.2.0 🍺
 * Do not edit manually.
 * Petrol Integrity System API Documentation
 * OpenAPI spec version: 0.0.1
 */
import {
  useMutation,
  useQuery
} from '@tanstack/react-query';
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  MutationFunction,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult
} from '@tanstack/react-query';

import type {
  AuthenticationExceptionResponse,
  AuthorizationExceptionResponse,
  CustomersDestroy200,
  CustomersIndex200,
  CustomersShow200,
  CustomersStore200,
  CustomersUpdate200,
  ModelNotFoundExceptionResponse,
  StoreCustomerRequest,
  UpdateCustomerRequest,
  ValidationExceptionResponse
} from '.././model';

import { customInstance } from '../../../lib/axios';


type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];



/**
 * @summary List Customers
Supports ?search=John for finding customers during a sale
 */
export type customersIndexResponse200 = {
  data: CustomersIndex200
  status: 200
}

export type customersIndexResponse401 = {
  data: AuthenticationExceptionResponse
  status: 401
}
    
export type customersIndexResponseSuccess = (customersIndexResponse200) & {
  headers: Headers;
};
export type customersIndexResponseError = (customersIndexResponse401) & {
  headers: Headers;
};

export type customersIndexResponse = (customersIndexResponseSuccess | customersIndexResponseError)

export const getCustomersIndexUrl = () => {


  

  return `/v1/customers`
}

export const customersIndex = async ( options?: RequestInit): Promise<customersIndexResponse> => {
  
  return customInstance<customersIndexResponse>(getCustomersIndexUrl(),
  {      
    ...options,
    method: 'GET'
    
    
  }
);}





export const getCustomersIndexQueryKey = () => {
    return [
    `/v1/customers`
    ] as const;
    }

    
export const getCustomersIndexQueryOptions = <TData = Awaited<ReturnType<typeof customersIndex>>, TError = AuthenticationExceptionResponse>( options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof customersIndex>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getCustomersIndexQueryKey();

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof customersIndex>>> = ({ signal }) => customersIndex({ signal, ...requestOptions });

      

      

   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof customersIndex>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type CustomersIndexQueryResult = NonNullable<Awaited<ReturnType<typeof customersIndex>>>
export type CustomersIndexQueryError = AuthenticationExceptionResponse


export function useCustomersIndex<TData = Awaited<ReturnType<typeof customersIndex>>, TError = AuthenticationExceptionResponse>(
  options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof customersIndex>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof customersIndex>>,
          TError,
          Awaited<ReturnType<typeof customersIndex>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useCustomersIndex<TData = Awaited<ReturnType<typeof customersIndex>>, TError = AuthenticationExceptionResponse>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof customersIndex>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof customersIndex>>,
          TError,
          Awaited<ReturnType<typeof customersIndex>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useCustomersIndex<TData = Awaited<ReturnType<typeof customersIndex>>, TError = AuthenticationExceptionResponse>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof customersIndex>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary List Customers
Supports ?search=John for finding customers during a sale
 */

export function useCustomersIndex<TData = Awaited<ReturnType<typeof customersIndex>>, TError = AuthenticationExceptionResponse>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof customersIndex>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getCustomersIndexQueryOptions(options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}




/**
 * @summary Store a new Customer
 */
export type customersStoreResponse200 = {
  data: CustomersStore200
  status: 200
}

export type customersStoreResponse401 = {
  data: AuthenticationExceptionResponse
  status: 401
}

export type customersStoreResponse403 = {
  data: AuthorizationExceptionResponse
  status: 403
}

export type customersStoreResponse422 = {
  data: ValidationExceptionResponse
  status: 422
}
    
export type customersStoreResponseSuccess = (customersStoreResponse200) & {
  headers: Headers;
};
export type customersStoreResponseError = (customersStoreResponse401 | customersStoreResponse403 | customersStoreResponse422) & {
  headers: Headers;
};

export type customersStoreResponse = (customersStoreResponseSuccess | customersStoreResponseError)

export const getCustomersStoreUrl = () => {


  

  return `/v1/customers`
}

export const customersStore = async (storeCustomerRequest: StoreCustomerRequest, options?: RequestInit): Promise<customersStoreResponse> => {
  
  return customInstance<customersStoreResponse>(getCustomersStoreUrl(),
  {      
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(
      storeCustomerRequest,)
  }
);}




export const getCustomersStoreMutationOptions = <TError = AuthenticationExceptionResponse | AuthorizationExceptionResponse | ValidationExceptionResponse,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof customersStore>>, TError,{data: StoreCustomerRequest}, TContext>, request?: SecondParameter<typeof customInstance>}
): UseMutationOptions<Awaited<ReturnType<typeof customersStore>>, TError,{data: StoreCustomerRequest}, TContext> => {

const mutationKey = ['customersStore'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof customersStore>>, {data: StoreCustomerRequest}> = (props) => {
          const {data} = props ?? {};

          return  customersStore(data,requestOptions)
        }



        


  return  { mutationFn, ...mutationOptions }}

    export type CustomersStoreMutationResult = NonNullable<Awaited<ReturnType<typeof customersStore>>>
    export type CustomersStoreMutationBody = StoreCustomerRequest
    export type CustomersStoreMutationError = AuthenticationExceptionResponse | AuthorizationExceptionResponse | ValidationExceptionResponse

    /**
 * @summary Store a new Customer
 */
export const useCustomersStore = <TError = AuthenticationExceptionResponse | AuthorizationExceptionResponse | ValidationExceptionResponse,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof customersStore>>, TError,{data: StoreCustomerRequest}, TContext>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof customersStore>>,
        TError,
        {data: StoreCustomerRequest},
        TContext
      > => {
      return useMutation(getCustomersStoreMutationOptions(options), queryClient);
    }
    /**
 * @summary Show a specific customer
 */
export type customersShowResponse200 = {
  data: CustomersShow200
  status: 200
}

export type customersShowResponse401 = {
  data: AuthenticationExceptionResponse
  status: 401
}

export type customersShowResponse403 = {
  data: AuthorizationExceptionResponse
  status: 403
}

export type customersShowResponse404 = {
  data: ModelNotFoundExceptionResponse
  status: 404
}
    
export type customersShowResponseSuccess = (customersShowResponse200) & {
  headers: Headers;
};
export type customersShowResponseError = (customersShowResponse401 | customersShowResponse403 | customersShowResponse404) & {
  headers: Headers;
};

export type customersShowResponse = (customersShowResponseSuccess | customersShowResponseError)

export const getCustomersShowUrl = (customer: string,) => {


  

  return `/v1/customers/${customer}`
}

export const customersShow = async (customer: string, options?: RequestInit): Promise<customersShowResponse> => {
  
  return customInstance<customersShowResponse>(getCustomersShowUrl(customer),
  {      
    ...options,
    method: 'GET'
    
    
  }
);}





export const getCustomersShowQueryKey = (customer: string,) => {
    return [
    `/v1/customers/${customer}`
    ] as const;
    }

    
export const getCustomersShowQueryOptions = <TData = Awaited<ReturnType<typeof customersShow>>, TError = AuthenticationExceptionResponse | AuthorizationExceptionResponse | ModelNotFoundExceptionResponse>(customer: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof customersShow>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getCustomersShowQueryKey(customer);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof customersShow>>> = ({ signal }) => customersShow(customer, { signal, ...requestOptions });

      

      

   return  { queryKey, queryFn, enabled: !!(customer), ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof customersShow>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type CustomersShowQueryResult = NonNullable<Awaited<ReturnType<typeof customersShow>>>
export type CustomersShowQueryError = AuthenticationExceptionResponse | AuthorizationExceptionResponse | ModelNotFoundExceptionResponse


export function useCustomersShow<TData = Awaited<ReturnType<typeof customersShow>>, TError = AuthenticationExceptionResponse | AuthorizationExceptionResponse | ModelNotFoundExceptionResponse>(
 customer: string, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof customersShow>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof customersShow>>,
          TError,
          Awaited<ReturnType<typeof customersShow>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useCustomersShow<TData = Awaited<ReturnType<typeof customersShow>>, TError = AuthenticationExceptionResponse | AuthorizationExceptionResponse | ModelNotFoundExceptionResponse>(
 customer: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof customersShow>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof customersShow>>,
          TError,
          Awaited<ReturnType<typeof customersShow>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useCustomersShow<TData = Awaited<ReturnType<typeof customersShow>>, TError = AuthenticationExceptionResponse | AuthorizationExceptionResponse | ModelNotFoundExceptionResponse>(
 customer: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof customersShow>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Show a specific customer
 */

export function useCustomersShow<TData = Awaited<ReturnType<typeof customersShow>>, TError = AuthenticationExceptionResponse | AuthorizationExceptionResponse | ModelNotFoundExceptionResponse>(
 customer: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof customersShow>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getCustomersShowQueryOptions(customer,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}




/**
 * @summary Update Customer details
 */
export type customersUpdateResponse200 = {
  data: CustomersUpdate200
  status: 200
}

export type customersUpdateResponse401 = {
  data: AuthenticationExceptionResponse
  status: 401
}

export type customersUpdateResponse403 = {
  data: AuthorizationExceptionResponse
  status: 403
}

export type customersUpdateResponse404 = {
  data: ModelNotFoundExceptionResponse
  status: 404
}

export type customersUpdateResponse422 = {
  data: ValidationExceptionResponse
  status: 422
}
    
export type customersUpdateResponseSuccess = (customersUpdateResponse200) & {
  headers: Headers;
};
export type customersUpdateResponseError = (customersUpdateResponse401 | customersUpdateResponse403 | customersUpdateResponse404 | customersUpdateResponse422) & {
  headers: Headers;
};

export type customersUpdateResponse = (customersUpdateResponseSuccess | customersUpdateResponseError)

export const getCustomersUpdateUrl = (customer: string,) => {


  

  return `/v1/customers/${customer}`
}

export const customersUpdate = async (customer: string,
    updateCustomerRequest: UpdateCustomerRequest, options?: RequestInit): Promise<customersUpdateResponse> => {
  
  return customInstance<customersUpdateResponse>(getCustomersUpdateUrl(customer),
  {      
    ...options,
    method: 'PUT',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(
      updateCustomerRequest,)
  }
);}




export const getCustomersUpdateMutationOptions = <TError = AuthenticationExceptionResponse | AuthorizationExceptionResponse | ModelNotFoundExceptionResponse | ValidationExceptionResponse,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof customersUpdate>>, TError,{customer: string;data: UpdateCustomerRequest}, TContext>, request?: SecondParameter<typeof customInstance>}
): UseMutationOptions<Awaited<ReturnType<typeof customersUpdate>>, TError,{customer: string;data: UpdateCustomerRequest}, TContext> => {

const mutationKey = ['customersUpdate'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof customersUpdate>>, {customer: string;data: UpdateCustomerRequest}> = (props) => {
          const {customer,data} = props ?? {};

          return  customersUpdate(customer,data,requestOptions)
        }



        


  return  { mutationFn, ...mutationOptions }}

    export type CustomersUpdateMutationResult = NonNullable<Awaited<ReturnType<typeof customersUpdate>>>
    export type CustomersUpdateMutationBody = UpdateCustomerRequest
    export type CustomersUpdateMutationError = AuthenticationExceptionResponse | AuthorizationExceptionResponse | ModelNotFoundExceptionResponse | ValidationExceptionResponse

    /**
 * @summary Update Customer details
 */
export const useCustomersUpdate = <TError = AuthenticationExceptionResponse | AuthorizationExceptionResponse | ModelNotFoundExceptionResponse | ValidationExceptionResponse,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof customersUpdate>>, TError,{customer: string;data: UpdateCustomerRequest}, TContext>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof customersUpdate>>,
        TError,
        {customer: string;data: UpdateCustomerRequest},
        TContext
      > => {
      return useMutation(getCustomersUpdateMutationOptions(options), queryClient);
    }
    /**
 * @summary Delete a customer
 */
export type customersDestroyResponse200 = {
  data: CustomersDestroy200
  status: 200
}

export type customersDestroyResponse401 = {
  data: AuthenticationExceptionResponse
  status: 401
}

export type customersDestroyResponse403 = {
  data: AuthorizationExceptionResponse
  status: 403
}

export type customersDestroyResponse404 = {
  data: ModelNotFoundExceptionResponse
  status: 404
}
    
export type customersDestroyResponseSuccess = (customersDestroyResponse200) & {
  headers: Headers;
};
export type customersDestroyResponseError = (customersDestroyResponse401 | customersDestroyResponse403 | customersDestroyResponse404) & {
  headers: Headers;
};

export type customersDestroyResponse = (customersDestroyResponseSuccess | customersDestroyResponseError)

export const getCustomersDestroyUrl = (customer: string,) => {


  

  return `/v1/customers/${customer}`
}

export const customersDestroy = async (customer: string, options?: RequestInit): Promise<customersDestroyResponse> => {
  
  return customInstance<customersDestroyResponse>(getCustomersDestroyUrl(customer),
  {      
    ...options,
    method: 'DELETE'
    
    
  }
);}




export const getCustomersDestroyMutationOptions = <TError = AuthenticationExceptionResponse | AuthorizationExceptionResponse | ModelNotFoundExceptionResponse,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof customersDestroy>>, TError,{customer: string}, TContext>, request?: SecondParameter<typeof customInstance>}
): UseMutationOptions<Awaited<ReturnType<typeof customersDestroy>>, TError,{customer: string}, TContext> => {

const mutationKey = ['customersDestroy'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof customersDestroy>>, {customer: string}> = (props) => {
          const {customer} = props ?? {};

          return  customersDestroy(customer,requestOptions)
        }



        


  return  { mutationFn, ...mutationOptions }}

    export type CustomersDestroyMutationResult = NonNullable<Awaited<ReturnType<typeof customersDestroy>>>
    
    export type CustomersDestroyMutationError = AuthenticationExceptionResponse | AuthorizationExceptionResponse | ModelNotFoundExceptionResponse

    /**
 * @summary Delete a customer
 */
export const useCustomersDestroy = <TError = AuthenticationExceptionResponse | AuthorizationExceptionResponse | ModelNotFoundExceptionResponse,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof customersDestroy>>, TError,{customer: string}, TContext>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof customersDestroy>>,
        TError,
        {customer: string},
        TContext
      > => {
      return useMutation(getCustomersDestroyMutationOptions(options), queryClient);
    }
    