/**
 * Generated by orval v8.0.3 🍺
 * Do not edit manually.
 * Petrol Integrity System API Documentation
 * OpenAPI spec version: 0.0.1
 */
import {
  useQuery
} from '@tanstack/react-query';
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseQueryOptions,
  UseQueryResult
} from '@tanstack/react-query';

import type {
  AuthenticationExceptionResponse,
  ReportDebtAging200,
  ReportPl200,
  ReportPlParams,
  ReportTaxSummary200,
  ReportTaxSummaryParams,
  ReportVarianceTrend200
} from '.././model';

import { customInstance } from '../../../lib/axios';


type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];



/**
 * @summary Debt Aging Report
 */
export type reportDebtAgingResponse200 = {
  data: ReportDebtAging200
  status: 200
}

export type reportDebtAgingResponse401 = {
  data: AuthenticationExceptionResponse
  status: 401
}
    
export type reportDebtAgingResponseSuccess = (reportDebtAgingResponse200) & {
  headers: Headers;
};
export type reportDebtAgingResponseError = (reportDebtAgingResponse401) & {
  headers: Headers;
};

export type reportDebtAgingResponse = (reportDebtAgingResponseSuccess | reportDebtAgingResponseError)

export const getReportDebtAgingUrl = () => {


  

  return `/v1/reports/debt-aging`
}

export const reportDebtAging = async ( options?: RequestInit): Promise<reportDebtAgingResponse> => {
  
  return customInstance<reportDebtAgingResponse>(getReportDebtAgingUrl(),
  {      
    ...options,
    method: 'GET'
    
    
  }
);}





export const getReportDebtAgingQueryKey = () => {
    return [
    `/v1/reports/debt-aging`
    ] as const;
    }

    
export const getReportDebtAgingQueryOptions = <TData = Awaited<ReturnType<typeof reportDebtAging>>, TError = AuthenticationExceptionResponse>( options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof reportDebtAging>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getReportDebtAgingQueryKey();

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof reportDebtAging>>> = ({ signal }) => reportDebtAging({ signal, ...requestOptions });

      

      

   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof reportDebtAging>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type ReportDebtAgingQueryResult = NonNullable<Awaited<ReturnType<typeof reportDebtAging>>>
export type ReportDebtAgingQueryError = AuthenticationExceptionResponse


export function useReportDebtAging<TData = Awaited<ReturnType<typeof reportDebtAging>>, TError = AuthenticationExceptionResponse>(
  options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof reportDebtAging>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof reportDebtAging>>,
          TError,
          Awaited<ReturnType<typeof reportDebtAging>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useReportDebtAging<TData = Awaited<ReturnType<typeof reportDebtAging>>, TError = AuthenticationExceptionResponse>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof reportDebtAging>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof reportDebtAging>>,
          TError,
          Awaited<ReturnType<typeof reportDebtAging>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useReportDebtAging<TData = Awaited<ReturnType<typeof reportDebtAging>>, TError = AuthenticationExceptionResponse>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof reportDebtAging>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Debt Aging Report
 */

export function useReportDebtAging<TData = Awaited<ReturnType<typeof reportDebtAging>>, TError = AuthenticationExceptionResponse>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof reportDebtAging>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getReportDebtAgingQueryOptions(options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}




/**
 * @summary Profit & Loss Report
 */
export type reportPlResponse200 = {
  data: ReportPl200
  status: 200
}

export type reportPlResponse401 = {
  data: AuthenticationExceptionResponse
  status: 401
}
    
export type reportPlResponseSuccess = (reportPlResponse200) & {
  headers: Headers;
};
export type reportPlResponseError = (reportPlResponse401) & {
  headers: Headers;
};

export type reportPlResponse = (reportPlResponseSuccess | reportPlResponseError)

export const getReportPlUrl = (params?: ReportPlParams,) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {
    
    if (value !== undefined) {
      normalizedParams.append(key, value === null ? 'null' : value.toString())
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0 ? `/v1/reports/pl?${stringifiedParams}` : `/v1/reports/pl`
}

export const reportPl = async (params?: ReportPlParams, options?: RequestInit): Promise<reportPlResponse> => {
  
  return customInstance<reportPlResponse>(getReportPlUrl(params),
  {      
    ...options,
    method: 'GET'
    
    
  }
);}





export const getReportPlQueryKey = (params?: ReportPlParams,) => {
    return [
    `/v1/reports/pl`, ...(params ? [params] : [])
    ] as const;
    }

    
export const getReportPlQueryOptions = <TData = Awaited<ReturnType<typeof reportPl>>, TError = AuthenticationExceptionResponse>(params?: ReportPlParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof reportPl>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getReportPlQueryKey(params);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof reportPl>>> = ({ signal }) => reportPl(params, { signal, ...requestOptions });

      

      

   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof reportPl>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type ReportPlQueryResult = NonNullable<Awaited<ReturnType<typeof reportPl>>>
export type ReportPlQueryError = AuthenticationExceptionResponse


export function useReportPl<TData = Awaited<ReturnType<typeof reportPl>>, TError = AuthenticationExceptionResponse>(
 params: undefined |  ReportPlParams, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof reportPl>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof reportPl>>,
          TError,
          Awaited<ReturnType<typeof reportPl>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useReportPl<TData = Awaited<ReturnType<typeof reportPl>>, TError = AuthenticationExceptionResponse>(
 params?: ReportPlParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof reportPl>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof reportPl>>,
          TError,
          Awaited<ReturnType<typeof reportPl>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useReportPl<TData = Awaited<ReturnType<typeof reportPl>>, TError = AuthenticationExceptionResponse>(
 params?: ReportPlParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof reportPl>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Profit & Loss Report
 */

export function useReportPl<TData = Awaited<ReturnType<typeof reportPl>>, TError = AuthenticationExceptionResponse>(
 params?: ReportPlParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof reportPl>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getReportPlQueryOptions(params,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}




/**
 * @summary Tax Summary Report
 */
export type reportTaxSummaryResponse200 = {
  data: ReportTaxSummary200
  status: 200
}

export type reportTaxSummaryResponse401 = {
  data: AuthenticationExceptionResponse
  status: 401
}
    
export type reportTaxSummaryResponseSuccess = (reportTaxSummaryResponse200) & {
  headers: Headers;
};
export type reportTaxSummaryResponseError = (reportTaxSummaryResponse401) & {
  headers: Headers;
};

export type reportTaxSummaryResponse = (reportTaxSummaryResponseSuccess | reportTaxSummaryResponseError)

export const getReportTaxSummaryUrl = (params?: ReportTaxSummaryParams,) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {
    
    if (value !== undefined) {
      normalizedParams.append(key, value === null ? 'null' : value.toString())
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0 ? `/v1/reports/tax-summary?${stringifiedParams}` : `/v1/reports/tax-summary`
}

export const reportTaxSummary = async (params?: ReportTaxSummaryParams, options?: RequestInit): Promise<reportTaxSummaryResponse> => {
  
  return customInstance<reportTaxSummaryResponse>(getReportTaxSummaryUrl(params),
  {      
    ...options,
    method: 'GET'
    
    
  }
);}





export const getReportTaxSummaryQueryKey = (params?: ReportTaxSummaryParams,) => {
    return [
    `/v1/reports/tax-summary`, ...(params ? [params] : [])
    ] as const;
    }

    
export const getReportTaxSummaryQueryOptions = <TData = Awaited<ReturnType<typeof reportTaxSummary>>, TError = AuthenticationExceptionResponse>(params?: ReportTaxSummaryParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof reportTaxSummary>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getReportTaxSummaryQueryKey(params);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof reportTaxSummary>>> = ({ signal }) => reportTaxSummary(params, { signal, ...requestOptions });

      

      

   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof reportTaxSummary>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type ReportTaxSummaryQueryResult = NonNullable<Awaited<ReturnType<typeof reportTaxSummary>>>
export type ReportTaxSummaryQueryError = AuthenticationExceptionResponse


export function useReportTaxSummary<TData = Awaited<ReturnType<typeof reportTaxSummary>>, TError = AuthenticationExceptionResponse>(
 params: undefined |  ReportTaxSummaryParams, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof reportTaxSummary>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof reportTaxSummary>>,
          TError,
          Awaited<ReturnType<typeof reportTaxSummary>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useReportTaxSummary<TData = Awaited<ReturnType<typeof reportTaxSummary>>, TError = AuthenticationExceptionResponse>(
 params?: ReportTaxSummaryParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof reportTaxSummary>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof reportTaxSummary>>,
          TError,
          Awaited<ReturnType<typeof reportTaxSummary>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useReportTaxSummary<TData = Awaited<ReturnType<typeof reportTaxSummary>>, TError = AuthenticationExceptionResponse>(
 params?: ReportTaxSummaryParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof reportTaxSummary>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Tax Summary Report
 */

export function useReportTaxSummary<TData = Awaited<ReturnType<typeof reportTaxSummary>>, TError = AuthenticationExceptionResponse>(
 params?: ReportTaxSummaryParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof reportTaxSummary>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getReportTaxSummaryQueryOptions(params,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}




/**
 * @summary Variance Trend Report
 */
export type reportVarianceTrendResponse200 = {
  data: ReportVarianceTrend200
  status: 200
}

export type reportVarianceTrendResponse401 = {
  data: AuthenticationExceptionResponse
  status: 401
}
    
export type reportVarianceTrendResponseSuccess = (reportVarianceTrendResponse200) & {
  headers: Headers;
};
export type reportVarianceTrendResponseError = (reportVarianceTrendResponse401) & {
  headers: Headers;
};

export type reportVarianceTrendResponse = (reportVarianceTrendResponseSuccess | reportVarianceTrendResponseError)

export const getReportVarianceTrendUrl = () => {


  

  return `/v1/reports/variance-trend`
}

export const reportVarianceTrend = async ( options?: RequestInit): Promise<reportVarianceTrendResponse> => {
  
  return customInstance<reportVarianceTrendResponse>(getReportVarianceTrendUrl(),
  {      
    ...options,
    method: 'GET'
    
    
  }
);}





export const getReportVarianceTrendQueryKey = () => {
    return [
    `/v1/reports/variance-trend`
    ] as const;
    }

    
export const getReportVarianceTrendQueryOptions = <TData = Awaited<ReturnType<typeof reportVarianceTrend>>, TError = AuthenticationExceptionResponse>( options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof reportVarianceTrend>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getReportVarianceTrendQueryKey();

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof reportVarianceTrend>>> = ({ signal }) => reportVarianceTrend({ signal, ...requestOptions });

      

      

   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof reportVarianceTrend>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type ReportVarianceTrendQueryResult = NonNullable<Awaited<ReturnType<typeof reportVarianceTrend>>>
export type ReportVarianceTrendQueryError = AuthenticationExceptionResponse


export function useReportVarianceTrend<TData = Awaited<ReturnType<typeof reportVarianceTrend>>, TError = AuthenticationExceptionResponse>(
  options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof reportVarianceTrend>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof reportVarianceTrend>>,
          TError,
          Awaited<ReturnType<typeof reportVarianceTrend>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useReportVarianceTrend<TData = Awaited<ReturnType<typeof reportVarianceTrend>>, TError = AuthenticationExceptionResponse>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof reportVarianceTrend>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof reportVarianceTrend>>,
          TError,
          Awaited<ReturnType<typeof reportVarianceTrend>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useReportVarianceTrend<TData = Awaited<ReturnType<typeof reportVarianceTrend>>, TError = AuthenticationExceptionResponse>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof reportVarianceTrend>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Variance Trend Report
 */

export function useReportVarianceTrend<TData = Awaited<ReturnType<typeof reportVarianceTrend>>, TError = AuthenticationExceptionResponse>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof reportVarianceTrend>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getReportVarianceTrendQueryOptions(options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}




