/**
 * Generated by orval v8.2.0 🍺
 * Do not edit manually.
 * Petrol Integrity System API Documentation
 * OpenAPI spec version: 0.0.1
 */
import {
  useQuery
} from '@tanstack/react-query';
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseQueryOptions,
  UseQueryResult
} from '@tanstack/react-query';

import type {
  AuditLogIndex200,
  AuthenticationExceptionResponse
} from '.././model';

import { customInstance } from '../../../lib/axios';


type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];



/**
 * @summary Display audit logs according to the user role
 */
export type auditLogIndexResponse200 = {
  data: AuditLogIndex200
  status: 200
}

export type auditLogIndexResponse401 = {
  data: AuthenticationExceptionResponse
  status: 401
}
    
export type auditLogIndexResponseSuccess = (auditLogIndexResponse200) & {
  headers: Headers;
};
export type auditLogIndexResponseError = (auditLogIndexResponse401) & {
  headers: Headers;
};

export type auditLogIndexResponse = (auditLogIndexResponseSuccess | auditLogIndexResponseError)

export const getAuditLogIndexUrl = () => {


  

  return `/v1/audit-logs`
}

export const auditLogIndex = async ( options?: RequestInit): Promise<auditLogIndexResponse> => {
  
  return customInstance<auditLogIndexResponse>(getAuditLogIndexUrl(),
  {      
    ...options,
    method: 'GET'
    
    
  }
);}





export const getAuditLogIndexQueryKey = () => {
    return [
    `/v1/audit-logs`
    ] as const;
    }

    
export const getAuditLogIndexQueryOptions = <TData = Awaited<ReturnType<typeof auditLogIndex>>, TError = AuthenticationExceptionResponse>( options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof auditLogIndex>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getAuditLogIndexQueryKey();

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof auditLogIndex>>> = ({ signal }) => auditLogIndex({ signal, ...requestOptions });

      

      

   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof auditLogIndex>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type AuditLogIndexQueryResult = NonNullable<Awaited<ReturnType<typeof auditLogIndex>>>
export type AuditLogIndexQueryError = AuthenticationExceptionResponse


export function useAuditLogIndex<TData = Awaited<ReturnType<typeof auditLogIndex>>, TError = AuthenticationExceptionResponse>(
  options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof auditLogIndex>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof auditLogIndex>>,
          TError,
          Awaited<ReturnType<typeof auditLogIndex>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useAuditLogIndex<TData = Awaited<ReturnType<typeof auditLogIndex>>, TError = AuthenticationExceptionResponse>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof auditLogIndex>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof auditLogIndex>>,
          TError,
          Awaited<ReturnType<typeof auditLogIndex>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useAuditLogIndex<TData = Awaited<ReturnType<typeof auditLogIndex>>, TError = AuthenticationExceptionResponse>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof auditLogIndex>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Display audit logs according to the user role
 */

export function useAuditLogIndex<TData = Awaited<ReturnType<typeof auditLogIndex>>, TError = AuthenticationExceptionResponse>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof auditLogIndex>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getAuditLogIndexQueryOptions(options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}




