import type { TutorialStep } from '@/lib/tutorial/types';

export const ADMIN_TUTORIAL_STEPS: TutorialStep[] = [
    {
        id: 'admin_quick_stats',
        route: '/admin',
        targetId: 'admin-quick-stats',
        title: 'Quick Stats',
        description: 'Get a snapshot of stations, products, and tanks at a glance.',
        placement: 'bottom',
        offsetY: 28,
    },
    {
        id: 'admin_finance_tab',
        route: '/admin',
        targetId: 'admin-tab-finance',
        title: 'Finance',
        description: 'Review sales, shifts, and financial performance.',
        placement: 'top',
        offsetY: 34,
        spotlightPadding: 1,
        spotlightRadius: 8,
    },
    {
        id: 'admin_inventory_tab',
        route: '/admin',
        targetId: 'admin-tab-inventory',
        title: 'Inventory',
        description: 'Track liftings and stock movement across your stations.',
        placement: 'top',
        offsetY: 34,
        spotlightPadding: 1,
        spotlightRadius: 8,
    },
    {
        id: 'admin_infrastructure_tab',
        route: '/admin',
        targetId: 'admin-tab-infrastructure',
        title: 'Infrastructure',
        description: 'Manage stations, tanks, nozzles, products, and suppliers.',
        placement: 'top',
        offsetX: -10,
        offsetY: 34,
        spotlightPadding: 1,
        spotlightRadius: 8,
    },
    {
        id: 'admin_system_tab',
        route: '/admin',
        targetId: 'admin-tab-system',
        title: 'System',
        description: 'Configure settings and review operational requests.',
        placement: 'top',
        offsetY: 34,
        spotlightPadding: 1,
        spotlightRadius: 8,
    },
];

