/**
 * Generated by orval v8.0.3 🍺
 * Do not edit manually.
 * Petrol Integrity System API Documentation
 * OpenAPI spec version: 0.0.1
 */
import {
  useMutation,
  useQuery
} from '@tanstack/react-query';
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  MutationFunction,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult
} from '@tanstack/react-query';

import type {
  AuthenticationExceptionResponse,
  AuthorizationExceptionResponse,
  CreditorsIndex200,
  CreditorsShow200,
  CreditorsStore201,
  CreditorsUpdate200,
  ModelNotFoundExceptionResponse,
  StoreSupplierRequest,
  UpdateSupplierRequest,
  ValidationExceptionResponse
} from '.././model';

import { customInstance } from '../../../lib/axios';


type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];



/**
 * @summary Display a listing of the resource
 */
export type creditorsIndexResponse200 = {
  data: CreditorsIndex200
  status: 200
}

export type creditorsIndexResponse401 = {
  data: AuthenticationExceptionResponse
  status: 401
}

export type creditorsIndexResponse403 = {
  data: AuthorizationExceptionResponse
  status: 403
}
    
export type creditorsIndexResponseSuccess = (creditorsIndexResponse200) & {
  headers: Headers;
};
export type creditorsIndexResponseError = (creditorsIndexResponse401 | creditorsIndexResponse403) & {
  headers: Headers;
};

export type creditorsIndexResponse = (creditorsIndexResponseSuccess | creditorsIndexResponseError)

export const getCreditorsIndexUrl = () => {


  

  return `/v1/creditors`
}

export const creditorsIndex = async ( options?: RequestInit): Promise<creditorsIndexResponse> => {
  
  return customInstance<creditorsIndexResponse>(getCreditorsIndexUrl(),
  {      
    ...options,
    method: 'GET'
    
    
  }
);}





export const getCreditorsIndexQueryKey = () => {
    return [
    `/v1/creditors`
    ] as const;
    }

    
export const getCreditorsIndexQueryOptions = <TData = Awaited<ReturnType<typeof creditorsIndex>>, TError = AuthenticationExceptionResponse | AuthorizationExceptionResponse>( options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof creditorsIndex>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getCreditorsIndexQueryKey();

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof creditorsIndex>>> = ({ signal }) => creditorsIndex({ signal, ...requestOptions });

      

      

   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof creditorsIndex>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type CreditorsIndexQueryResult = NonNullable<Awaited<ReturnType<typeof creditorsIndex>>>
export type CreditorsIndexQueryError = AuthenticationExceptionResponse | AuthorizationExceptionResponse


export function useCreditorsIndex<TData = Awaited<ReturnType<typeof creditorsIndex>>, TError = AuthenticationExceptionResponse | AuthorizationExceptionResponse>(
  options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof creditorsIndex>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof creditorsIndex>>,
          TError,
          Awaited<ReturnType<typeof creditorsIndex>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useCreditorsIndex<TData = Awaited<ReturnType<typeof creditorsIndex>>, TError = AuthenticationExceptionResponse | AuthorizationExceptionResponse>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof creditorsIndex>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof creditorsIndex>>,
          TError,
          Awaited<ReturnType<typeof creditorsIndex>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useCreditorsIndex<TData = Awaited<ReturnType<typeof creditorsIndex>>, TError = AuthenticationExceptionResponse | AuthorizationExceptionResponse>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof creditorsIndex>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Display a listing of the resource
 */

export function useCreditorsIndex<TData = Awaited<ReturnType<typeof creditorsIndex>>, TError = AuthenticationExceptionResponse | AuthorizationExceptionResponse>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof creditorsIndex>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getCreditorsIndexQueryOptions(options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}




/**
 * @summary Store a newly created resource in storage
 */
export type creditorsStoreResponse201 = {
  data: CreditorsStore201
  status: 201
}

export type creditorsStoreResponse401 = {
  data: AuthenticationExceptionResponse
  status: 401
}

export type creditorsStoreResponse403 = {
  data: AuthorizationExceptionResponse
  status: 403
}

export type creditorsStoreResponse422 = {
  data: ValidationExceptionResponse
  status: 422
}
    
export type creditorsStoreResponseSuccess = (creditorsStoreResponse201) & {
  headers: Headers;
};
export type creditorsStoreResponseError = (creditorsStoreResponse401 | creditorsStoreResponse403 | creditorsStoreResponse422) & {
  headers: Headers;
};

export type creditorsStoreResponse = (creditorsStoreResponseSuccess | creditorsStoreResponseError)

export const getCreditorsStoreUrl = () => {


  

  return `/v1/creditors`
}

export const creditorsStore = async (storeSupplierRequest: StoreSupplierRequest, options?: RequestInit): Promise<creditorsStoreResponse> => {
  
  return customInstance<creditorsStoreResponse>(getCreditorsStoreUrl(),
  {      
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(
      storeSupplierRequest,)
  }
);}




export const getCreditorsStoreMutationOptions = <TError = AuthenticationExceptionResponse | AuthorizationExceptionResponse | ValidationExceptionResponse,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof creditorsStore>>, TError,{data: StoreSupplierRequest}, TContext>, request?: SecondParameter<typeof customInstance>}
): UseMutationOptions<Awaited<ReturnType<typeof creditorsStore>>, TError,{data: StoreSupplierRequest}, TContext> => {

const mutationKey = ['creditorsStore'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof creditorsStore>>, {data: StoreSupplierRequest}> = (props) => {
          const {data} = props ?? {};

          return  creditorsStore(data,requestOptions)
        }



        


  return  { mutationFn, ...mutationOptions }}

    export type CreditorsStoreMutationResult = NonNullable<Awaited<ReturnType<typeof creditorsStore>>>
    export type CreditorsStoreMutationBody = StoreSupplierRequest
    export type CreditorsStoreMutationError = AuthenticationExceptionResponse | AuthorizationExceptionResponse | ValidationExceptionResponse

    /**
 * @summary Store a newly created resource in storage
 */
export const useCreditorsStore = <TError = AuthenticationExceptionResponse | AuthorizationExceptionResponse | ValidationExceptionResponse,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof creditorsStore>>, TError,{data: StoreSupplierRequest}, TContext>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof creditorsStore>>,
        TError,
        {data: StoreSupplierRequest},
        TContext
      > => {
      return useMutation(getCreditorsStoreMutationOptions(options), queryClient);
    }
    /**
 * @summary Display the specified resource
 */
export type creditorsShowResponse200 = {
  data: CreditorsShow200
  status: 200
}

export type creditorsShowResponse401 = {
  data: AuthenticationExceptionResponse
  status: 401
}

export type creditorsShowResponse403 = {
  data: AuthorizationExceptionResponse
  status: 403
}

export type creditorsShowResponse404 = {
  data: ModelNotFoundExceptionResponse
  status: 404
}
    
export type creditorsShowResponseSuccess = (creditorsShowResponse200) & {
  headers: Headers;
};
export type creditorsShowResponseError = (creditorsShowResponse401 | creditorsShowResponse403 | creditorsShowResponse404) & {
  headers: Headers;
};

export type creditorsShowResponse = (creditorsShowResponseSuccess | creditorsShowResponseError)

export const getCreditorsShowUrl = (creditor: string,) => {


  

  return `/v1/creditors/${creditor}`
}

export const creditorsShow = async (creditor: string, options?: RequestInit): Promise<creditorsShowResponse> => {
  
  return customInstance<creditorsShowResponse>(getCreditorsShowUrl(creditor),
  {      
    ...options,
    method: 'GET'
    
    
  }
);}





export const getCreditorsShowQueryKey = (creditor: string,) => {
    return [
    `/v1/creditors/${creditor}`
    ] as const;
    }

    
export const getCreditorsShowQueryOptions = <TData = Awaited<ReturnType<typeof creditorsShow>>, TError = AuthenticationExceptionResponse | AuthorizationExceptionResponse | ModelNotFoundExceptionResponse>(creditor: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof creditorsShow>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getCreditorsShowQueryKey(creditor);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof creditorsShow>>> = ({ signal }) => creditorsShow(creditor, { signal, ...requestOptions });

      

      

   return  { queryKey, queryFn, enabled: !!(creditor), ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof creditorsShow>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type CreditorsShowQueryResult = NonNullable<Awaited<ReturnType<typeof creditorsShow>>>
export type CreditorsShowQueryError = AuthenticationExceptionResponse | AuthorizationExceptionResponse | ModelNotFoundExceptionResponse


export function useCreditorsShow<TData = Awaited<ReturnType<typeof creditorsShow>>, TError = AuthenticationExceptionResponse | AuthorizationExceptionResponse | ModelNotFoundExceptionResponse>(
 creditor: string, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof creditorsShow>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof creditorsShow>>,
          TError,
          Awaited<ReturnType<typeof creditorsShow>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useCreditorsShow<TData = Awaited<ReturnType<typeof creditorsShow>>, TError = AuthenticationExceptionResponse | AuthorizationExceptionResponse | ModelNotFoundExceptionResponse>(
 creditor: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof creditorsShow>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof creditorsShow>>,
          TError,
          Awaited<ReturnType<typeof creditorsShow>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useCreditorsShow<TData = Awaited<ReturnType<typeof creditorsShow>>, TError = AuthenticationExceptionResponse | AuthorizationExceptionResponse | ModelNotFoundExceptionResponse>(
 creditor: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof creditorsShow>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Display the specified resource
 */

export function useCreditorsShow<TData = Awaited<ReturnType<typeof creditorsShow>>, TError = AuthenticationExceptionResponse | AuthorizationExceptionResponse | ModelNotFoundExceptionResponse>(
 creditor: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof creditorsShow>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getCreditorsShowQueryOptions(creditor,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}




/**
 * @summary Update the specified resource in storage
 */
export type creditorsUpdateResponse200 = {
  data: CreditorsUpdate200
  status: 200
}

export type creditorsUpdateResponse401 = {
  data: AuthenticationExceptionResponse
  status: 401
}

export type creditorsUpdateResponse403 = {
  data: AuthorizationExceptionResponse
  status: 403
}

export type creditorsUpdateResponse404 = {
  data: ModelNotFoundExceptionResponse
  status: 404
}

export type creditorsUpdateResponse422 = {
  data: ValidationExceptionResponse
  status: 422
}
    
export type creditorsUpdateResponseSuccess = (creditorsUpdateResponse200) & {
  headers: Headers;
};
export type creditorsUpdateResponseError = (creditorsUpdateResponse401 | creditorsUpdateResponse403 | creditorsUpdateResponse404 | creditorsUpdateResponse422) & {
  headers: Headers;
};

export type creditorsUpdateResponse = (creditorsUpdateResponseSuccess | creditorsUpdateResponseError)

export const getCreditorsUpdateUrl = (creditor: string,) => {


  

  return `/v1/creditors/${creditor}`
}

export const creditorsUpdate = async (creditor: string,
    updateSupplierRequest: UpdateSupplierRequest, options?: RequestInit): Promise<creditorsUpdateResponse> => {
  
  return customInstance<creditorsUpdateResponse>(getCreditorsUpdateUrl(creditor),
  {      
    ...options,
    method: 'PUT',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(
      updateSupplierRequest,)
  }
);}




export const getCreditorsUpdateMutationOptions = <TError = AuthenticationExceptionResponse | AuthorizationExceptionResponse | ModelNotFoundExceptionResponse | ValidationExceptionResponse,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof creditorsUpdate>>, TError,{creditor: string;data: UpdateSupplierRequest}, TContext>, request?: SecondParameter<typeof customInstance>}
): UseMutationOptions<Awaited<ReturnType<typeof creditorsUpdate>>, TError,{creditor: string;data: UpdateSupplierRequest}, TContext> => {

const mutationKey = ['creditorsUpdate'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof creditorsUpdate>>, {creditor: string;data: UpdateSupplierRequest}> = (props) => {
          const {creditor,data} = props ?? {};

          return  creditorsUpdate(creditor,data,requestOptions)
        }



        


  return  { mutationFn, ...mutationOptions }}

    export type CreditorsUpdateMutationResult = NonNullable<Awaited<ReturnType<typeof creditorsUpdate>>>
    export type CreditorsUpdateMutationBody = UpdateSupplierRequest
    export type CreditorsUpdateMutationError = AuthenticationExceptionResponse | AuthorizationExceptionResponse | ModelNotFoundExceptionResponse | ValidationExceptionResponse

    /**
 * @summary Update the specified resource in storage
 */
export const useCreditorsUpdate = <TError = AuthenticationExceptionResponse | AuthorizationExceptionResponse | ModelNotFoundExceptionResponse | ValidationExceptionResponse,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof creditorsUpdate>>, TError,{creditor: string;data: UpdateSupplierRequest}, TContext>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof creditorsUpdate>>,
        TError,
        {creditor: string;data: UpdateSupplierRequest},
        TContext
      > => {
      return useMutation(getCreditorsUpdateMutationOptions(options), queryClient);
    }
    /**
 * @summary Remove the specified resource from storage
 */
export type creditorsDestroyResponse204 = {
  data: void
  status: 204
}

export type creditorsDestroyResponse401 = {
  data: AuthenticationExceptionResponse
  status: 401
}

export type creditorsDestroyResponse403 = {
  data: AuthorizationExceptionResponse
  status: 403
}

export type creditorsDestroyResponse404 = {
  data: ModelNotFoundExceptionResponse
  status: 404
}
    
export type creditorsDestroyResponseSuccess = (creditorsDestroyResponse204) & {
  headers: Headers;
};
export type creditorsDestroyResponseError = (creditorsDestroyResponse401 | creditorsDestroyResponse403 | creditorsDestroyResponse404) & {
  headers: Headers;
};

export type creditorsDestroyResponse = (creditorsDestroyResponseSuccess | creditorsDestroyResponseError)

export const getCreditorsDestroyUrl = (creditor: string,) => {


  

  return `/v1/creditors/${creditor}`
}

export const creditorsDestroy = async (creditor: string, options?: RequestInit): Promise<creditorsDestroyResponse> => {
  
  return customInstance<creditorsDestroyResponse>(getCreditorsDestroyUrl(creditor),
  {      
    ...options,
    method: 'DELETE'
    
    
  }
);}




export const getCreditorsDestroyMutationOptions = <TError = AuthenticationExceptionResponse | AuthorizationExceptionResponse | ModelNotFoundExceptionResponse,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof creditorsDestroy>>, TError,{creditor: string}, TContext>, request?: SecondParameter<typeof customInstance>}
): UseMutationOptions<Awaited<ReturnType<typeof creditorsDestroy>>, TError,{creditor: string}, TContext> => {

const mutationKey = ['creditorsDestroy'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof creditorsDestroy>>, {creditor: string}> = (props) => {
          const {creditor} = props ?? {};

          return  creditorsDestroy(creditor,requestOptions)
        }



        


  return  { mutationFn, ...mutationOptions }}

    export type CreditorsDestroyMutationResult = NonNullable<Awaited<ReturnType<typeof creditorsDestroy>>>
    
    export type CreditorsDestroyMutationError = AuthenticationExceptionResponse | AuthorizationExceptionResponse | ModelNotFoundExceptionResponse

    /**
 * @summary Remove the specified resource from storage
 */
export const useCreditorsDestroy = <TError = AuthenticationExceptionResponse | AuthorizationExceptionResponse | ModelNotFoundExceptionResponse,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof creditorsDestroy>>, TError,{creditor: string}, TContext>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof creditorsDestroy>>,
        TError,
        {creditor: string},
        TContext
      > => {
      return useMutation(getCreditorsDestroyMutationOptions(options), queryClient);
    }
    