/**
 * Generated by orval v8.0.3 🍺
 * Do not edit manually.
 * Petrol Integrity System API Documentation
 * OpenAPI spec version: 0.0.1
 */
import {
  useMutation,
  useQuery
} from '@tanstack/react-query';
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  MutationFunction,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult
} from '@tanstack/react-query';

import type {
  AuthenticationExceptionResponse,
  AuthorizationExceptionResponse,
  CreditSalesIndex200,
  CreditSalesShow200,
  CreditSalesStore201,
  ModelNotFoundExceptionResponse,
  StoreCreditSaleRequest,
  ValidationExceptionResponse
} from '.././model';

import { customInstance } from '../../../lib/axios';


type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];



/**
 * @summary Display a paginated list of credit sales
 */
export type creditSalesIndexResponse200 = {
  data: CreditSalesIndex200
  status: 200
}

export type creditSalesIndexResponse401 = {
  data: AuthenticationExceptionResponse
  status: 401
}

export type creditSalesIndexResponse403 = {
  data: AuthorizationExceptionResponse
  status: 403
}
    
export type creditSalesIndexResponseSuccess = (creditSalesIndexResponse200) & {
  headers: Headers;
};
export type creditSalesIndexResponseError = (creditSalesIndexResponse401 | creditSalesIndexResponse403) & {
  headers: Headers;
};

export type creditSalesIndexResponse = (creditSalesIndexResponseSuccess | creditSalesIndexResponseError)

export const getCreditSalesIndexUrl = () => {


  

  return `/v1/credit-sales`
}

export const creditSalesIndex = async ( options?: RequestInit): Promise<creditSalesIndexResponse> => {
  
  return customInstance<creditSalesIndexResponse>(getCreditSalesIndexUrl(),
  {      
    ...options,
    method: 'GET'
    
    
  }
);}





export const getCreditSalesIndexQueryKey = () => {
    return [
    `/v1/credit-sales`
    ] as const;
    }

    
export const getCreditSalesIndexQueryOptions = <TData = Awaited<ReturnType<typeof creditSalesIndex>>, TError = AuthenticationExceptionResponse | AuthorizationExceptionResponse>( options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof creditSalesIndex>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getCreditSalesIndexQueryKey();

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof creditSalesIndex>>> = ({ signal }) => creditSalesIndex({ signal, ...requestOptions });

      

      

   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof creditSalesIndex>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type CreditSalesIndexQueryResult = NonNullable<Awaited<ReturnType<typeof creditSalesIndex>>>
export type CreditSalesIndexQueryError = AuthenticationExceptionResponse | AuthorizationExceptionResponse


export function useCreditSalesIndex<TData = Awaited<ReturnType<typeof creditSalesIndex>>, TError = AuthenticationExceptionResponse | AuthorizationExceptionResponse>(
  options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof creditSalesIndex>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof creditSalesIndex>>,
          TError,
          Awaited<ReturnType<typeof creditSalesIndex>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useCreditSalesIndex<TData = Awaited<ReturnType<typeof creditSalesIndex>>, TError = AuthenticationExceptionResponse | AuthorizationExceptionResponse>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof creditSalesIndex>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof creditSalesIndex>>,
          TError,
          Awaited<ReturnType<typeof creditSalesIndex>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useCreditSalesIndex<TData = Awaited<ReturnType<typeof creditSalesIndex>>, TError = AuthenticationExceptionResponse | AuthorizationExceptionResponse>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof creditSalesIndex>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Display a paginated list of credit sales
 */

export function useCreditSalesIndex<TData = Awaited<ReturnType<typeof creditSalesIndex>>, TError = AuthenticationExceptionResponse | AuthorizationExceptionResponse>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof creditSalesIndex>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getCreditSalesIndexQueryOptions(options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}




/**
 * @summary Store a newly created credit sale
 */
export type creditSalesStoreResponse201 = {
  data: CreditSalesStore201
  status: 201
}

export type creditSalesStoreResponse401 = {
  data: AuthenticationExceptionResponse
  status: 401
}

export type creditSalesStoreResponse403 = {
  data: AuthorizationExceptionResponse
  status: 403
}

export type creditSalesStoreResponse422 = {
  data: ValidationExceptionResponse
  status: 422
}
    
export type creditSalesStoreResponseSuccess = (creditSalesStoreResponse201) & {
  headers: Headers;
};
export type creditSalesStoreResponseError = (creditSalesStoreResponse401 | creditSalesStoreResponse403 | creditSalesStoreResponse422) & {
  headers: Headers;
};

export type creditSalesStoreResponse = (creditSalesStoreResponseSuccess | creditSalesStoreResponseError)

export const getCreditSalesStoreUrl = () => {


  

  return `/v1/credit-sales`
}

export const creditSalesStore = async (storeCreditSaleRequest: StoreCreditSaleRequest, options?: RequestInit): Promise<creditSalesStoreResponse> => {
  
  return customInstance<creditSalesStoreResponse>(getCreditSalesStoreUrl(),
  {      
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(
      storeCreditSaleRequest,)
  }
);}




export const getCreditSalesStoreMutationOptions = <TError = AuthenticationExceptionResponse | AuthorizationExceptionResponse | ValidationExceptionResponse,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof creditSalesStore>>, TError,{data: StoreCreditSaleRequest}, TContext>, request?: SecondParameter<typeof customInstance>}
): UseMutationOptions<Awaited<ReturnType<typeof creditSalesStore>>, TError,{data: StoreCreditSaleRequest}, TContext> => {

const mutationKey = ['creditSalesStore'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof creditSalesStore>>, {data: StoreCreditSaleRequest}> = (props) => {
          const {data} = props ?? {};

          return  creditSalesStore(data,requestOptions)
        }



        


  return  { mutationFn, ...mutationOptions }}

    export type CreditSalesStoreMutationResult = NonNullable<Awaited<ReturnType<typeof creditSalesStore>>>
    export type CreditSalesStoreMutationBody = StoreCreditSaleRequest
    export type CreditSalesStoreMutationError = AuthenticationExceptionResponse | AuthorizationExceptionResponse | ValidationExceptionResponse

    /**
 * @summary Store a newly created credit sale
 */
export const useCreditSalesStore = <TError = AuthenticationExceptionResponse | AuthorizationExceptionResponse | ValidationExceptionResponse,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof creditSalesStore>>, TError,{data: StoreCreditSaleRequest}, TContext>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof creditSalesStore>>,
        TError,
        {data: StoreCreditSaleRequest},
        TContext
      > => {
      return useMutation(getCreditSalesStoreMutationOptions(options), queryClient);
    }
    /**
 * @summary Display the specified credit sale
 */
export type creditSalesShowResponse200 = {
  data: CreditSalesShow200
  status: 200
}

export type creditSalesShowResponse401 = {
  data: AuthenticationExceptionResponse
  status: 401
}

export type creditSalesShowResponse403 = {
  data: AuthorizationExceptionResponse
  status: 403
}

export type creditSalesShowResponse404 = {
  data: ModelNotFoundExceptionResponse
  status: 404
}
    
export type creditSalesShowResponseSuccess = (creditSalesShowResponse200) & {
  headers: Headers;
};
export type creditSalesShowResponseError = (creditSalesShowResponse401 | creditSalesShowResponse403 | creditSalesShowResponse404) & {
  headers: Headers;
};

export type creditSalesShowResponse = (creditSalesShowResponseSuccess | creditSalesShowResponseError)

export const getCreditSalesShowUrl = (creditSale: string,) => {


  

  return `/v1/credit-sales/${creditSale}`
}

export const creditSalesShow = async (creditSale: string, options?: RequestInit): Promise<creditSalesShowResponse> => {
  
  return customInstance<creditSalesShowResponse>(getCreditSalesShowUrl(creditSale),
  {      
    ...options,
    method: 'GET'
    
    
  }
);}





export const getCreditSalesShowQueryKey = (creditSale: string,) => {
    return [
    `/v1/credit-sales/${creditSale}`
    ] as const;
    }

    
export const getCreditSalesShowQueryOptions = <TData = Awaited<ReturnType<typeof creditSalesShow>>, TError = AuthenticationExceptionResponse | AuthorizationExceptionResponse | ModelNotFoundExceptionResponse>(creditSale: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof creditSalesShow>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getCreditSalesShowQueryKey(creditSale);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof creditSalesShow>>> = ({ signal }) => creditSalesShow(creditSale, { signal, ...requestOptions });

      

      

   return  { queryKey, queryFn, enabled: !!(creditSale), ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof creditSalesShow>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type CreditSalesShowQueryResult = NonNullable<Awaited<ReturnType<typeof creditSalesShow>>>
export type CreditSalesShowQueryError = AuthenticationExceptionResponse | AuthorizationExceptionResponse | ModelNotFoundExceptionResponse


export function useCreditSalesShow<TData = Awaited<ReturnType<typeof creditSalesShow>>, TError = AuthenticationExceptionResponse | AuthorizationExceptionResponse | ModelNotFoundExceptionResponse>(
 creditSale: string, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof creditSalesShow>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof creditSalesShow>>,
          TError,
          Awaited<ReturnType<typeof creditSalesShow>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useCreditSalesShow<TData = Awaited<ReturnType<typeof creditSalesShow>>, TError = AuthenticationExceptionResponse | AuthorizationExceptionResponse | ModelNotFoundExceptionResponse>(
 creditSale: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof creditSalesShow>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof creditSalesShow>>,
          TError,
          Awaited<ReturnType<typeof creditSalesShow>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useCreditSalesShow<TData = Awaited<ReturnType<typeof creditSalesShow>>, TError = AuthenticationExceptionResponse | AuthorizationExceptionResponse | ModelNotFoundExceptionResponse>(
 creditSale: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof creditSalesShow>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Display the specified credit sale
 */

export function useCreditSalesShow<TData = Awaited<ReturnType<typeof creditSalesShow>>, TError = AuthenticationExceptionResponse | AuthorizationExceptionResponse | ModelNotFoundExceptionResponse>(
 creditSale: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof creditSalesShow>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getCreditSalesShowQueryOptions(creditSale,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}




